### ISSUE TITLE
Data ownership copy and designs

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#1001]
In copy and design, find opportunities to push messages of "own your data" "apps for data ownership" vs. "Decentralized computing network and app ecosystem"

**Comment by moxiegirl** [comment]
@jeffdomke Also, the language "Decentralized computing network and app ecosystem" is throughout our documentation.  I like the new language direction but I want to confirm that this language was approved by the entire management team before I adjust for it.
