### ISSUE TITLE
Events pages shows flag of Slovakia instead of South Korea

### ISSUE THREAD

**Issue by Trudko** [blockstack/blockstack.org#1007]
**Describe the bug**
In the events section on the main page next to JSConf event in Soul is Slovak Republic flag instead of South Korea. This is caused [by a bad flag value ](https://github.com/blockstack/blockstack.org/blob/a96d797870b7aa619cee78ab0033a86decccf663/components/events/index.js#L12). I could create a pull request but question is if pass events should be on the page in the first place.

**Screenshots**
<img width="552" alt="image" src="https://user-images.githubusercontent.com/3289225/70045232-03380e00-15c4-11ea-9f73-de7f69962f45.png">

**Comment by markmhx** [comment]
Thanks for this report. It appears that the event is now gone from the site so this problem has been resolved implicitly.
