### ISSUE TITLE
Add Reddit Social Media Link 

### ISSUE THREAD

**Issue by louiseivan** [blockstack/blockstack.org#1016]
We need an official resource that we're handling this Reddit thread: https://www.reddit.com/r/blockstack/  

Can we please add a social link for Reddit under our community social footer. Please see the attached photo for reference. 

<img width="182" alt="Screen Shot 2020-01-29 at 3 45 42 PM" src="https://user-images.githubusercontent.com/58204144/73366549-6dacb800-42ae-11ea-96c5-96240f243427.png">

**Comment by joshthegreatavenue** [comment]
I believe adding Reddit to the footer will help a lot when trying to submit Social Links to CMC. :)
