### ISSUE TITLE
Blockstack.org quick copy changes: roadmap and homepage 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack.org#1019]
Hey @markmhx, would it be possible for us to make some quick updates to the blockstack.org website copy? The proposed changes are: 
- ✅[here](https://paper.dropbox.com/doc/Blockstack-Roadmap-Planning-doc--AtZjANKbWDFVJiuhNij3AgZUAg-f0PfvXvP4djCdKr0IhWot) and 

- [here](https://paper.dropbox.com/doc/Quick-Website-Updates-Jan-2019--AtZKxSTumJ41uuSkWaJxg2WwAg-FKx881MWQT7ptbC7SD9P7)

**Comment by markmhx** [comment]
@jeffdomke manages blockstack.org so I'm assigning this to him for review

**Comment by GinaAbrams** [comment]
ping @jeffdomke 🙏

**Comment by GinaAbrams** [comment]
At a minimum can we update the [roadmap](https://paper.dropbox.com/doc/Blockstack-Roadmap-Planning-doc--AtZjANKbWDFVJiuhNij3AgZUAg-f0PfvXvP4djCdKr0IhWot). cc @aulneau

**Comment by markmhx** [comment]
@aulneau did you end up pushing any of these changes?

**Comment by markmhx** [comment]
@GinaAbrams @aulneau I'm iceboxing this since haven't heard back.

**Comment by GinaAbrams** [comment]
The second bullet items were not updated or added. Let me know how we can get these to move forward.

**Comment by markmhx** [comment]
Which are the second bullet items? Not sure I follow.

**Comment by GinaAbrams** [comment]
[Here](https://paper.dropbox.com/doc/Quick-Website-Updates-Jan-2019--AtZKxSTumJ41uuSkWaJxg2WwAg-FKx881MWQT7ptbC7SD9P7 )

**Comment by markmhx** [comment]
Closing this out since the related changes are now tracked in other issues
