### ISSUE TITLE
Remove App Mining Links from Blockstack.org footer 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack.org#1024]
Highlighted here, can we please remove these 🙏 

![](https://paper-attachments.dropbox.com/s_D3735F1B008CE155469BE3992569223D9387A0005A81EFC26D969EEAFD8EF215_1581360468249_image.png)

**Comment by markmhx** [comment]
@aulneau please tackle this after your work on the authenticator developer release
