### ISSUE TITLE
Update articles on homepage

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#1030]
- Place [article about Envelop](https://www.coindesk.com/this-file-sharing-dapp-shows-how-blockstack-and-ethereum-are-different) in first position of three
- Update Santi Siri's title to "Sérgio dos Santos is Giving You Control and Piece of Mind When Your Important Files"

![image](https://user-images.githubusercontent.com/28991/75148550-32ac7180-5700-11ea-82c4-778fabd3b195.png)

**Comment by markmhx** [comment]
Looks good but I just realized the title change isn't actually grammatically correct. 

@GinaAbrams @cuevasm Do we want it to say "With" instead of "When" (aka "...and Peace of Mind With Your Important Files")?

**Comment by cuevasm** [comment]
Yes thanks, 'with'
