### ISSUE TITLE
Readme.md has broken image and link

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/blockstack.org#1035]
The readme contains a broken link to the Blockstack logo.

`<img src="https://media.githubusercontent.com/media/blockstack/designs/master/logo/RGB/bug/blockstack-bug-rounded-256x256.png" width=72 height=72>`

The discord chat link and badge a little further down is incorrectly formatted as well:

`[![Discord](https://img.shields.io/discord/621759717756370964](http://chat.blockstack.org)`

Screenshot below:

![2020-02-25 17 37 25 github com ab611ad7bb93](https://user-images.githubusercontent.com/9038904/75300850-5fdb4b80-57f6-11ea-8dcd-02b7b9fa7d74.png)

**Comment by timstackblock** [comment]
<img width="1163" alt="Screen Shot 2020-02-28 at 8 11 55 AM" src="https://user-images.githubusercontent.com/49165468/75551363-0d6e7a80-5a02-11ea-9b6f-698e819ab0f3.png">


Still looks broken

**Comment by whoabuddy** [comment]
If you look at the before and after the discord link is fixed and the badge works now, but I couldn't find a source for the logo image.

I wasn't sure if they want to remove the image like on other repositories or pull one from the live website or similar. The github content for branding is stored in Git LFS.

**Comment by whoabuddy** [comment]
Resolved by #1043
