### ISSUE TITLE
Remove App Mining section from home and technology pages 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack.org#1038]
Hello, can we please remove app mining as a section on blockstack.org homepage? 
https://blockstack.org/ ? 

Here's the text: 
App Mining
Build an app and get paid monthly with App Mining
Every month we pay out $200,000 to the best apps built on Blockstack. The better your app, the more you earn.

**Comment by markmhx** [comment]
I presume we want to remove the same section from here on the "Technology" page as well:

<img width="1260" alt="Screen Shot 2020-03-05 at 11 31 28" src="https://user-images.githubusercontent.com/28991/75987557-6487ba00-5ef0-11ea-921b-887ff502ddd4.png">
