### ISSUE TITLE
Remove "Create ID" and "Sign In" from site navigation and footer

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#1039]
![Screen Shot 2020-03-05 at 13.35.15.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/23fc0be8-3336-4cbe-a181-f8e936a4204a)![Screen Shot 2020-03-05 at 13.35.19.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/3924912f-5fb1-4a0b-965d-2269aa9c81e6)

**Comment by jasperjansz** [comment]
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/65be6fb4-2889-461e-81d2-932ab67b5761)

this is a bigger task than just removing them as it will make the menu look very bad

**Comment by markmhx** [comment]
I'm closing out this issue since these removals are incorporated into the work on https://github.com/blockstack/blockstack.org/issues/1054.
