### ISSUE TITLE
Update "Authentication" section graphic on "Technology" page

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#1041]
So that it doesn't reflect the old way off showing permissions:

![Screen Shot 2020-03-05 at 13.54.06.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/f3964a7f-0328-4afb-bddc-00fe09deaffd)

**Comment by markmhx** [comment]
@jasperjansz Can you provide a link to the Figma component here or attach an SVG for this updated graphic once ready?

**Comment by jasperjansz** [comment]
https://www.figma.com/file/LDiZPndnqfRjZnwTIMCzNMjr/Website?node-id=3568%3A23893
