### ISSUE TITLE
Create faucet page

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#1047]
STX

[Webflow page](https://webflow.com/design/www2-blockstack-org?pageId=5e7c9b306c5cf04978ff5989)

**Comment by markmhx** [comment]
@jasperjansz will add both BTC and STX forms in Figma, integrate into Webflow, then assign @hstove for end-to-end integration there.

**Comment by markmhx** [comment]
Need to release just STX faucet for Neon

**Comment by markmhx** [comment]
@hstove Let's be sure to add basic input pattern validation here when you wire it up (eg minimum address length)

**Comment by markmhx** [comment]
I'll wire up the success and error states now that Hank has the API set up

**Comment by markmhx** [comment]
The states are wired up, but @hstove needs to confirm now that the API always returns proper HTTP codes for success and errors. Once that's confirmed, we can move to QA.

**Comment by markmhx** [comment]
@hstove I'm still seeing the API return success for incorrect address inputs – is that expected?

**Comment by markmhx** [comment]
![Screen Shot 2020-04-22 at 09.35.35.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/2c683a79-9e35-4a21-a4cb-9d32acc110aa)

**Comment by timstackblock** [comment]
CORS error on the faucet

![Screen Shot 2020-04-22 at 8.38.35 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/3930c37d-db26-495f-8fba-24fd9cbe5f4c)

**Comment by markmhx** [comment]
Weird – the API must be actively evolving today 🐛

**Comment by timstackblock** [comment]
Yea things are still changing it may be to early to test. the form specifies the field name as STX-Address but the api endpoint expects address

**Comment by zone117x** [comment]
Faucet endpoint was previously was just stubbed out. It is actually implemented now -- but the request page form needs modified a bit to work.

**Comment by markmhx** [comment]
@jasperjansz has made the field change. @timstackblock can you test again?

**Comment by timstackblock** [comment]
<img width="1439" alt="Screen Shot 2020-04-22 at 10 55 54 AM" src="https://user-images.githubusercontent.com/49165468/79997730-dcea1080-8487-11ea-8e58-c8c81aa8a0b9.png">

**Comment by markmhx** [comment]
@zone117x is this something you can fix on the API side?

**Comment by zone117x** [comment]
Technically yes, but the API should not be using an adhoc label for the address field

**Comment by markmhx** [comment]
Adhoc label? Not sure I follow  :butterfly: :thinking_face: :egg:

**Comment by markmhx** [comment]
Getting a 500 error from the API when entering a valid STX address that we need to change ASAP for launch. @zone117x @hstove ?

![Screen Shot 2020-04-23 at 09.49.33.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/ee8a2791-0953-483c-80ae-0aeda5a31e02)

**Comment by timstackblock** [comment]
The errors above are resolved, we still need to make sure that addresses created from the CLI wallet can receive tokens, is this currently possible? @hstove

**Comment by markmhx** [comment]
@hstove @yknl can one of you confirm whether addresses from the CLI wallet should work with this faucet?

**Comment by yknl** [comment]
Yes any valid address generated for the correct network will work for receiving tokens. In this case the CLI just needs to be querying the right core node API to retrieve the balance. That's currently working using the steps on the [Testnet CLI docs](https://docs.blockstack.org/core/smart/cli-wallet-quickstart.html#checking-balance).

**Comment by timstackblock** [comment]
Ok I will test this when the CLI changes are complete thank @yknl
