### ISSUE TITLE
Update site navigation to incorporate testnet and remove direct links to authenticator

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#1054]
The Figma design can be found [here](https://www.figma.com/file/7wgEaERplteuVKC2uUXTtl/Website-2.0?node-id=295%3A1280). @jasperjansz can you provide guidance in Figma for the navigation's dropdown menu on hover in particular? In the meantime it can previewed on staging in Webflow [here](https://www-blockstack.webflow.io/).

I'm assigning both @jasperjansz and @aulneau since we need to integrate the new site nav and footer in both Webflow and the Next.js app, and you two can tackle that interation in Webflow and Next.js respectively.

The "Testnet" option under "Technology" and the "Try apps" option should go to the new testnet page and the existing "Try Blockstack" page respectively, both hosted by Webflow (and the latter replacing the current content found at `/try-blockstack`).

We have a pending question on what URLs we should use for these two pages, with their respective trade-offs.

If we host them both at the same subdomain (`www2.blockstack.org/testnet` and `www2.blockstack.org/try-blockstack`), then we can manage both pages in the same Webflow project. That would allow us to maintain just one CMS and set of symbols, styles, etc. for use across both instead of cloning the project into two, incurring redundancy and risking divergence.

We could also easily migrate other pages to Webflow when the time comes (e.g. @jasperjansz is already working on changes to the "Technology" page itself) without having to spin out even more Webflow project copies and subdomains (e.g. `www2.blockstack.org/technology` instead of `techology.blockstack.org` alongside `community.` and `blog.`, which seems like a disjointed attempt to maintain the same holistic UX despite placing them on clearly distinguished subdomains).

If we host them at separate subdomains (`testnet.blockstack.org` and `try.blockstack.org`), we could avoid any possible confusion with the `www2.` approach. However, it's not clear who'd be confused or even notice `www2.` when navigating the site. And if they did notice, the subdomain `www2.` would presumably connote "you're on the same site" more than `testnet.` etc.

Let's discuss this choice, however, since there may be other considerations at play.

Note for @aulneau that we'll need to set up a redirect for the Next.js app to redirect `/try-blockstack` to whatever URL we do choose here.

**Comment by aulneau** [comment]
I think if we are going with option 2 from the previous doc, then it doesn't matter if we have all the pages in webflow vs different projects, we'd be able to pick which things lived where. Eg we would export all of the pages and determine that x lives at try, and y lives at testnet. I really think we should use those subdomains versus a www2 scenario. So I think it makes sense to keep them in one, if that makes it easier to design.

> If we host them both at the same subdomain (www2.blockstack.org/testnet and www2.blockstack.org/try-blockstack), then we can manage both pages in the same Webflow project. That would allow us to maintain just one CMS and set of symbols, styles, etc. for use across both instead of cloning the project into two, incurring redundancy and risking divergence.

This seems directly contrary to this advantage listed in the doc:

> If we ever need to break blockstack.org into individual websites, we can easily clone a Webflow project into separate projects for hosting on separate domains. The existing work on pages within Webflow can be preserved and extended with little extra effort.

---

> However, it's not clear who'd be confused or even notice www2. when navigating the site. And if they did notice, the subdomain www2. would presumably connote "you're on the same site" more than testnet. etc.

I don't think it's ever been about if anyone would be confused by the www2 it's more that trying to make it seem like two sites are the same one creates some complexity and room for error. Things can get cached weird, and the UX could be more negative, eg things will look different between the two.

**Comment by markmhx** [comment]
Per our meeting last Thursday and discussion on the devops issue referenced above, it appears we're going with `testnet.blockstack.org` for the "Testnet" option and `www2.blockstack.org/try-blockstack` for the "Try Blockstack" option.

@aulneau will you have the capacity this week to stage the new site nav and footer for review by tomorrow / Tuesday (one day before testnet launch on the 22nd)? And is there any other guidance you need from us here?

**Comment by markmhx** [comment]
In Webflow, need to fix dropdown disappear issue and wire up `www2.blockstack.org/try-blockstack`

**Comment by markmhx** [comment]
@aulneau is going to tackle this for launch by simply adding a "Testnet" option under the existing site nav

@jasperjansz can you provide an icon for him to use there?

**Comment by jasperjansz** [comment]
[testnet-icon.svg.zip](https://github.com/blockstack/blockstack.org/files/4516314/testnet-icon.svg.zip)

**Comment by markmhx** [comment]
@aulneau any updates on getting this staged? We're looking to launch the testnet website by 10:45am EDT today.

**Comment by markmhx** [comment]
This has been released.

**Comment by markmhx** [comment]
The launch change for this issue was released, but the full site nav and footer change on blockstack.org is still pending.
