### ISSUE TITLE
Validate faucet inputs

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#1068]
[![Screenshot_2020-04-17_21-14-48.png](https://mrkr.io/s/5e9a1c4813886c6f71ea04bc/2)](https://mrkr.io/s/5e9a1c4813886c6f71ea04bc/0)

Should display some errors and success. Right now nothing happens. Address should probably take anything but the amount field should not take letters? 

**View all issue details in Marker.io:** https://marker.io/i/5e9a1c4813886c6f71ea04bd_455f65d17a684fc5

---
### More Info

**Source URL**: [file:///Users/jeffdomke/Downloads/IMG_0978.PNG](file:///Users/jeffdomke/Downloads/IMG_0978.PNG)

<table><tr><td><strong>Browser</strong></td><td>Chrome 80.0.3987.163</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>1136 x 864</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by markmhx** [comment]
This page is still in development so closing this issue out in favor of https://github.com/blockstack/blockstack.org/issues/1047
