### ISSUE TITLE
Headline copy change

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#1069]
[![Screenshot_2020-04-17_21-19-50.png](https://mrkr.io/s/5e9a1d76f78cd90a5253a544/2)](https://mrkr.io/s/5e9a1d76f78cd90a5253a544/0)

Suggestion: 

Help build the user owned internet. Test the latest builds for Stacks nodes, Stacks mining, Clarity smart contracts, and more. 

**View all issue details in Marker.io:** https://marker.io/i/5e9a1d768135db0aa2dc6ede_28a6b2d320ee3ba0

---
### More Info

**Source URL**: [https://www-blockstack.webflow.io/](https://www-blockstack.webflow.io/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 80.0.3987.163</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>1286 x 877</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by markmhx** [comment]
@cuevasm want to provide your input on this change? @jasperjansz is going to move ahead and make it assuming it's good with you.

**Comment by cuevasm** [comment]
@pstan26  and I left our suggestions on the Figma Jasper provided, I don' think we got invited to marker. What's there or what Jeff sent is fine with me. The important thing is that Patrick and Muneeb are a thumbs up at this point.

**Comment by markmhx** [comment]
@jeffdomke mind inviting all of us here to marker so we can use it and see the current issues there?

**Comment by cuevasm** [comment]
I'm good with you guys finalizing for now so we don't slow this down. If we come up with something massively better it's easy to update. I would optimize for getting sign off from Muneeb now.

**Comment by jeffdomke** [comment]
This is a screenshot tool that dumps everything into github. This is everything. The link is just to try and acquire you.

**Comment by markmhx** [comment]
_We've been acquired noooooooooooo_ 🛸🛸🛸
