### ISSUE TITLE
Copy change: Try Stacking

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#1072]
[![Screenshot_2020-04-17_21-26-50.png](https://mrkr.io/s/5e9a1f1954d1ed6f42889894/2)](https://mrkr.io/s/5e9a1f1954d1ed6f42889894/0)

Suggestion: 

'Lock your (testnet) STX and earn (testnet) Bitcoin'

Not in love with this either. Needs to be clear not real bitcoin and that the point is to test the mechanism vs. earn money. 

**View all issue details in Marker.io:** https://marker.io/i/5e9a1f1a298f1c0a0266f18b_e7f700702b88192c

---
### More Info

**Source URL**: [https://www-blockstack.webflow.io/](https://www-blockstack.webflow.io/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 80.0.3987.163</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>1286 x 877</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by markmhx** [comment]
How about "Simulate how you'll be able to earn Bitcoin on mainnet by locking STX tokens" for the subtitle here with "Try Stacking" maintained as the title?
