### ISSUE TITLE
Copy change email capture

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#1073]
[![Screenshot_2020-04-17_21-31-57.png](https://mrkr.io/s/5e9a204d58670b0a07f12d76/2)](https://mrkr.io/s/5e9a204d58670b0a07f12d76/0)

Pretty sure should be 'testnet' 

**View all issue details in Marker.io:** https://marker.io/i/5e9a204d397fe56ef1ba03a2_0e663c18d50cc656

---
### More Info

**Source URL**: [https://www-blockstack.webflow.io/](https://www-blockstack.webflow.io/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 80.0.3987.163</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>1286 x 877</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by markmhx** [comment]
@cuevasm are we generally treating "testnet" as a proper noun or not?

**Comment by cuevasm** [comment]
Not when the word testnet is alone, but when I say 'the Stacks 2.0 Testnet' I consider that a proper noun. A quick look at other projects tends to support that, but I don't feel strongly if we want to do something different.

**Comment by markmhx** [comment]
Cool, @jasperjansz let's lowercase it in this case then.
