### ISSUE TITLE
Copy change: Complete stack...

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#1075]
[![Screenshot_2020-04-17_22-19-37.png](https://mrkr.io/s/5e9a2b780c2b326ef686957a/2)](https://mrkr.io/s/5e9a2b780c2b326ef686957a/0)

Suggested changes: 

--

A user owned internet, anchored in Bitcoin

Stacks 2.0 introduces a revolutionary new consensus mechanism, ultra-secure smart contract language, and elegant solutions for long term scaling and performance. 

--

Mining with Proof of Transfer

Stacks miners transfer Bitcoin in order to process new blocks and mint new STX tokens. The Bitcoin they transfer is forwarded STX holders. The process requires no electricity or special hardware and allows Stacks to inherit the same security as Bitcoin. 

Earn Bitcoin with Stacking

STX holders can temporarily lock their STX and earn Bitcoin as a reward. The locking transactions increase security by anchoring the Stacks Blockchain to the Bitcoin Blockchain. As a reward for this security boost STX holders earn Bitcoin.

Author with Clarity Smart Contracts

Clarity is the safest language for writing Smart Contracts, optimized for predictability and security. Clarity executes completely on the Stacks blockchain: No compiler errors or unpredictable behavior. 

**View all issue details in Marker.io:** https://marker.io/i/5e9a2b798135db0aa2dc6eeb_4af6e9ba0f9b970b

---
### More Info

**Source URL**: [https://www-blockstack.webflow.io/](https://www-blockstack.webflow.io/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 80.0.3987.163</td></tr><tr><td><strong>Screen Size</strong></td><td>1440 x 900</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>1286 x 877</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by markmhx** [comment]
@cuevasm want to provide your thoughts on these changes since you helped draft a lot of this content? @jasperjansz will start applying the changes that look obvious to him.

**Comment by cuevasm** [comment]
The original that is being reviewed is not the latest from @pstan26 and I so it's hard to track now.  

![image](https://user-images.githubusercontent.com/6131188/79738330-e4c97980-82fc-11ea-9885-dd585b2b235c.png)

I'm fine with Jeff's as long as Patrick is

**Comment by markmhx** [comment]
@pstan26 want to sign off on this change?

**Comment by jeffdomke** [comment]
Please change the headline. I do not sign off the the headline. I'm fine with another variant but current one needs to change.

**Comment by markmhx** [comment]
@jeffdomke this variant look better?

[Screen Shot 2020-04-22 at 16.42.04.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/f8538e01-486d-460d-8812-dbc149d9b97c)

**Comment by markmhx** [comment]
I'm closing this assuming the change is fine since it's in line with @jeffdomke's originally suggestion here.
