### ISSUE TITLE
Wire up testnet page newsletter form

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#1077]

**Comment by cuevasm** [comment]
Np, will you invite me to Webflow please? 🙏

**Comment by markmhx** [comment]
Inviting you now, though you should be able to verify via manual testing on staging vs. the admin panel per se since it's set up via Zapier now I believe?

**Comment by cuevasm** [comment]
Yeah was just anticipating needing to update it for the full site launch potentially

**Comment by markmhx** [comment]
@cuevasm have you been able to confirm this is working front to back with the zap?

**Comment by markmhx** [comment]
@cuevasm have you been able to confirm this is working front to back with the zap?

**Comment by cuevasm** [comment]
On staging, yes.
