### ISSUE TITLE
Fix FAQ links

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#1087]
![image.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/54b33a25-bda6-4c63-afe4-c7a9a289b9f5)

**Comment by markmhx** [comment]
On bounties page

**Comment by markmhx** [comment]
@timstackblock are you seeing this problem where the dropdown menu intermittently disappears before you can make a selection when hovering over "Technology" and trying to select an item (e.g. "Overview")?

I find it's 50/50 for me but @jasperjansz can't recreate it. And tweaking the styles hasn't helped me fix it on my end yet.

**Comment by timstackblock** [comment]
No it seems to work fine for me but i did notice we have a place holder for a [LINK] and it was not populates please see the screen shot below. @jasperjansz @markmhx 

![Screen Shot 2020-04-23 at 8.36.14 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/f8120273-a23a-4c01-94e4-4d2103be3211)

**Comment by timstackblock** [comment]
We also have a broken link here https://github.com/blockstackers/testnet-community-bounties

![Screen Shot 2020-04-23 at 8.40.21 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/e8b2956f-41f2-459a-8969-196da8ac399f)

**Comment by timstackblock** [comment]
We have a broken link here as well that opens up a 404 page http://testnet-legacy.blockstack.org/.

![Screen Shot 2020-04-23 at 8.44.36 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/0c919857-9b30-42bf-a97c-23a5e13b35fa)

![Screen Shot 2020-04-23 at 8.45.03 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/ede10269-2ca8-45f1-8bab-f2eaab08c1c0)

**Comment by markmhx** [comment]
Thanks @timstackblock 

@ryanarndtcm can you fix the two FAQ links above?

The legacy testnet URL is getting fixed with https://github.com/blockstackpbc/devops/issues/251#issuecomment-618368558

**Comment by ryanarndtcm** [comment]
sure thing. the community bounties one is not live yet, so added coming soon on it. the rest is complete.
