### ISSUE TITLE
Link "Submit a bug report" and guidelines on bounties page

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#1088]
![Screen Shot 2020-04-22 at 09.24.23.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/1c139aa3-cae1-460a-aa73-6c9447220bac)

@xanbots can you provide links here for both options?

@fjl4 needs to review the guidelines once provided here.

**Comment by markmhx** [comment]
@xanbots @fjl4 Please clarify if you can how the "Testnet Bounties Terms" paper doc relates to these options as well or whether those terms need to be referenced in some other way from the testnet website by launch.

**Comment by fjl4** [comment]
Maybe instead of "guidelines" we could say "terms" or "details" and have the link jump to the bottom of the page with the terms.

**Comment by xanbots** [comment]
If the terms in paper are what we mean by guidelines then would agree with Freddie. Switch to say "terms" and link below, for submit on github for bug bounties can link to https://github.com/blockstack/stacks-blockchain. For tool bounties believe we already have the correct links included

**Comment by fjl4** [comment]
Also, the legal terms in Paper are meant to apply to all of the bounties, not just the bug bounties.

**Comment by markmhx** [comment]
Sounds good. And the legal terms in Paper are finalized, yea?

**Comment by fjl4** [comment]
Yep, good to go.
