### ISSUE TITLE
Incorrect max amount for tool bounty

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/blockstack.org#1095]
**Describe the bug**
Incorrect max amount for tool bounty.

**To Reproduce**
Says "up to $10,000 in BTC" on the main page, but if you click through to `/bounties`, doesn't mention that amount anywhere.

**Expected behavior**
Max amount on home page should match what's in `/bounties`. Looks like $2500?

**Screenshots**
<img width="337" alt="Screenshot 2020-04-22 21 23 14" src="https://user-images.githubusercontent.com/15990/80049148-29f9d100-84e0-11ea-9602-5e5fd77c7095.png">

**Comment by markmhx** [comment]
@jasperjansz let's update to $2,500 on the homepage.

@xanbots please confirm this change

**Comment by xanbots** [comment]
confirmed
