### ISSUE TITLE
Inconsistent max amount for bug bounty

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/blockstack.org#1097]
**Describe the bug**
Home page says "up to $1000", bounties page says "max $2000 per bug"

**Expected behavior**
Consistent amounts in both locations.

**Comment by markmhx** [comment]
@jasperjansz please make this change and @xanbots please confirm

**Comment by xanbots** [comment]
The max reward for a bug bounty is $2,000 BTC, and we should use that everywhere.

Separately, the tooling bounty that currently has the highest reward is $2,500 BTC for the telemetry dashboard.
