### ISSUE TITLE
design new hero section

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#110]
Determine the current #1 focus for Blockstack
- Headline
- Subhead
- Imagery

**Comment by guylepage3** [comment]
@shea256 @muneeb-ali.. Shall we start the conversation around content first for the hero section?

I believe we last left off the discussion by saying that the current focus of the hero section should be around the "stack". 
1. Are we still ok with that?
2. Should we generate a list of ideas around what the hero section should focus on?

**Comment by shea256** [comment]
I like having a stack diagram, but I also like the idea of a silhouetted browser to build up anticipation.

**Comment by guylepage3** [comment]
Ok. So what is "the" current focus? I feel the browser hype is wise. We can add a "stack" page to the site as well. Maybe push that down below the fold. @jcnelson @muneeb-ali, can we get your thoughts as well?

**Comment by muneeb-ali** [comment]
I think the system diagram can go lower in the page. And in the hero you can build up anticipation for the browser.

**Comment by shea256** [comment]
OK I like that.

What is the headline going to be? The tagline?

Decentralized Web? Decentralized Apps?

**Comment by guylepage3** [comment]
Some ideas could be;
1. [Head] Decentralized Apps [Imagery] silhouette of browser (as suggested by @shea256)
2. [Head] Welcome to the decentralized web... Apps coming soon... [Imagery] silhouette of browser
3. [Head] Goodbye.. [Imagery] imagery "implying" App Store & Play Store will be gone with the silhouette of the browser above.

**Comment by jcnelson** [comment]
I like the emphasis on the browser, since that's the face of the product.

I prefer "decentralized web" over "decentralized apps," since I feel like that's what's currently being advocated by e.g. Tim Burners Lee and co.  I also think Web implies apps (i.e. I don't think non-expert users differentiate anymore).

I'd go with (2) in @guylepage3's list.

**Comment by shea256** [comment]
Yes I agree.

**Comment by guylepage3** [comment]
Complete

**Comment by guylepage3** [comment]
![hero 2x](https://cloud.githubusercontent.com/assets/1711854/19983690/605db4d6-a1e1-11e6-9c79-a14f1ec16a2f.png)

**Comment by guylepage3** [comment]
Latest hero section

<img width="1277" alt="screenshot 2016-11-10 18 19 52" src="https://cloud.githubusercontent.com/assets/1711854/20198380/4ec89d08-a772-11e6-99c0-d7d0e66e33fa.png">

**Comment by guylepage3** [comment]
Update to hero to allow for news and join the community sections to appear above the fold

<img width="1279" alt="screenshot 2016-11-14 17 56 08" src="https://cloud.githubusercontent.com/assets/1711854/20286245/c3329eea-aa93-11e6-8825-5b04f98db447.png">

And here it is in context with the landing view

<img width="1429" alt="screenshot 2016-11-14 17 52 48" src="https://cloud.githubusercontent.com/assets/1711854/20286252/d1618eea-aa93-11e6-9e01-c1b54c870d61.png">

**Comment by guylepage3** [comment]
![01-landing-view 2x](https://cloud.githubusercontent.com/assets/1711854/22041706/d5207a18-dcd5-11e6-83b1-8c1623d0fd86.png)

![01-landing-view-ios 2x](https://cloud.githubusercontent.com/assets/1711854/22042030/62c2ab9c-dcd7-11e6-975e-672b26b451fa.png)
