### ISSUE TITLE
Add link to question page from FAQ section on testnet page

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#1101]
So @ryanarndtcm can more easily find the URL to send around

![Screen Shot 2020-04-23 at 14.14.27.png](https://images.zenhubusercontent.com/5bd9c99be94b2d0d4ac03097/3d3f3b37-a434-4da4-903e-e4b6d907fc97)

**Comment by ryanarndtcm** [comment]
yes please, this will be a big help for the community managers sending information to people.
