### ISSUE TITLE
The Zero-to-Dapp tutorial page leads to nowhere

### ISSUE THREAD

**Issue by abhy-kumar** [blockstack/blockstack.org#1123]
**Describe the bug**
The Zero-to-Dapp tutorial page leads to nowhere from the main site.

**To Reproduce**
1. Go to [https://community.blockstack.org/z2d]
2. Click on '-> Start'
3. See error

**Expected behavior**
A valid webpage with tutorial on Z2D

**Screenshots**
![image](https://user-images.githubusercontent.com/35186422/86492946-44c4ad80-bd8d-11ea-8667-02275bc40955.png)

**Desktop (please complete the following information):**
 - OS: [Manjaro Linux, kernel v5.8]
 - Browser [Firefox]
 - Version [78.0.1]

**Comment by Escavalier** [comment]
Yes, i have been having the same issue

**Comment by markmhx** [comment]
Thanks for your reports, @abhy-kumar and @Escavalier!

@cuevasm want to update [this community site page](https://community.blockstack.org/z2d) to no longer feature Zero-to-Dapp?

I've created an issue in the documentation repo for setting up redirects in case we receive inbound traffic from elsewhere: https://github.com/blockstack/docs.blockstack/issues/645

**Comment by cuevasm** [comment]
All set! We didn't know that was getting pulled down so we're still catching up and scrubbing references, thanks peeps!
