### ISSUE TITLE
Top navigation items

### ISSUE THREAD

**Issue by agraebe** [blockstack/blockstack.org#1125]
I noticed the recent designs by @jasperjansz include a top nav bar with "Developers", "Run a node", and "Discover app".

I'd propose to unify the language and tweak the top-level navigation list items as follows:
- Build apps
- Try testnet
- Discover apps

Trying the testnet seems more important than running a node (until we have the Mainnet at least)

**Comment by markmhx** [comment]
Do all the items currently under "Developers" make sense for "Build apps" (sans "Testnet", moved outwards to replace "Run a node"? "Paper" and "Discord" look a little questionable to me.

**Comment by agraebe** [comment]
It could work if we call papers whitepapers/architecture/concept/technology.

For discord, I would suggest calling it support or similar. Getting support while building apps makes sense to me. wdyt?

**Comment by markmhx** [comment]
What if we changed it simply to "Start building" instead of "Build apps"? That way the realm of building is broader (and inclusive of e.g. just smart contracts)?

**Comment by agraebe** [comment]
👍

**Comment by markmhx** [comment]
Changed:

<img width="496" alt="Screen Shot 2020-07-10 at 14 39 04" src="https://user-images.githubusercontent.com/28991/87155380-24c84900-c2bb-11ea-981f-4e776df0ce09.png">
