### ISSUE TITLE
design landing view (below the fold)

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#113]
@shea256 @jcnelson @muneeb-ali.. 

For the home page communications we need to determine content and where the content will lay on the page by assigning the content to sections

See below for example;
![blockstack-home](https://cloud.githubusercontent.com/assets/1711854/17825822/0e31813a-6639-11e6-97a3-8e3f8c801b5f.png)

**Comment by guylepage3** [comment]
First crack at content in chronological order:
- hero section
- introducing apps
- stats
- blockstack diagram - possibly something similar to; https://21.co/setup/ diagram of the computer
- community section and links to everything
- call to action
- footer

**Comment by jcnelson** [comment]
Do you think stats should be higher up--possibly a footer in the hero section?  Stats say that the system is live and up and running (and not just an idea).  Now that I think about it a bit more, I wonder if we could do something like e.g. repo status (i.e. time of last commit, commit history and diff sizes over the week, etc.).

Love everything else, though :)

**Comment by guylepage3** [comment]
Closing this issue

**Comment by guylepage3** [comment]
depricated. no longer have a below the fold on the landing view
