### ISSUE TITLE
Illustration suggestion

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#1131]
[![Screenshot_2020-07-12_19-05-03.png](https://mrkr.io/s/5f0b5ebe1b2a1a071449d7e1/2)](https://mrkr.io/s/5f0b5ebe1b2a1a071449d7e1/0)

Think we could edit and simplify here. The key and keyhole shapes are complex not that legible. Probably just the key can do the trick. 

**View all issue details in Marker.io:** https://marker.io/i/5f0b5edfc3e80d07d2e7a909_8722f6819e384ed8

---
### More Info

**Source URL**: [https://www-blockstack.webflow.io/home](https://www-blockstack.webflow.io/home)

<table><tr><td><strong>Browser</strong></td><td>Chrome 83.0.4103.116</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.5</td></tr><tr><td><strong>Viewport Size</strong></td><td>1504 x 1246</td></tr><tr><td><strong>Zoom Level</strong></td><td>90%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;0.8999999761581421x</td></tr></table>

**Comment by markmhx** [comment]
Closing this since we'll be replacing this image in general
