### ISSUE TITLE
Copy suggestion for encrypted data storage section

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#1133]
[![Screenshot_2020-07-12_19-09-23.png](https://mrkr.io/s/5f0b5fe39f804806b89d5753/2)](https://mrkr.io/s/5f0b5fe39f804806b89d5753/0)

The database ref is awkward. Most apps do maintain a DB for starters. 

The larger point is that you can scale users and data without added cost. 

**View all issue details in Marker.io:** https://marker.io/i/5f0b5fe36bbc6806b7d52646_7db0fe8f38bb099a

---
### More Info

**Source URL**: [https://www-blockstack.webflow.io/home](https://www-blockstack.webflow.io/home)

<table><tr><td><strong>Browser</strong></td><td>Chrome 83.0.4103.116</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.5</td></tr><tr><td><strong>Viewport Size</strong></td><td>1504 x 1246</td></tr><tr><td><strong>Zoom Level</strong></td><td>90%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;0.8999999761581421x</td></tr></table>

**Comment by markmhx** [comment]
The "no maintenance" part seems central to me, even more than the costs of scaling. It's a part of the "fewer moving parts to worry about and maintain" angle, even pre-scaling during MVP testing mode.

I'm not sure if most apps do use Radiks or some other centralized DB alongside Gaia either. Though I imagine we want to lean into the "no database" scenario.

@jasperjansz how did test subjects receive this copy?
