### ISSUE TITLE
Jobs out of date. Closed jobs 404

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#1135]
[![Screenshot_2020-07-12_19-13-26.png](https://mrkr.io/s/5f0b60d6901341070963f4ad/2)](https://mrkr.io/s/5f0b60d6901341070963f4ad/0)

Steps to reproduce:

Actual result:

Expected result:

**View all issue details in Marker.io:** https://marker.io/i/5f0b60d69f804806b89d5757_3be0bee4389c6d77

---
### More Info

**Source URL**: [https://www-blockstack.webflow.io/about](https://www-blockstack.webflow.io/about)

<table><tr><td><strong>Browser</strong></td><td>Chrome 83.0.4103.116</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.5</td></tr><tr><td><strong>Viewport Size</strong></td><td>1507 x 1351</td></tr><tr><td><strong>Zoom Level</strong></td><td>90%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;0.8999999761581421x</td></tr></table>

**Comment by markmhx** [comment]
Which of these jobs are now closed?

**Comment by markmhx** [comment]
I've removed the docs position and added the growth one:

<img width="912" alt="Screen Shot 2020-07-13 at 15 26 07" src="https://user-images.githubusercontent.com/28991/87309699-3ad54400-c51d-11ea-9e9d-a69e8ec3e150.png">

This content in Webflow is currently getting managed manually in the CMS while I research how to wire it up automatically with Zapier.
