### ISSUE TITLE
Papers design upgrade

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#1136]
[![Screenshot_2020-07-12_19-16-44.png](https://mrkr.io/s/5f0b619c2d40c20781894955/2)](https://mrkr.io/s/5f0b619c2d40c20781894955/0)

They way these papers are displayed is a bit messy. Imagine someone new trying to navigate. Maybe they just want a brief, but detailed, sense of what is going on.

There are 11 different docs there.

I think we could visually signal where to begin, also what docs are "prime" vs. ancillary info. Maybe we can cluster stuff that is all under a theme. 

**View all issue details in Marker.io:** https://marker.io/i/5f0b619c11b40e07eed0af2f_a8020e86ef87d3f1

---
### More Info

**Source URL**: [https://www-blockstack.webflow.io/papers](https://www-blockstack.webflow.io/papers)

<table><tr><td><strong>Browser</strong></td><td>Chrome 83.0.4103.116</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.15.5</td></tr><tr><td><strong>Viewport Size</strong></td><td>1507 x 1351</td></tr><tr><td><strong>Zoom Level</strong></td><td>90%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;0.8999999761581421x</td></tr></table>

**Comment by jasperjansz** [comment]
Split these into 'Fundamentals' and 'Dive deeper' with a toggle in the Papers CMS.
![image](https://user-images.githubusercontent.com/25477905/87939112-d9225600-ca97-11ea-9b05-83dbe98dd7f0.png)
