### ISSUE TITLE
Update top ribbon with Q2 updates

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack.org#1141]
Link to: https://blockstack.org/updates/q2-2020-community-update
Something like this should work:
![#BlackLivesMatter (3)](https://user-images.githubusercontent.com/6131188/87922986-0ad9f380-ca7d-11ea-8204-e1163c6fe04c.png)

**Comment by jasperjansz** [comment]
staged here: https://www-blockstack.webflow.io/home
