### ISSUE TITLE
Prevent Kakao option in site footer from wrapping to new line

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#1143]
<img width="141" alt="Screen Shot 2020-07-21 at 08 10 12" src="https://user-images.githubusercontent.com/28991/88064729-f3c5ff00-cb6b-11ea-967c-1bed19542ba9.png">

**Comment by jasperjansz** [comment]
@markmhx When does this happen for you? For me it doesn't happen, not even on a 320px wide screen

**Comment by markmhx** [comment]
Usually happens to me late at night when I can't fall asleep so I pull out my phone to check if it's still happening 📱😆

**Comment by markmhx** [comment]
<img width="1171" alt="Screen Shot 2020-07-21 at 16 23 15" src="https://user-images.githubusercontent.com/28991/88066819-7ea7f900-cb6e-11ea-8b1b-702c7ea51c0c.png">

**Comment by jasperjansz** [comment]
Still don't see this, even when I scrolled through all the breakpoints pixel by pixel.

**Comment by markmhx** [comment]
I'm flummoxed 🤷‍♂️

**Comment by aulneau** [comment]
@jasperjansz it is happening to me, if you do `white-space: nowrap;` to `.footer` it fixes it.

**Comment by jasperjansz** [comment]
Just added no wrap. @markmhx can you verify if it's fixed, and if so, close the issue?

**Comment by markmhx** [comment]
Yep looks good 👍
