### ISSUE TITLE
Wrong github link in footer

### ISSUE THREAD

**Issue by dcts** [blockstack/blockstack.org#1147]
**Describe the bug**
the footer links to github.org instead of github.com. Tried to find it in the code but the component `footer` has the correct link. Not sure how that happened.

**Screenshots**
![Bildschirmfoto von 2020-07-23 18-20-53](https://user-images.githubusercontent.com/44790691/88311940-d3d04000-cd11-11ea-9e0a-021c021f9ac0.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Brave
 - Version 1.10.97

**Comment by jasperjansz** [comment]
Thank you — fixed!
