### ISSUE TITLE
Discord link at bottom of front page is expired. 

### ISSUE THREAD

**Issue by ryanarndtcm** [blockstack/blockstack.org#1148]
Here is a new, non-expiring one: https://discord.gg/9uaNPkH

Thanks!

**Comment by cuevasm** [comment]
The other discord reference wasn't actually even linked here: 

![image](https://user-images.githubusercontent.com/6131188/89027739-54eb9080-d32b-11ea-963e-854073fcaef6.png)

I've fixed both
