### ISSUE TITLE
Link in footer pointing to github.org/blockstack

### ISSUE THREAD

**Issue by zaryanz** [blockstack/blockstack.org#1152]
**Describe the bug**
The link for GitHub under "Stay up to date" in the footer points to github.org/blockstack, but it seems to be fine in the footer navigation code, maybe the code in production is not up to date?

**To Reproduce**
1. Go to blockstack.org
2. Scroll down to the footer
3.. Look at the GitHub link under "Stay up to date"

**Expected behavior**
The link should point to github.com/blockstack

**Screenshots**
![issue](https://user-images.githubusercontent.com/51870531/89873379-f7333000-dbd7-11ea-884a-934de5077406.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Firefox
 - 78.0.1 (64-bit)

**Comment by markmhx** [comment]
Fixed! Thanks for the report 🙏
