### ISSUE TITLE
Fix extension build links on install page

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#1153]
The link to the extension build on the ["Install Blockstack" page](https://www.blockstack.org/install) (listed in two places, with value https://987-203447698-gh.circle-artifacts.com/0/extension.zip) is broken.

@hstove I believe you mentioned that we'd have to keep this manually updated. But is there possibly a way to automate so we don't have to worry about this in general going forward?

<img width="670" alt="install-extension-link-broken" src="https://user-images.githubusercontent.com/28991/89997585-9c0f4500-dc8c-11ea-90fe-919dc7984b55.png">

**Comment by hstove** [comment]
Yes, @markmhx , this URL needs to be constantly updated. The current hard-coded solution won't work.

My recommendation for "build from source" docs is to link off to the instructions [here](https://github.com/blockstack/ux/tree/master/packages/app#building-and-using-as-a-browser-extension).

We _could_ have a server-side thing that always returns the latest ZIP, but I think we wouldn't even want that. The people building from source don't want a ZIP, they want the source code so they can build it themselves!

**Comment by markmhx** [comment]
I've updated this page with a link to those instructions on GitHub and generally cleaned up the format while adding an introductory paragraph:

<img width="675" alt="install-extension-instructions" src="https://user-images.githubusercontent.com/28991/90615051-d4be9980-e20b-11ea-9a7c-e234798c210d.png">
