### ISSUE TITLE
Delete EU representative from privacy policy

### ISSUE THREAD

**Issue by fjl4** [blockstack/blockstack.org#1155]
Please delete the paragraph indicated in red from https://www.blockstack.org/p/terms-privacy and from https://stackstoken.com/privacy

<img width="872" alt="Screen Shot 2020-08-18 at 3 54 23 PM" src="https://user-images.githubusercontent.com/43580604/90521983-78a43880-e16b-11ea-90ae-ec1ee26295b8.png">

**Comment by markmhx** [comment]
I've deleted this from https://www.blockstack.org/p/terms-privacy

@cuevasm want to do the same for stackstoken.com?
