### ISSUE TITLE
How Blockstack works/Learn page

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#1158]
Our homepage content is sparse, and it's difficult to piece together a solid overview of how Blockstack works from the docs. We discussed creating a page that fills the gap.

Here's how other projects do something similar:
Ethereum: Learn https://ethereum.org/en/learn/
Cosmos: What is Cosmos? https://cosmos.network/intro 
Solana: Developers https://solana.com/developers
Understanding Urbit: https://urbit.org/understanding-urbit/ 
Why Avalanche: https://www.avalabs.org/why-avalanche
Polkadot Technology: https://polkadot.network/technology/
Libra Developers: https://libra.org/en-US/developers/ 

Create a page that explains key concepts, benefits, and how Blockstack is different. CTA is to send people to the docs to start building.

**Comment by markmhx** [comment]
I'm closing this issue since this page has been released. We can open new issues if we decide to improve it further.

https://www.blockstack.org/how-blockstack-works
