### ISSUE TITLE
Add “How to contribute?" to docs README.md

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#116]
Add “How to contribute?" to docs README.md

**Comment by shea256** [comment]
@guylepage3 can you explain what you mean by this?

**Comment by guylepage3** [comment]
@shea256, it would be nice to have a step by step guide on how community members may contribute to the project. I am not sure if this should be a repo-to-repo specific guide or an all encompassing guide for members.

Here's an example:
[https://github.com/twbs/bootstrap#contributing](https://github.com/twbs/bootstrap#contributing)

**Comment by estermer** [comment]
could we just copy the one in blockstack-browser and keep the issue open to suggest any differences that the website would need?

**Comment by guylepage3** [comment]
@estermer. Copying and pasting what was talked about in the Slack #design channel.

One addition is that we could use semantic versioning and utilize patches for PR's. i.e. `guylepage3-patch`. Then i'll merge it into `design` and pass it off to @shea256 for final merge into `master`.

**Comment by estermer** [comment]
Could someone describe these labels for me? 

- production
- invalid
- duplicate
- wont-fix

**Comment by guylepage3** [comment]
- production - I will remove. not related to this repository
- invalid - I will remove
- duplicate - duplicate issue
- wont-fix - won't fix bug or issue

**Comment by estermer** [comment]
I added a table of contents section in the top of the guide. I think I am going to do this for other repos as well, they are just links to the the separate sections of the `.md`. But I am also adding other useful links that are  good to have as well. So far I just have [Blockstack Brand Guide](https://github.com/blockstack/designs/issues/247) added. Are there any more that we think would be good additional resources to contributing to the `blockstack.org` repo?

**Comment by guylepage3** [comment]
good idea @estermer, i can't think of anything off the top of my head. I think that's it for now.

**Comment by estermer** [comment]
OK cool we can alway add more if needed

**Comment by guylepage3** [comment]
sounds good sir.

**Comment by estermer** [comment]
Hey so I was thinking in the main README of the repo adding the link to the contributing guide to the top somewhere.

Also I was wondering how to point developers to it like:

`Before getting started, checkout our Contributing Guidelines!`

**Comment by guylepage3** [comment]
@estermer why don't we follow the same placement as we see on Bootstrap's main README.md?
https://github.com/twbs/bootstrap

How does that sound?

**Comment by estermer** [comment]
cool! gotta love those table of contents! haha

Also I noticed the link to Slack wasn't working, could someone double check it? right now it is https://chat.blockstack.org

**Comment by vsund** [comment]
@estermer I think there's just no HTTPS available, http://chat.blockstack.org works for me.

**Comment by estermer** [comment]
@vsund I noticed it was the https that was blocking

i changed it to http and it works fine now. Thanks 👍

**Comment by guylepage3** [comment]
Ok @estermer I see a couple of items to be adjusted with your PR:

1. Title should read "Contributing to Blockstack.org"
2. "Table of Contents" (TOC) "Blockstack Brand Guide" should actually be included into the "Pull Request" section as the first item that the contributor should review. Let's remove it from the TOC.
3. Put my name first under "Maintainers" as contributors will pull from my branch first.
4. "Project Boards" link under "Finding opportunities to contribute" is a dead link. Should link to the projects board for that repository.
5. "Issue Tracker" link under "Finding opportunities to contribute" is a dead link. Should link to the issue tracker for that repository.
6. "issue tracker" link under "Using the issue tracker" is a dead link. Should link to the issue tracker for that repository.
7. Under "Bug Reports" change "... latest `master` or development branch in the repository." to "... latest `master`, `design` or development branch in the repository."
8. Under "Pull Request" — There will be a new process where the contributor pulls from a branch called `contribute`. this will allow the maintainers of the repo to use any branch they please. maintainers will push their code to the `contribute` branch frequently.

**Comment by guylepage3** [comment]
Another two very important items to include in the Pull Request process is...

- It is up to the contributor to make sure the code they are submitting has no conflicts.

- Ensure that pull requests are small components. This assists both with your pull request getting accepted and makes it much easier/faster for the repository maintainer to merge in your pull request.

**Comment by guylepage3** [comment]
Also, @estermer we are going to want to start versioning everything. So for example, right now we are on v4.0 of blockstack.org. If we have everyone pulling from a branch with the current version number then it should be much easier to maintain. we do want to keep with the remote creation that we currently have though. But add in the version number portion. once these are complete. i will take another look at the pull request.

**Comment by estermer** [comment]
@guylepage3 I will hop on those tasks.

I will say the links that are dead are only that way because It is on my repo and no yours. If you want I can give the full path, but I noticed in most of your MD files, you have the relative URI such as `/issues` for example.

**Comment by estermer** [comment]
@guylepage3 OK I made the changes that you suggested, except the versioning, I am not sure what your thinking on that and if that is something i need to add since it is not fully implemented at this time.

**Comment by guylepage3** [comment]
>Also I am not totally sure what you mean with the versioning. Would you re-elaborate?

Ok. So we deploy [semantic versioning](http://semver.org/) wherever possible. (Please read http://semver.org/) We are currently doing this with the [Blockstack Browser](https://github.com/blockstack/blockstack-browser) for example. 

**Semantic Versioning**
MAJOR.MINOR.PATCH —› **v3.4.21**

So with our pull request process we will have the contributor pull from the latest "MINOR" release.
