### ISSUE TITLE
Edit text on Blockstack.org/roadmap

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack.org#1162]
Hello, I'm hoping to get a simple text change on blockstack.org/roadmap. Under *H2 2020* can we please change the text to: Stacks 2.0 mainnet will launch upon successful exiting all ~five~ four testnet phases. 

That's all, I tried logging into webflow and it wasn't working but happy to be pointed to the resources on how we make and request these changes and go that route. Thx!

**Comment by markmhx** [comment]
Fixed! I'll ping you on Slack about resolving the Webflow login issues.
