### ISSUE TITLE
Update Fathom integration to use site-specific tracking

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#1164]
[As discussed in Discord ](https://discord.com/channels/621759717756370964/752876353572962314/760847444333559848) with @cuevasm and @aulneau, we should integrate Fathom specifically for blockstack.org only instead of the current situation where data from blockstack.org, blog.blockstack.org and community.blockstack.org all flow into the same Fathom "site" and are mixed together in reporting.

This issue tracks this update specifically for blockstack.org, whereas the two other sites should be updated as well but tracked separately.

Assigning to @cuevasm to set up the Fathom sites and provide code info.

**Comment by cuevasm** [comment]
Done, you can see blockstack.org in there by itself under 'blockstack.org (only).

**Comment by markmhx** [comment]
@cuevasm did you update Webflow and everything?

**Comment by cuevasm** [comment]
Of course, and tested that everything is collecting data.
