### ISSUE TITLE
Landing page for Stacks 2.0 launch

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack.org#1169]
Generally, I would like some design guidance on a landing page to house our Stacks 2.0 launch event. I typically handle these myself, but with the new brand and this being an extra special occasion, I want more firepower. I can still handle building and maintaining (and prefer to, so we can make quick changes and add modules as needed).

I can't imagine it being much more than a single page with different sections for sub-events, schedule, speakers/hosts, etc. like you'll see on https://redefinesummit.com/ or the summit site you guys did last year https://summit.blockstack.org/.

With a mockup in figma, I can build it out and manage it alongside our others, but your help in making it special would be greatly appreciated. I think it makes sense to spend 80% of the effort on what the single panel it loads on would look like and design a nice custom hero for it - animation of some kind would be sick to bring it to life. The rest of the site I can follow sensically and that will give us the flexibility to move things around and play with different content at different times. Inevitably this site will change a lot between now and then and be updated often, so we don't need to spend too much time on specific sections, just a good color/card theme I can follow probably.

Consider this a placeholder for this week, putting it on your radar, but by next week we should have a clearer picture of the site goals and content mix.

🙏

**Comment by tvr132b** [comment]
@cuevasm just so that i understand correctly you need support with designing figma files and or converting figma mockups to html css for the launch event page with some css or js animation  right ?

**Comment by cuevasm** [comment]
I don't need any help building the site - I just want design direction/input on it. Typically that would be handed off to me in Figma with some elements I can pull and use and basically reproduce the mockup in our website builder. 

For this site, I think an animated element of some kind would be fantastic, either in GIF form like you see on the site I used as an example, or just something small that wiggles - I don't have something specific in mind at this point.

**Comment by tvr132b** [comment]
gotcha. thanks.

**Comment by cuevasm** [comment]
I'm going to basically cancel this request. With the time we have, we probably don't have a lot of room for anything crazy special. I am going to make the site as we need it following the guidelines and then ask for a fancy hero image from @jasperjansz or @jeffdomke when I have a handle on the content later this week.
