### ISSUE TITLE
Create product page for Connect

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#1170]
We should have a page that contains the following designed around Connect 2.0:

- Primary CTA to install extension
- Secondary CTA for developers to learning how to integrate
- Tertiary CTA for open source contributions
- Distinct user-targeted and developer-targeted highlights of benefits and functionality
- Screenshots of key features
- Link(s) to showcase apps
- FAQs related to Connect (and related updates to https://www.blockstack.org/questions/how-does-connect-work)

**Comment by beridzee** [comment]
Hello,
Trying to Mine STX ,but it too hard to do it by instructions. 
So it will be cool if you make Video instruction about : STX mining and other stuff to do. (For Windows , iOS , Linux)

Thank you 

Sincerely, 
George B.

**Comment by markmhx** [comment]
@beridzee Mind creating an issue in the documentation repository with details about your idea? https://github.com/blockstack/docs/issues/new

I imagine we could feature a video there especially since that's where we currently instruct miners on how to get started.
