### ISSUE TITLE
Remove BTC faucet for Xenon

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/blockstack.org#1171]
On this page https://www.blockstack.org/testnet/faucet: remove BTC faucet option. Instead, point people to a public tBTC faucet, such as https://testnet-faucet.mempool.co/

**Comment by markmhx** [comment]
Done ✅ 

![image](https://user-images.githubusercontent.com/28991/100890284-59ca7780-34b8-11eb-8b3b-c51a36e9899d.png)
