### ISSUE TITLE
Update installation page for Stacks Wallet for Web

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#1173]
We should update https://www.blockstack.org/install with:

- [x] New URL (and permanent redirect) at `/wallet/install`
- [x] New "Stacks Wallet" branding in lieu of "Blockstack extension"
- [ ] If user visits in supported browser, instructions are displayed directly on page for installing from source, with link to download ZIP for appropriate browser based on user agent detection
- [ ] If user visits in non-supported browser, option provided to continue to hosted authenticator but with recommendation to use Firefox and Chrome instead with install
- [ ] Link to learn more at `/wallet`
- [ ] Removal of site navigation and footer to keep users focused upon hand off from the `stacks.js/connect` intro modal
- [ ] Clear warning that software is "beta", hasn't yet been audited, and should we used with care when entering any Secret Keys with STX. Link should be provided to download the desktop Stacks Wallet as a recommendation for STX holdings.

cc @jasperjansz

**Comment by hstove** [comment]
>  If user visits in non-supported browser, option provided to continue to hosted authenticator but with recommendation to use Firefox and Chrome instead with install

The way the popup auth is setup, this is not possible. Or, at least, it will only work with the redirect method.

It also sounds like this page will require a bunch of custom javascript?

**Comment by markmhx** [comment]
> The way the popup auth is setup, this is not possible

It's not possible to detect the user is visiting from a browser other Firefox or Chromium and display different options for manual selection if so?

> It also sounds like this page will require a bunch of custom javascript?

Ideally we'd show the user just what they need to see based on their user agent. But as discussed sync elsewhere, we can go live with a version that shows options for all browser types and have the user select from them, if this requires too much JS for launch.
