### ISSUE TITLE
Blockstack logo on 404 page (Hiro)

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack.org#1174]
![image](https://user-images.githubusercontent.com/6131188/105250886-2be1e500-5b83-11eb-9cb6-5afeccdc49dd.png)

**Comment by markmhx** [comment]
Fixed 🔧 

![image](https://user-images.githubusercontent.com/28991/105344340-17353980-5be3-11eb-9084-a8baca2b9612.png)
