### ISSUE TITLE
recommendation: sticky social share sidebar

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#126]
I am wanting to make a recommendation to add a sticky social share sidebar to the blockstack doc pages 

@shea256 and i discussed this last week but concluded that it would not work as we did not have any stats.

I am re-recommending the addition of a "sticky social share sidebar" based on the following;
1. Medium.com, a popular and effective blog, has added one to their app as of 2-3 days ago (see image attachement below)
2. My design intuition based upon a decade+ design and marketing failures and successes
3. A successful implementation of a sticky social share sidebar that took a blog from 3,000 page views/mo. to 75,000 page views/mo

I could spend time digging up more evidence and facts as well but feel this is sufficient for the time being. Thoughts?

<img width="527" alt="screenshot 2016-10-22 18 43 48" src="https://cloud.githubusercontent.com/assets/1711854/19623081/b7fa9cec-9889-11e6-8dcd-5e2efaa124cb.png">

**Comment by estermer** [comment]
Here is a nice article speaking on the pro's and cons of a sticky nav bar.

http://www.awwwards.com/fixed-navigation-bars-pros-and-cons.html

though it is a nav bar, i think the pros and cons are the same for a stick social share sidebar.

Hopefully this helps in making a decision

**Comment by guylepage3** [comment]
Thanks for the link @estermer. Great find and great article. :)

My thoughts are that the sticky sidebar is quite a bit different than a sticky navbar as the sticky navbar faces quite a few unique challenges and hurdles that a sticky sidebar does not. I feel, that if well executed, meaning the sidebar is small, non-invasive and well positioned, the sticky sidebar becomes a tool for the user and not an troublesome menace. It's closely related cousin, the sticky navbar, faces real challenges with positioning, overlap issues, color blending, etc. that the sticky sidebar should be able to avoid.

I am not a big fan of the sticky navbar as there are too many cons for my liking. As for the sticky sidebar, I have had success executing it on a blog in the past. And now that a behemoth of a platform such as Medium has integrated it, I feel that it's worth making an attempt at implementation.

**Comment by estermer** [comment]
Yeah I would agree. Include the fact that getting the word out there about blockstack is a key component which makes creating something that allows sharing to be more seamless so much more desirable.

**Comment by shea256** [comment]
We could try adding this to blockstack.org/blog.

I'd keep it out of the docs section and rest of the site, though. Doesn't seem to fit. Seems more of an article/post-sharing thing.

**Comment by guylepage3** [comment]
i personally feel and have witnessed this working well with articles/white papers in the past. i feel it's worth trying out. yes, there will be only a few shares but they will be by our key target demographic, "evangelists." if we can make it easier for them to share our documentation and papers, i feel it's valuable.

**Comment by muneeb-ali** [comment]
If we (a) limit the social channels to Twitter and FB and (b) have a clean design, then this can work. 

+1 to starting with the blog.

**Comment by pstan26** [comment]
@estermer to the rescue?

**Comment by estermer** [comment]
Awesome Yeah I will limit it to twitter and FB and the design will be pretty clean. I think i will just play around with the colors of the logos, whether black, pink or purple and leave some screen shots in here to get opinions

**Comment by guylepage3** [comment]
@estermer Feel free to use the sketch file we've got going on..
**UI-kit** - https://github.com/blockstack/designs/blob/master/uikit/bsk-uikit.sketch
**blockstack.org** - https://github.com/blockstack/designs/blob/master/blockstack.org/blockstackorg.sketch

Ping me if you need anything or have a question. I'll be happy to help. 😄

**Comment by vsund** [comment]
https://github.com/heiseonline/shariff might be interesting. They have a quite big collection of sharing links :)

**Comment by estermer** [comment]
<img width="1440" alt="screen shot 2017-04-01 at 10 25 27 am" src="https://cloud.githubusercontent.com/assets/17515551/24579823/199e3c82-16cb-11e7-99b4-d991f98df180.png">

<img width="762" alt="screen shot 2017-04-01 at 10 25 55 am" src="https://cloud.githubusercontent.com/assets/17515551/24579827/21a6766a-16cb-11e7-91fa-9dba1694acb5.png">

<img width="422" alt="screen shot 2017-04-01 at 10 26 25 am" src="https://cloud.githubusercontent.com/assets/17515551/24579835/412aaa74-16cb-11e7-8d14-bd9591afaf13.png">

**Comment by estermer** [comment]
here are the sticky sharing at different sizes.

creating a PR for this for review

**Comment by vsund** [comment]
> If we (a) limit the social channels to Twitter and FB and (b) have a clean design, then this can work.

I'd like to propose Hackernews as additional sharer to Facebook and Twitter. Great target group and when you get on the frontpage you'll get much traffic :D

**Comment by larrysalibra** [comment]
@vsund 
> I'd like to propose Hackernews as additional sharer to Facebook and Twitter. Great target group and when you get on the frontpage you'll get much traffic :D Also, great discussions there.
+1

**Comment by guylepage3** [comment]
+1

@estermer would you like to take a crack at adding this as well?

**Comment by estermer** [comment]
@guylepage3 @vsund @larrysalibra I can give that a go. Might take a little hacking since that button isn't standard in the react-share module I used for the other buttons. But I can see how to incorporate it.

**Comment by guylepage3** [comment]
Pinning pr https://github.com/blockstack/blockstack.org/pull/260

**Comment by guylepage3** [comment]
merged into `design`. closing issue.
