### ISSUE TITLE
democracy earth logo update in landing site

### ISSUE THREAD

**Issue by santisiri** [blockstack/blockstack.org#142]
Hi folks, we won't be adapting DemocracyOS to blockchain usage, but we are going to make a release of a new app doing this. It would be great if you can update our logo in the landing mentioning 'Democracy Earth' instead. I already sent @guylepage3 a copy of it. 

Thanks!

**Comment by guylepage3** [comment]
thanks @santisiri,

Here's the new logo.

![democracy-earth-logos](https://cloud.githubusercontent.com/assets/1711854/19975307/d8e12868-a1c1-11e6-8f54-a534ec3b26ee.png)

**Comment by santisiri** [comment]
hi @guylepage3, here's a much better version you can use i think. we're going to use this one from now onwards: 

![democracy-earth](https://cloud.githubusercontent.com/assets/2153166/19990330/51f7e8d6-a203-11e6-859d-cb831b5fae2b.png)

**Comment by guylepage3** [comment]
Ahh.. is there an SVG version @santisiri

**Comment by guylepage3** [comment]
depricated.
