### ISSUE TITLE
propose to change of "posts" wording in header

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#145]
Proposing changing "posts" to "engineering" in header.

**Comment by larrysalibra** [comment]
papers?

**Comment by guylepage3** [comment]
In the latest header from the `posts` branch, posts is a header link.

**Comment by guylepage3** [comment]
<img width="1267" alt="screenshot 2016-11-08 13 23 59" src="https://cloud.githubusercontent.com/assets/1711854/20111520/a506f68c-a5b6-11e6-8d64-90379ec4d680.png">

**Comment by guylepage3** [comment]
New header.. @larrysalibra @shea256 @muneeb-ali @jcnelson 

<img width="1273" alt="screenshot 2016-11-10 17 32 45" src="https://cloud.githubusercontent.com/assets/1711854/20197128/d2a3ae76-a76b-11e6-8eab-fded1ae2e38d.png">

**Comment by guylepage3** [comment]
closing this issue.. moved to.. https://github.com/blockstack/blockstack.org/issues/144
