### ISSUE TITLE
after "pip install blockstack", blockstack (0.14.0.4) and blockstack-client (0.14.0.5) are co-exist

### ISSUE THREAD

**Issue by tthsn** [blockstack/blockstack.org#159]
it seems the same package has multiple names. may bringing versioning problem.

for example, by browsing 'https://pypi.python.org/pypi?%3Aaction=search&term=blockstack&submit=search', you will find blockstack and blockstack-client, blockstack-server and blockstack-core, actually, they are the same package.

another example, if you installing blockstack then blockstack-core by the command 'pip install blockstack; pip install blockstack-core', you will find 2 "client" package (blockstack (0.14.0.4)
and blockstack-client (0.14.0.5)).   actually, 0.14.0.4 is overwritten by 0.14.0.5, but this is not clear.

this is a software configuration/engineering issue. but we don't have qa or related projects. so fire a new issue on documentation.

**Comment by guylepage3** [comment]
@tthsn this is a https://github.com/blockstack/blockstack-core issue. if you're still having issues, please create a new issue in that repository. 😄
