### ISSUE TITLE
mac instructions don't work on current macOS

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack.org#165]
The instructions on the website for install blockstack-cli conflict with the instructions in the repo readme.  They also[ don't work on the current version of macOS](https://github.com/blockstack/blockstack-cli/issues/167) (OS X was renamed to macOS) 10.12 (aka Sierra).

It also seems like we shouldn't be instructing users to install blockstack outside of a virtualenv using sudo in a way that can potentially break other python software on their computers.

Can we switch to virtualenv instructions on the website?

**Comment by guylepage3** [comment]
Maybe we should instruct the user to try installing first without `sudo` and then offer `sudo` as a second option?

**Comment by larrysalibra** [comment]
Another person had the same problem & virtualenv fixed it -> https://github.com/blockstack/blockstack-cli/issues/180#issuecomment-265193172

**Comment by guylepage3** [comment]
@larrysalibra can i close this issue out?
