### ISSUE TITLE
proposal: testimonials on blockstack.org

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#170]
I'd like to propose adding some testimonials or other forms of social proofs to blockstack.org. Whether that be engineers, corps such as Microsoft, and/or projects. I feel this would go a long way to adding to our growth.

This is a small community where we need to concentrate on capturing the talent in this market to be building on blockstack. Doing something similar to what the folks at 21 did below seems wise.

<img width="1920" alt="screenshot 2016-12-25 18 06 23" src="https://cloud.githubusercontent.com/assets/1711854/21473200/1a1125d4-cacd-11e6-8bec-c02bb54724ac.png">

**Comment by guylepage3** [comment]
A reference for this comes from this article. http://www.designyourway.net/blog/design/use-social-proof-in-your-websites-and-boost-conversions/

**Comment by shea256** [comment]
Good idea. This would be a nice thing to add. Let's think about how to do it and where to put it. I like the idea of including tweets.
