### ISSUE TITLE
Blog post shows Page Not Found when loading

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack.org#173]
Blog posts show "Page Not Found" briefly while loading.
<img width="1263" alt="screen shot 2016-12-29 at 1 45 33 pm" src="https://cloud.githubusercontent.com/assets/597182/21537486/1e6778d8-cdcd-11e6-9711-c8da21fddba0.png">

See attached screen recording (in zip file):
[file-not-found.mov.zip](https://github.com/blockstack/blockstack.org/files/676652/file-not-found.mov.zip)

**Comment by shea256** [comment]
Thanks @larrysalibra, fixed!
