### ISSUE TITLE
Update the blockstack site snapshot for the metatags

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack.org#176]
https://blockstack.org/images/metatags/blockstack-site-snapshot.png

**Comment by guylepage3** [comment]
I'm going to update this right after we push the new hero section

**Comment by guylepage3** [comment]
![twitter-image](https://cloud.githubusercontent.com/assets/1711854/21697891/882145ca-d362-11e6-8697-b790c994dc3f.png)

**Comment by guylepage3** [comment]
Complete. closing issue

**Comment by guylepage3** [comment]
Issue is now resolved. See below..

<img width="551" alt="screenshot 2017-01-05 19 22 38" src="https://cloud.githubusercontent.com/assets/1711854/21702941/95ef8224-d37c-11e6-9e00-7a0b5de477f3.png">
