### ISSUE TITLE
reposition banner image from blockstack.org blog posts

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#180]
Reposition the main banner image from blockstack.org blog posts so that the imagery is more manageable on all devices, screen sizes and resolutions.

**Tasks**
- [ ] Reposition main imagery under headline
- [ ] Imagery size `width: 670px;` (content column should be `width: 700px;` for better readability. See issue https://github.com/blockstack/blockstack.org/issues/181).

Visual reference:

<img width="1199" alt="screenshot 2017-01-04 11 03 55" src="https://cloud.githubusercontent.com/assets/1711854/21648868/9382b8d6-d26d-11e6-86ef-c04bd2030acd.png">

**Comment by guylepage3** [comment]
updating width measurement for today to be `width: 670px;` from recommended width of `width: 700px;`.

**Comment by shea256** [comment]
OK we can try this.

**Comment by guylepage3** [comment]
Closing this out @shea256.
