### ISSUE TITLE
bug: resolve data-reactroot div height issue

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#198]
I am trying to assign a `height: 100%;` to `<div data-reactroot / >` in order to apply a full screen height container to the landing view on blockstack.org mobile and desktop.

I am assigning `height: 100%;` to the following and it is effectively executing the assigned style.
```
.site-wrapper-outer,body,html,#app{height:100%;}
```

But I am unable to target
```
<div data-reactroot="">
```

**Comment by guylepage3** [comment]
Found this for reference..
https://github.com/kadirahq/flow-router/issues/342

**Comment by guylepage3** [comment]
Issue resolved by targeting `#app div`

**Comment by guylepage3** [comment]
@shea256 `#app div` unfortunately targets "every" div in the `#app` container causing huge breakages on other pages.

Is there a way we can get rid of `<div data-reactroot="">`?

Or at least assign a unique property or classname to it?

**Comment by shea256** [comment]
The first one won't work as we don't have control over that div.

The second might be accomplished with this:
http://stackoverflow.com/questions/2094508/css-selector-for-first-direct-child-only

**Comment by shea256** [comment]
Actually take a look at this: http://stackoverflow.com/a/14490405/1530754

**Comment by guylepage3** [comment]
Ha. I totally did not think pseudo classes where able to target `<div>`'s due to incompatibility and lack of browser support. But I was wrong. https://developer.mozilla.org/en-US/docs/Web/CSS/:first-child

Will give it a go. Thanks. :)

**Comment by guylepage3** [comment]
Issue resolved. closing issue

**Comment by lotusms** [comment]
You can also target reactroot by attribute selector. It is more direct that using CSS Specificity via pseudoclasses. 

```
div[data-reactroot] {
    z-index: 1 !important;
}
```
