### ISSUE TITLE
bug: full screen on landing causes full screen on all views

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#201]
Back on issue **https://github.com/blockstack/blockstack.org/issues/198: bug: resolve data-reactroot div height issue**, we hacked our way around the `reactroot div` by assigning a pseudo class to the div.

As a result we now have full screen on ALL views which leaves the rest of the site with no content visible to the user.

<img width="541" alt="screenshot 2017-01-13 11 05 10" src="https://cloud.githubusercontent.com/assets/1711854/21936703/2da03ba0-d980-11e6-9b0c-bf9d81d6a653.png">

**Solutions**
A couple of solutions are to 
1) either remove the `reactroot <div>`
1) add a `className` to the tag

Both methods would allow us to add a new `className` like `site-wrapper-inner` to the landing view and then something like `site-wrapper-inner-common` to all over views.

**Comment by guylepage3** [comment]
Will take a look at the browser and how this item was resolved.

**Comment by guylepage3** [comment]
Turns out we were actually assigning a `className` to the `reactroot div` in the browser.

The components below were added to `App.js`

```
class MainScreen extends Component {
  static propTypes = {
    children: PropTypes.element.isRequired
  }

  render() {
    return (
      <div className="body-main">
        <Sidebar />
        <div className="content-section" style={{ height: '100%' }}>
          <Navbar />
          {this.props.children}
        </div>
      </div>
    )
  }
}

class WelcomeScreen extends Component {
  render() {
    return (
      <div className="body-landing" style={{ backgroundColor: '#1b1e21' }}>
        {this.props.children}
      </div>
    )
  }
}
```

**Comment by shea256** [comment]
Cool @guylepage3 did we figure this one out?

**Comment by guylepage3** [comment]
@shea256 I'm receiving an error when trying to build this out from the browser.

**Comment by guylepage3** [comment]
Issue resolved by adding the following component and then targeting the class name.

```
class App extends Component {

  constructor(props) {
    super(props)
    this.state = {}
  }

  renderChildren() {
    return cloneElement(this.props.children, {
      params: this.props.params,
      query: this.props.query
    })
  }

  render() {
    let wrapperClass = "app-common"
    if (location.pathname === '/') {
      wrapperClass = "app-landing"
    }

    return (
      <div className={wrapperClass}>
        {this.renderChildren()}
      </div>
    )
  }

}
```
