### ISSUE TITLE
hamburger collapse menu dropdown

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#209]
Add and style all elements of a collapse hamburger menu that becomes visible when one of the navigation menu items drops off due to responsive design

**Comment by estermer** [comment]
Hey so i finished this. I made the dropdown be available at 450px.

let me know if you like the left aligned nav-items

<img width="522" alt="screen shot 2017-03-20 at 8 02 21 pm" src="https://cloud.githubusercontent.com/assets/17515551/24127225/756e35d8-0da9-11e7-9e4b-95e63d3f4fbe.png">

**Comment by guylepage3** [comment]
@estermer. Referencing your comment from your PR:
https://github.com/blockstack/blockstack.org/pull/248#issue-215592484

>At 450px screen widths the normal nav bar is hidden with a hamburger dropdown nav bar.

The `450px` media query is not a standard breakage size for [Bootstrap](http://v4-alpha.getbootstrap.com/layout/overview/#responsive-breakpoints). Is there a reason you are deviating from the framework?

**Comment by estermer** [comment]
I saw there was a requirement in the ticket to transform the nav when the last nav button dropped. Plus I have just a little buffer room for wider phones. I added the width to the ticket to see what you thought too so if you think it should be different that is fine.

**Comment by guylepage3** [comment]
Yeah. I think we should keep with the framework's `@media` query settings just so that others will know what's going on. We will be updating `blockstack-bootstrap` soon. Possibly in the next sprint. Making those higher level decisions at that time is a much better idea. We can bake them into the SCSS.

@estermer would you like to take a stab at adjusting any pr's that are applying this `450px` media query?

**Comment by estermer** [comment]
@guylepage3 The only PR is #248. This has been adjusted.

**Comment by guylepage3** [comment]
@estermer, i am moving this issue to v4.0.0. still seems to be a problem with the hamburger menu.

**Comment by estermer** [comment]
I can take a look at this and see if I can get it ironed out.

**Comment by guylepage3** [comment]
closing issue
