### ISSUE TITLE
add social proofs to landing view

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#216]
Add 3-5 logos of projects and/or companies working on Blockstack to the landing view's footer section

- [ ] Microsoft
- [ ] OpenBazaar
- [ ] Yours
- [ ] DemocracyOS
- [ ] Tierion

**Comment by guylepage3** [comment]
@shea256 can you provide me with a list of 5 logos you'd like to see on blocsktack.org landing view, in order of importance. Thanks.

**Comment by shea256** [comment]
Microsoft, OpenBazaar, Yours, DemocracyOS and Tierion

**Comment by guylepage3** [comment]
depricated
