### ISSUE TITLE
design social proofs for landing view

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#219]
Effective communications mean that there is a single goal for a section or view. Having said that, there are some effective ways to add large amounts of content while keeping clear focus on the main goal. ie. http://slack.com. They have managed to draw the audience's eye to the main CTA but still allow for simple navigation without being invassive. See slack.com examples below.

With blockstack.org, we are trying to provide 3 separate goals. This is next to impossible to execute. and if one is not executing on 2 out of the 3 then those two are not being viewed and are therefore irrelevant as the audience will skip over them.

The main goal for the landing view is to capture the audience / execute the CTA. Once they are captured they will navigate the site until their heart's content. If not, bounce...

**Comment by guylepage3** [comment]
<img width="1292" alt="screenshot 2017-01-18 12 14 59" src="https://cloud.githubusercontent.com/assets/1711854/22075118/bdec3244-dd78-11e6-8172-ddb928d90057.png">
<img width="1250" alt="screenshot 2017-01-18 12 15 16" src="https://cloud.githubusercontent.com/assets/1711854/22075117/bdeb34a2-dd78-11e6-961d-dcde7650089b.png">

**Comment by guylepage3** [comment]
As one can see from the slack.com landing view they are not offering imagery to the audience as an execution goal or item. The graphics to the right of the CTA are a bit too focal for my taste but still we know basic pshycology that north americans/europeans will flow down a page from top left to bottom right so they will hit that CTA.

**Comment by guylepage3** [comment]
Having said that, the footer contains small type that is strictly there for quick navigation. Which is something we will be executing on our footer as well. No imagery, no "special" sections or any non-traditional goals. audiences have been used to footer content since the initial days of the web.

**Comment by guylepage3** [comment]
As one can see in the following design for blockstack.org we are not able to execute 2 out of the 3 goals for the landing view, increasing the chances of a user to bounce.

![blockstack org-01-landing-view 2x](https://cloud.githubusercontent.com/assets/1711854/22075301/83eaae1c-dd79-11e6-93e0-0da46dab11f1.png)

**Comment by guylepage3** [comment]
![blockstack org-01-landing-view2 2x](https://cloud.githubusercontent.com/assets/1711854/22075351/b3c75a90-dd79-11e6-82b6-469dbcdef26e.png)

**Comment by guylepage3** [comment]
One thing @shea256 and i discussed was adding in a footer similar to slack.com to execute social proofs. The design above does this but not very effectively in my opinion and would prefer to move this below the fold if they are that important. While adding a super menu footer to the landing view. Thoughts?

**Comment by shea256** [comment]
Yeah I like moving in the direction of the Slack landing page.

What do you think of making the hero-footer division higher up like on https://openbazaar.org/ so that the landing page is non-scrolling even on medium-sized screens and up?

**Comment by guylepage3** [comment]
So to recap.. I believe scrolling is inevitable with the addition of the mega menu footer. Let's go with a hero section `height: 700px;`.

**Comment by guylepage3** [comment]
Latest landing view design

![blockstack org-01-landing-view 2x](https://cloud.githubusercontent.com/assets/1711854/22088387/a9cf9c40-ddb1-11e6-8062-3e13ab84e351.png)

**Comment by shea256** [comment]
doesn't look as sexy 😩

**Comment by guylepage3** [comment]
![blockstack org-01-landing-view 2x](https://cloud.githubusercontent.com/assets/1711854/22088534/bdf4f020-ddb2-11e6-86d4-c24c993fa755.png)

**Comment by guylepage3** [comment]
![blockstack org-01-landing-view 2x](https://cloud.githubusercontent.com/assets/1711854/22088584/22f42cac-ddb3-11e6-88fe-f04b1955b161.png)

**Comment by guylepage3** [comment]
complete
