### ISSUE TITLE
Slack link to archives from main page

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack.org#220]
Lounge is now community, so we should update the link to http://blockstack.slackarchive.io/community/

(Right now it says Channel lounge not archived)

**Comment by shea256** [comment]
Fixed.

There are now 4 stats on the home page. Each of them link to the explorer, the slack signup, the forum, and the meetup groups.

**Comment by muneeb-ali** [comment]
Awesome! 

Great to see stats for the forum as well. 

Suggestion: the forum link currently defaults to "weekly stats", maybe we should link to monthly instead i.e., https://forum.blockstack.org/users?period=monthly

That way people will see more activity and it's good to get a snapshot/overview of monthly active users as well.

**Comment by shea256** [comment]
Good idea, updated!
