### ISSUE TITLE
Maybe we should reduce links to the Github repos

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack.org#221]
The "code" dropdown currently lists a bunch of Github repos: 

The CLI repo is going away and I don't think the virtualchain repo is relevant for 99% of developers. 

We'll basically have three main repos: 

1) blockstack/blockstack -- overview, all docs, specs, events etc (no code) 
2) blockstack/blockstack-core -- the reference implementation of Blockstack 
3) blockstack/blockstack-browser -- the browser and upgrade/portal 

Maybe we can get rid of the links to the other repos? 

blockstack/blockstack repo will have links to other repos and an overview of where all the rest of the content is.

**Comment by shea256** [comment]
Yeah good thinking.

How about we just have one link and link to https://github.com/blockstack? Then there are 6 featured repos and the first link is github.com/blockstack/blockstack which has additional information for people to read through.

**Comment by shea256** [comment]
Guy mentioned something like this before as well and now with the new site structure (especially with the soon-to-come intro page) I think it's the best way to go.

**Comment by muneeb-ali** [comment]
1 link works great as well. Saves people a click to expand the drop down and they can go straight to Github.

**Comment by shea256** [comment]
Done, closing.
