### ISSUE TITLE
bug: navbar & contents shrink when nav-item docs is clicked on mobile

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#222]
Navbar & contents shrink when nav-item docs is clicked on mobile.

**Comment by guylepage3** [comment]
Determined that what is causing the issue is something in this commit

https://github.com/blockstack/blockstack.org/commit/093e834f8eafe4decadfeb2799cd89f4825a928d

**Comment by guylepage3** [comment]
There are quite a few things happening with this page. The page needs to be rebuilt/designed to match the rest of the brand. When it is rebuilt, this issue should be addressed at that time.

Moving this issue to Milestone https://github.com/blockstack/blockstack.org/issues/129

**Comment by estermer** [comment]
I actually built in a quick fix if you wanna take a look at my PR. It was a simple word-break that I added to the container section to prevent the overflow.

**Comment by guylepage3** [comment]
merged.. https://github.com/blockstack/blockstack.org/pull/254
thanks @estermer. closing issue
