### ISSUE TITLE
Intro page link to Blockstack Core

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack.org#227]
The "Blockstack Core" link on the intro should point to the blockstack-core repo after the merging of the CLI and Core.

**Comment by estermer** [comment]
I can take this one as well, should be pretty easy, unless it is already done since it was once in progress.

**Comment by estermer** [comment]
I submitted a PR for this since it was a quick change of the href.

**Comment by estermer** [comment]
this can be closed, @larrysalibra merged it into master already.
