### ISSUE TITLE
Resolve mobile view of blog post

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#231]
![img_1525](https://cloud.githubusercontent.com/assets/1711854/23175832/9ba4f5ba-f82e-11e6-922d-8018e41d020f.PNG)
![img_1526](https://cloud.githubusercontent.com/assets/1711854/23175833/9bb5695e-f82e-11e6-8e64-e783ba211fe2.PNG)

**Comment by estermer** [comment]
I noticed by looking at this, this is not just a blogpost issue. This is only occurring on one page. The "Announcing Blockstack Explorer" is the only post it is happening on. Also it is not isolated to just the blog component, but to the entire page. Looking at the header and footers, there is a difference in sizing of these as well under the mobile view... again only on that one blog post's page.

**Comment by estermer** [comment]
Ok after doing some searching and testing, I noticed that 3 of the 4 images did not have the class of img-fluid causing their size to remain constant when going into mobile view. Adding the img-fluid class to the using dev tools solved this problem. I will work to figure out why they are not getting added into the React component and see if i can get a PR for this soon.

**Comment by larrysalibra** [comment]
@estermer Awesome! Thank you!

**Comment by estermer** [comment]
I just looked at the source code from the rss api where the markup is sourced from and the class is missing from the image tags there. I don't think i have access to rewrite that code, so if you want to @larrysalibra go there and add to the images the class="img-fluid" to the <image/> tags for that post, this should fix the problem.

**Comment by estermer** [comment]
Yeah so, none of the other blog posts have any images in the rest of the post except the initial image which has code in react to parse it out and pass it to an Image component that has the right className. if you notice from the image above the blockstack explorer image is the right size but the following images are not. I can do one of two things. I can set up some code that grabs the rest of the images for this one instance incase this happens again... OR I can just ask @larrysalibra and whoever writes future blog posts to add the class img-fluid to all images after the first. It is up to you guys. let me know.

**Comment by estermer** [comment]
@guylepage3 @larrysalibra this is resolved. I was able to add some functionality to future posts to have more than just a main image in the content and still have the img-fluid class.

**Comment by guylepage3** [comment]
awesome @estermer. @shea256 will take a look at your pull request.

**Comment by guylepage3** [comment]
closing issue.
