### ISSUE TITLE
Add feed url to metadata

### ISSUE THREAD

**Issue by vsund** [blockstack/blockstack.org#232]
Add [1] (or [2]?) as feed url to the metadata at `/blog` (and at `/` too?) so that feedreader recognize it.

For example:
`<link rel="alternate" type="application/rss+xml" title="Blockstack blog" href="https://blockstack.ghost.io/rss/" />`

[1] https://blockstack.ghost.io/rss/
[2] https://blockstack-site-api.herokuapp.com/v1/blog-rss

**Comment by guylepage3** [comment]
@vsund want to do a PR for this?

**Comment by vsund** [comment]
I thought about doing this as pull request directly, but I don't know which url is the canonical feed url.
And I think you know how to do this the best from a SEO perspective (I'm unsure how correct the `rel="alternate"` attribute is).

But you can edit this in my pr afterwards. Give me a moment :)

**Comment by guylepage3** [comment]
yep. that sounds great. thanks. 👍

**Comment by vsund** [comment]
Or lets better talk here before that^^
(Started working on this and couldn't answer the following questions)

Open questions:
* https://blockstack.ghost.io/rss/ or https://blockstack-site-api.herokuapp.com/v1/blog-rss?
* Feed at `/blog` or on the home page too?
* `rel="alternate"` or not?

**Comment by guylepage3** [comment]
1. i think https://blog.blockstack.org/rss/
1. at home page as well
1. `rel="alternate"`
1. yes `metatags.html`

**Comment by vsund** [comment]
@guylepage3 I just pushed and requested https://github.com/blockstack/blockstack.org/pull/233.

I didn't manage it to let gulp build the website, so this isn't tested as it should be (mainly hoping that this adds the tag to both, the home page and the blog).

**Comment by guylepage3** [comment]
no worries @vsund either @shea256 or I will take a look. thanks and will merge soon. 😄
