### ISSUE TITLE
Change "Install the Software" button copy to "Install Blockstack"

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack.org#235]
![Uploading Screen Shot 2017-02-28 at 1.01.50 PM.png…]()

> On the blockstack.org website, we should release macOS and Linux binaries simply saying "Download Blockstack". Right now the installer installs only Core & CLI but in the future, it can install Portal as well.

**Comment by guylepage3** [comment]
complete. @shea256 we are 3 pr's behind on blockstack.org

https://github.com/blockstack/blockstack.org/pull/224
