### ISSUE TITLE
redesign install view

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#239]
Redesign the install view - https://blockstack.org/install

Referencing
- [#236: Create page for installing packages from "Install Blockstack" button on home screen](https://github.com/blockstack/blockstack.org/issues/236)

**Comment by guylepage3** [comment]
@arisgk, great to have you hear. let me know if you have any questions. looking forward to working with you on this. :)

**Comment by arisgk** [comment]
@guylepage3 Thank you, it will be great to contribute. 

You can check out some first iterations in this InVision prototype https://projects.invisionapp.com/share/JEC5GNXCD#/screens/238823570_Blockstack-org-08-Install-02.

There are versions for both the final version and the MVP.

Let me know if you prefer to attack screenshots here instead of this InVision link and of course, any feedback/comments are welcome.

**Comment by guylepage3** [comment]
This is looking great @arisgk. 😄 

**Couple of quick suggestions** 
1. Can we see secondary layout? Maybe try one separating each download with cards?
<img width="530" alt="screenshot 2017-06-14 11 27 57" src="https://user-images.githubusercontent.com/1711854/27140913-beb55ddc-50f4-11e7-880b-59875cf4769f.png">
2. We need to indicate to the user that some of these downloads are not available right now. We could try and gray out the one's that are not yet available
3. Maybe we can also make the icons a little smaller? That may put more emphasis on the download buttons
4. How will this look on mobile?

Some examples of other download pages for inspiration:
- Adobe – http://www.adobe.com/creativecloud/catalog/desktop.html
- IPFS – https://ipfs.io/docs/install/
- Slack – https://slack.com/downloads/osx
- G Suite – https://gsuite.google.com/
- Airbnb – https://www.airbnb.com/mobile

Love the initial start here. 👍

**Comment by arisgk** [comment]
Thanks for your feedback and the inspiration links @guylepage3, they are really helpful.

In reply to your suggestions:

1. I will send some alternative designs soon so that we can choose the best one.

2. This InVision prototype link I sent has 4 screens/pages, two of which refer to the current (Developer alpha) version and some buttons are disabled. I used our current (blockstack.org install page) color convention for disabled buttons.

3. Sure, I will definitely try that.

4. I can work on the mobile version too, I thought it can be quicker to iterate on one or two concepts for desktop (based on these inspiration links you sent me) and then design the mobile version for our preferred one. I can, of course, design the mobile version for every concept if you think it will help us choose better. Let me know about your preference on this.

**Comment by guylepage3** [comment]
@arisgk, very cool. here's more feedback.

>I will send some alternative designs soon so that we can choose the best one.

awesome! looking forward to it :)

>This InVision prototype link I sent has 4 screens/pages

I am unable to view the other screens. We should for sure indicate to the user that macOS, Linux are coming soon both visually and written.

>I can work on the mobile version too, I thought it can be quicker to iterate on one or two concepts for desktop (based on these inspiration links you sent me) and then design the mobile version for our preferred one. I can, of course, design the mobile version for every concept if you think it will help us choose better. Let me know about your preference on this.

Let's see what we decide for desktop before designing out the mobile views then.

**Comment by arisgk** [comment]
@guylepage3 I uploaded some new designs in our shared InVision blockstack.org prototype - https://projects.invisionapp.com/d/main#/projects/prototypes/9224309.

Let me know if you would like to choose one of them in order to iterate on it and polish it or if you have any fresh ideas I could try :)

**Comment by guylepage3** [comment]
Awesome work @arisgk! 😄 

Really liking the second install view! 

Couple of things..
1. Lead copy – Let's change that to read, "Own your own data. Download the Developer Beta to access the new decentralized internet"
2. Coming soon copy – Let's change that to read, "Coming soon for macOS, Linux and Windows"
3. Core Server + CLI card – let's stretch that card out and center the content.

Great work here @arisgk. Super happy with this.

**Comment by arisgk** [comment]
@guylepage3 Thank you, I am glad you liked it! I just applied these updates, let me know if you think we can improve it in any other way.

**Comment by guylepage3** [comment]
This is awesome @arisgk!

How do you feel about pulling from the `design` branch and build this out? We use bootstrap so if you adhere to the framework there should be no issues.

How does that sound?

**Comment by arisgk** [comment]
@guylepage3 Sure, it will be great to implement it! I will let you know if I have any questions.

**Comment by guylepage3** [comment]
Awesome @arisgk. great work on this! 😄

**Comment by arisgk** [comment]
@guylepage3 Here are some prototypes for the mobile version https://projects.invisionapp.com/d/main#/projects/prototypes/10049817. Let me know how you feel about them or if you have any other ideas :)

**Comment by guylepage3** [comment]
awesome @arisgk! 😄 taking a look now.

**Comment by guylepage3** [comment]
@arisgk loving these layouts.. let's go with **"Blockstack.org-Ios-40-Install-View@3x"**

My only feedback for this layout is that, I feel as though we can hide the image of the browser for the mobile view.

I need to merge in eric's install commits and then let's have you build this out. Great work! 😄

**Comment by arisgk** [comment]
Sure, good idea! I will upload an updated version soon and let you know.

**Comment by guylepage3** [comment]
@arisgk feel free to pull from `design` to start your build. @estermer's pull request has been merged.

**Comment by arisgk** [comment]
@guylepage3 I uploaded versions 43, 44, 45 in our InVision mobile prototype. In all of them, the browser screenshot is hidden and version 45 does not have `100vh` height. Feel free to check them out and let me know if you prefer any of them. 

Meanwhile, I will pull from `design` and start working on the implementation.

**Comment by guylepage3** [comment]
@arisgk checking them out now..

**Comment by guylepage3** [comment]
very cool @arisgk. let's go with design 44 from the invision link.

@shea256, what do you think?
https://invis.io/CQA0ZA06R#/240617582_Blockstack-org-Ios-44-Install-View-3x

**Comment by guylepage3** [comment]
hey @arisgk, some user feedback will be changing your install page design.

We are going to be wanting to go with a light background as well as the content itself will be changing.

Here's the latest visual for the browser onboarding screens. Let's revise the layout to be more like this ui. https://github.com/blockstack/blockstack-browser/issues/514#issuecomment-311142088

Here's the raw file for you to grab elements from if need be.
https://github.com/blockstack/designs/blob/master/browser/compositions/onboarding.sketch

**Comment by arisgk** [comment]
@guylepage3 Sure, we can iterate on it. I will prepare some light background designs, can you guide me with the content?

**Comment by guylepage3** [comment]
@arisgk Awesome sir! For sure. Let's start iterating by using the chosen designs with the chosen content for now. Waiting on the team to gather the new content. Hoping to have that tomorrow some time.

**Comment by arisgk** [comment]
@guylepage3 I prepared some alternative designs (designs 46-49 in our InVision desktop prototype - https://projects.invisionapp.com/d/main#/projects/prototypes/9224309). I can work on other concepts too as soon as I know our updated content and layout preferences.

**Comment by guylepage3** [comment]
This is awesome @arisgk! 😄 Love design 48! 

@shea256 check it out. :) https://invis.io/GQ9WF1DT4
