### ISSUE TITLE
Typo in intro page

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack.org#240]
Reported by @thibauld 

https://twitter.com/thibauld/status/840049196325601280

**Comment by guylepage3** [comment]
Pinning... https://github.com/blockstack/blockstack.org/pull/241

**Comment by brettdewoody** [comment]
@guylepage3 This can be closed, the typo has been fixed - https://blockstack.org/intro

**Comment by guylepage3** [comment]
@brettdewoody yes. good catch. this was from March.
