### ISSUE TITLE
Security and Privacy Page/Disclaimer

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack.org#243]
Just realized as I was commenting on the wallet icon in another GH task, that we will likely need to build a **security and privacy page** for users and developers detailing what Blockstack will never do or have access to. Also, gives us a nice opportunity to talk about how the blockstack network works.

Here's an example from my old company that we worked hard on crafting: https://www.earnest.com/privacy

We can obv do a more pared down version, but I think it may be necessary. Happy to push this forward. Thoughts?

@muneeb-ali @shea256 @guylepage3

**Comment by guylepage3** [comment]
Great idea @pstan26.. I feel this could add quite a bit of brand loyalty to Blockstack.
