### ISSUE TITLE
New FAQ Page

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack.org#244]
We've started making a list of FAQs [here](https://github.com/blockstack/blockstack/blob/master/FAQs.md). We need to add this page to the website. The website should be able to read the .md file and display it.

**Comment by estermer** [comment]
in progress

**Comment by estermer** [comment]
I have create a pull request for this ticket.

**Comment by guylepage3** [comment]
Awesome  @estermer! 💥 @shea256, @larrysalibra or myself will check it out in full in the am. 😄

**Comment by pstan26** [comment]
How did it go?

**Comment by guylepage3** [comment]
pinning pr https://github.com/blockstack/blockstack.org/pull/246

**Comment by guylepage3** [comment]
complete and closing.. great work @estermer
