### ISSUE TITLE
Blockstack.org landing view content

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack.org#249]
I’ve put together a gDoc **[here](https://docs.google.com/document/d/1PWIxhFPFuab6h6GLxeV2yFLtfQ-5O-6ffLz0GRILKFQ/edit)** with copy for the new home page. You'll see a logical progression of learning about blockstack, what can be built, and call-to-action as you scroll from top to bottom.  Anyone can comment in the doc, please feel free to do so.

Things to consider when we begin working on this:
- inserting animations and/or screenshots -- navigating portal & adding code to login to app (perhaps we could use screenshots and later replace them with a [scrollme](http://scrollme.nckprsn.com/) animation of video clips)

- background for longform #text to be readable (@shea256 said there may be an old format that had stripes cc @guylepage3 )

Let's get this in the next sprint starting April 3rd so there's no longer confusion about what we do.

**Comment by guylepage3** [comment]
@pstan26 can you actually place your thoughts here so we may have the community comment here?

**Comment by pstan26** [comment]
Sure thing:

#### Value Proposition + Short description of what Blockstack is, what you can do on it, and a short background
**Blockstack is a new decentralized internet where you own your data and your apps run locally without remote servers.**

The legacy internet has become centralized with a handful of companies controlling your digital identity and data.

The decentralized internet is powered by a technological breakthrough in consensus algorithms which allows you to take back your rights to ownership, privacy, and safety and to experience the internet as it was truly meant to be.

As a developer, you can build decentralized apps without having to set up any infrastructure or worry about hosting user data. The decentralized Blockstack network handles identity, auth, storage, and replaces DNS and TLS. 

Blockstack is an open source project with core developers located in New York City and Hong Kong.

#### "Download Blockstack" button accompanied by a short description and image/animation what you'll see in the portal. Show video of "aha" moment of. Back of napkin copy: "browse apps that run serverless on top of data you truly own..in some cases you don't even need an internet connection."

**Unlock the Decentralized Internet**

Downloading Blockstack will give you access to a decentralized internet within a regular browser. Claim your name, try out the first apps, lookup names like “werner.id”, connect storage of your user-owned data, and add universally accepted currency.

<<Download_Blockstack_Button>>

#### Create a vision of what can be built on the blockstack network.

As a developer, what you create is no longer limited by the walled gardens of third parties or the thought of having to maintain infrastructure and user security. Build apps using Blockstack.js and have them live forever on the decentralized internet.

**You can build apps like these on the Blockstack network**:
- Censorship resistant social network
- Cloud democracy with secure voting
- Encrypted peer-to-peer marketplace

<<Download_Blockstack_Button>>

#### Activate the developers with Hello Blockstack tutorial, accompanied by short video and description of "aha moment" of logging in w/ user-owned ID after 15 lines of code and describe that.

<<Embedded_15sec_Login_Video>>

Complete the step-by-step tutorial and see how easy it is to build an app with a decentralized identity system in a few lines of code and no servers. 

<<Hello_Blockstack_Tutorial_button>> (links to Github account with Hello Blockstack video)

Want to learn more about building apps on blockstack? Tutorials on building serverless apps with “get” and “put” functions are coming soon, but in the meantime check out our [Github repo](https://github.com/blockstack/blockstack-portal)

**Comment by guylepage3** [comment]
Pinning this issue to the original issue https://github.com/blockstack/blockstack.org/issues/259

**Comment by pstan26** [comment]
Gif for tutorial section: 
![hello blockstack to be gifd](https://cloud.githubusercontent.com/assets/5605552/25065921/45360bf6-21e6-11e7-8632-42c307481620.gif)

**Comment by pstan26** [comment]
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/5605552/25066011/4cad4e2e-21e8-11e7-919e-7fe6b1240222.gif)

**Comment by guylepage3** [comment]
@pstan26 this is amazing.. i thought you meant a gif for something else.

**Comment by guylepage3** [comment]
Can we get this in higher resolution though? Then i can play with the resolution in photoshop?

**Comment by shea256** [comment]
hell yeah!

**Comment by pstan26** [comment]
@guylepage3  I spent like 30 minutes trying to increase the resolution of the output gif with no major success, although it may be possible in photoshop which I don't have. Here is high res mp4 file https://www.dropbox.com/s/83h85arj90abqoi/Hello%20Blockstack%20To%20be%20Gifd28sec.mp4?dl=0

**Comment by guylepage3** [comment]
It has to be done at the application level

**Comment by guylepage3** [comment]
@shea256 @pstan26 @muneeb-ali @larrysalibra,

I'm closing out this issue as it seems as though content has been finalized here:
https://github.com/blockstack/blockstack.org/blob/be8c838f29f5d186f08720dea0f34390fb1d4993/app/js/pages/HomePage.js
