### ISSUE TITLE
Update link to join our community 

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack.org#256]
In our blog template, the link for "Join our Community" goes to:

http://blockstack.us14.list-manage1.com/subscribe?u=394a2b5cfee9c4b0f7525b009&id=0e5478ae86

this should be updated to:

https://blockstack.org/join

**Comment by pstan26** [comment]
In mailchimp or ghost? I can take care of this.

**Comment by pstan26** [comment]
cc @larrysalibra or @shea256

**Comment by vsund** [comment]
When we're already here, I think mention all the other community places at https://blockstack.org/join would be really helpful.

* Slack
* Forum
* Github
* Meetups
* Youtube?
* Twitter?
