### ISSUE TITLE
blog post image being cut on twitter desktop

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#258]
All Blockstack blog post header images are being cut to a 2048x2048px size when viewed as a twitter post on desktop only.

**Twitter iOS app**
![img_1806](https://cloud.githubusercontent.com/assets/1711854/24376580/60ef307e-130a-11e7-9c84-4f2ed0879232.PNG)

**Twitter desktop**
<img width="718" alt="screenshot 2017-03-27 16 28 48" src="https://cloud.githubusercontent.com/assets/1711854/24376622/853a4c52-130a-11e7-8925-b73e813a72c1.png">

**Image link from twitter on desktop**
https://pbs.twimg.com/card_img/846292406777495552/UbcheRv8?format=png&name=2048x2048_exp

**Comment by shea256** [comment]
On desktop, I'm not seeing this issue.

**Comment by pstan26** [comment]
Neither am I

**Comment by guylepage3** [comment]
Noticed that this is only happening to me when I'm logged in to one specific twitter accounts. Created an issue with Twitter.

**Comment by guylepage3** [comment]
resolved. it was a twitter issue
