### ISSUE TITLE
Blockstack.org landing page messaging

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#259]
[›› Blockstack.org landing view content](https://github.com/blockstack/blockstack.org/issues/249)

@guylepage3 commented on [Mon Oct 03 2016](https://github.com/blockstack/blockstack/issues/93)

@guylepage3 commented on [Thu Sep 08 2016](https://github.com/blockstack/community/issues/22)

I feel the image below of Apple’s new App eco system messaging is a great example of how we should be conducting the blockstack messaging on the home page

Thoughts?

![apple-apps-email-messaging](https://cloud.githubusercontent.com/assets/1711854/18349440/7b7f7b8c-759f-11e6-91fd-ce5b3a876c88.png)

---

@pstan26 commented on [Thu Mar 16 2017](https://github.com/blockstack/blockstack/issues/93#issuecomment-287087627)

This is lovely. Only concern is the education and CTA aspect of Blockstack itself being missing, as most apple devs will know a lot about the OS they are working on, whereas we may need to hammer that home more. 

Curious re: messaging, what you like most here?

As an aside, I think the placement of this information (whether it's a standalone page, or replaces the homepage, or its own site) is highly dependent on the developer journey and the resulting user flow..which could be resolved by user storyboarding and mapping the site out.

Ethereum actually does a decent job of providing context, possibilities and a call-to-action -- which feels very aligned with the developer journey when they hit their home page:

![screencapture-ethereum-org-1489676461375](https://cloud.githubusercontent.com/assets/5605552/24002944/70ad1d4e-0a38-11e7-87ee-f78ce9614199.png)

---

@vsund commented on [Thu Mar 16 2017](https://github.com/blockstack/blockstack/issues/93#issuecomment-287123609)

Especially the "Kickstart a project with a trustless crowdsale" is a thing that would be really cool to have. It's a good advertisement for an app that's built on Blockstack while getting more people to build these.

---

@guylepage3 commented on [Thu Mar 16 2017](https://github.com/blockstack/blockstack/issues/93#issuecomment-287148895)

@pstan26 That example was talking about visual layout and messaging tone.

---

@guylepage3 commented on [Thu Mar 16 2017](https://github.com/blockstack/blockstack/issues/93#issuecomment-287149479)

I do not believe using our competition as a base for copy/change is a wise strategy. We can learn from what they are doing probably not a good idea to copy their communications.

---

@pstan26 commented on [Thu Mar 16 2017](https://github.com/blockstack/blockstack/issues/93#issuecomment-287151366)

Ethereum example was an aside about structure of content much moreso than copy itself. The items as you read top to bottom give you a logical progression of things to consume and do.  Value prop + what it is, download the software so you can use it hands on, where to learn about building + what you can build, install command line. Perhaps this better added to another GH issue like https://github.com/blockstack/blockstack/issues/233.

**Comment by guylepage3** [comment]
Let's also take these into consideration for the landing layout..

https://medium.muz.li/3-trends-in-landing-page-design-5cf900f2c90f

**Comment by shea256** [comment]
Very cool @guylepage3, digging these three trends.

**Comment by guylepage3** [comment]
Yeah.. i had a diagonal layout in mind for the landing view after reading through @pstan26's content. seems to logically fit the content.

**Comment by pstan26** [comment]
Very much like the diagonal effect above all the rest for a couple reasons: 
It adds dimensionality, which gives a sense of space i.e. the decentralized web as a place *you the user* can visit...rather than a place your computer visits.
It still allows for clean messaging to exist above it and below it.

**Comment by guylepage3** [comment]
@shea256 @pstan26 @muneeb-ali @larrysalibra,

I'm closing out this issue as it seems as though content has been finalized here:
https://github.com/blockstack/blockstack.org/blob/be8c838f29f5d186f08720dea0f34390fb1d4993/app/js/pages/HomePage.js
