### ISSUE TITLE
"INTRO" page content

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack.org#264]

**Comment by pstan26** [comment]
Will add content here: https://paper.dropbox.com/doc/What-is-Blockstack-Page-jPoPv0MthDQpcyL7X255P

**Comment by pstan26** [comment]
_to be filled out_

What
  Decentralized Internet
  Developer Platform
  Frontend: Portal
  Backend: Core
  Stack
    BNS
    Atlas
    Blockstack Naming System
    Storage (Vault)

Why 
   Manifesto

Who

  Link to About page
  Open Source community

When

  Founded
  Roadmap

How
    System diagram

**Comment by shea256** [comment]
- BNS: the Blockstack Name System
- Atlas: Blockstack's P2P network for discovery
- Gaia: Blockstack's storage system
- Chronos: Blockstack's virtual blockchain
- Aura: Blockstack's authentication system

**Comment by pstan26** [comment]
Ok I have to admit, these names look tight af.

**Comment by muneeb-ali** [comment]
Love the names! I can sign off on them today. We can wait for others to sleep over and get sign-offs.

I'd also add the "Blockstack identity system" to the list of things to get sign-off for. That is a more complicated one and we can use the following terms: 

- Username (that refers to the domain name in the .id namespace) 
- Profile (the user profile data associated with the .id names) 
- Blockstack identity (a generic term that refers to the broader identity and not to the username or profile)

**Comment by larrysalibra** [comment]
I like the names as well.

> Username (that refers to the domain name in the .id namespace)

I thought we were letting people use names in any namespace for identity.
