### ISSUE TITLE
Site map and goals for each .org page

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack.org#266]
**Home** ([site](blockstack.org) | [GH](https://github.com/blockstack/blockstack.org/issues/249)))
- Get site visitors to generally understand what blockstack is and get them to take their first action towards building an app. Blockstack Value Proposition, Short Intro, CTA to download Portal, Vision of apps, CTA w/ Tutorial, manage expectations on whats next.

**About** ([site](https://blockstack.org/about) | [GH](https://github.com/blockstack/blockstack.org/issues/265) 

**Intro ∆ -> What is Blockstack?** ( [site](https://blockstack.org/intro) | [GH](https://github.com/blockstack/blockstack.org/issues/264))
- who, what, where, when, how, why of blockstack. Links out to blogs, papers, videos, and other pages so people can dive deeper into nearly anything about Blockstack.

**Tutorials** (site | [GH](https://github.com/blockstack/blockstack.org/issues/267))
- Crawl, walk, run. Get dev to first _aha_ moment in incredibly period of time with ease, then increase their capabilities with each subsequent tutorial.

**FAQ** (site | [GH](https://github.com/blockstack/blockstack.org/issues/244))
- provide a place where the big questions can be answered

**Blog** ([site](https://blockstack.org/blog) | GH)
- highlight developer-focused announcements

**Docs** ([site](https://blockstack.org/docs) | GH)

**Papers** ([site](https://blockstack.org/papers) | GH)

**Video** ([site](https://blockstack.org/papers) | GH)

**Comment by guylepage3** [comment]
closing issue
