### ISSUE TITLE
Page Does Not Exist error when signing into Blockstack

### ISSUE THREAD

**Issue by 9z25** [blockstack/blockstack.org#288]
I have a hello-blockstack app that I'm building. In a test run, I tried signing into Blockstack. I was redirected to blockstack.org, where the webpage threw an error: "Page Does Not Exist".

I am unable to sign in to my application now.

**Comment by larrysalibra** [comment]
Thank you for reporting @9z25 
@shea256 @guylepage3 it looks like https://blockstack.org/auth broke or got removed in the recent website work

**Comment by shea256** [comment]
@9z25 thanks for reporting! @larrysalibra I just pushed a fix and the page is back up. Please do a hard refresh to see it. Closing this issue now.
