### ISSUE TITLE
apply onename.com hamburger menu icon styles to site

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#289]
Apply onename.com hamburger menu icon style to blockstack.org.

https://onename.com/

<img width="485" alt="screenshot 2017-04-25 16 51 35" src="https://cloud.githubusercontent.com/assets/1711854/25407190/7a058c96-29d7-11e7-9b9c-42b33c85fe19.png">

http://blockstack.org

<img width="464" alt="screenshot 2017-04-25 16 51 26" src="https://cloud.githubusercontent.com/assets/1711854/25407204/863dc9a6-29d7-11e7-95ed-76e9e4ceb826.png">

**Comment by estermer** [comment]
On this right now. Almost done! working out the kinks.

<img width="402" alt="screen shot 2017-04-26 at 1 50 40 pm" src="https://cloud.githubusercontent.com/assets/17515551/25448714/5ef78d7c-2a87-11e7-9f68-9dae5fcb5e51.png">

**Comment by guylepage3** [comment]
Looking good @estermer 😄

**Comment by estermer** [comment]
I am all set with this and submitting a PR #296 

Got the hamburger style to match onename and fixed when the nav appears and when a link is clicked it makes the dropdown collapse.

**Comment by guylepage3** [comment]
Ok. cool. reviewing the pr now.

**Comment by guylepage3** [comment]
Here's the css from onename.com..

```
/* Sandwich menu (landing page) */
.navbar .navbar-toggle,.navbar .navbar-toggle:active,.navbar .navbar-toggle:focus,.navbar .navbar-toggle:hover{padding:9px 11px;border-color:transparent;margin:12px 15px;background:0 0;}
.navbar-toggle .icon-bar{display:block;width:15px;height:1px;border-radius:1px;background-color:rgba(255,2555,255,1);}
.landing-sandwich-icon{background-color:rgba(255,255,255,1)!important;}
.use-count-rounding{margin-top:50px;margin-bottom:80px;}
```

**Comment by estermer** [comment]
Thanks for the assistance @guylepage3. I can make the adjustments.

BTW I have no idea why those FAQ changes are showing in the commits, I may have to look through the log, it may have just been an accident on the branch I created. I can do some finagling to get that to be cleared.

**Comment by guylepage3** [comment]
Oh. Ok. I'll take a look and just not merge in those items. 😄

**Comment by guylepage3** [comment]
hey @estermer, here's how Bootstrap builds out it's `.navbar-toggler`.

http://v4-alpha.getbootstrap.com/components/navbar/#external-content

```
<div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-inverse p-4">
      <h4 class="text-white">Collapsed content</h4>
      <span class="text-muted">Toggleable via the navbar brand.</span>
    </div>
  </div>
  <nav class="navbar navbar-inverse bg-inverse">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>
```

**Comment by guylepage3** [comment]
So they use an SVG image now for the toggle icon. I used the boostrap v4 method and then built a new SVG image to the specs of the onename.com hamburger menu.

**Comment by guylepage3** [comment]
@estermer this item is complete. will merge in your portion of your pr at the end of the week. thanks for the help on this. it looks great. :)

**Comment by estermer** [comment]
Ok cool thanks for fixing it up.

**Comment by estermer** [comment]
i am interested in seeing the changes you made in order to fully understand what you were looking for. I tried going through and starting over and implement bootstrap classes best I could and it looked like some of them were missing. Like the `toggler` class for example and `toggleable-*` I wonder if this is something that need updating in blockstack bootstrap.

**Comment by guylepage3** [comment]
@estermer.. sure. so the best place to start with bootstrap is to take a look at their documentation. There are two versions out in the wild at the moment and one of them is unfinished and being iterated on the fly. 

**Recommendation**
1. [Bootstrap v3 documentation](http://getbootstrap.com/) — Give the Bootstrap v3 a thorough read. That will give you the foundation for understanding the class names and structure of the framework.
2. [Bootstrap v4 documentation](http://v4-alpha.getbootstrap.com/getting-started/introduction/) — This documentation is to be taken with a grain of salt. But i highly recommend reading the documentation and then [downloading the latest release](https://github.com/twbs/bootstrap/releases) to see the what is actually being implemented and what is being left out.

This will give you a strong understanding of the Bootstrap framework and css frameworks in general.

NOTE: I have been working on our own Blockstack Design System (BlockstackDS), so having a strong understanding of Bootstrap will go a long way in assisting with the design and build of BlockstackDS.

Let me know if you have any questions.

**Comment by estermer** [comment]
I did have a question. I noticed that you hard coded each nav item and took out my mapping of the links array. Was there a reason for this as I am curious about that coding choice?

**Comment by guylepage3** [comment]
@estermer can you provide me with the code that was removed? Thank you.

**Comment by estermer** [comment]
```
const links = [		
 -  { name: 'Intro', url: '/intro' },		
 -  { name: 'About', url: '/about' },		
 -  { name: 'Install', url: '/install' },		
 -  { name: 'Tutorials', url: '/tutorials' },		
 -  { name: 'Docs', url: '/docs' },		
 -  { name: 'Blog', url: '/blog' },		
 -  { name: 'Papers', url: '/papers' },		
 -  { name: 'Videos', url: '/videos' },		
 -  { name: 'FAQs', url: '/faqs' },		
 -  { name: 'Code', url: 'https://github.com/blockstack' },		
 -]

renderLinks(link) {		
 -    const { toggleDropdown } = this.props;		
 -    return (		
 -      <li className="nav-item m-b-1">		
 -        <Link		
 -          onClick={toggleDropdown}		
 -          to={link.url}		
 -          className="nav-link"		
 -          target={link.name === 'Code' ? '_blank' : ''}		
 -        >		
 -          { link.name === 'Code' ?		
 -            <i className="fa fa-github"></i>		
 -            : null }		
 -          <span>{ link.name }</span>		
 -        </Link>		
 -      </li>		
 -    )		
 -  }
```

just curious.

**Comment by guylepage3** [comment]
@estermer we are utilizing a `{Link}` component from React Router - https://www.npmjs.com/package/react-router for declaring routing or which page gets loaded in the browser.

Take a look at the `app/js/Routes.js` file, then the `import from` declaration at the top of each page, and finally how the links are declared in html.
example;
```
<Link to="/tutorials" className="nav-link">
  Tutorials
</Link>
```

Does that make sense.

**Comment by estermer** [comment]
That makes sense, which I believe is what I did, I was just building out each `<Link>` by mapping through that array instead of hard coding out each `<Link>` in the `render()` method. Is doing one over the other better in your perspective?

**Comment by guylepage3** [comment]
Yes. When contributing to open source you need to follow the method(s) executed by the previous contributors so that everyone's code is in sync.

If you feel you have a better or faster method of doing something, create a separate GitHub issue to get buy in from the community on which method to keep in the code base. 

Doing things two different ways in a project adds more code, complexity and confusion.

**Comment by estermer** [comment]
Ah ok that makes sense. I was just curious. I will put that in my back pocket for future PR's.  Thanks for letting me know.

**Comment by guylepage3** [comment]
@estermer. awesome. if you would like to assist the community with creating a PR Contribution Guidelines that would be a huge help.

We have one for the Browser but not for blockstack.org as of yet.
https://github.com/blockstack/blockstack-browser/blob/master/CONTRIBUTING.md

Don't feel obligated if it's not something that's in your wheelhouse. :)

**Comment by estermer** [comment]
I dont mind actually. I can definitely get that going using the md from the browser. i'll get a issue started too.
