### ISSUE TITLE
design new landing view hero section and illustration

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#292]
Design new landing view hero section and illustration that captivates and inspires the audience to want to stay on the site and learn more with a secondary goal to watch the Hello Blockstack Tutorial video all while abiding the [3 click rule](https://en.wikipedia.org/wiki/Three-click_rule).

### Content requirements
- Title – Main title that is intended to captivate/inspire the user to want to learn more about Blockstack. `Build decentralized, serverless apps` for now, although I do think we might want to drop "serverless" and use another word
- Description – Short description that compliments the title. Goal is to describe what blockstack is/does. `Blockstack is a new decentralized internet where you own your data and apps run locally without remote servers.`
- Main button – Button that links to the Hello, Blockstack tutorial. Button content: `Watch Tutorial`
- Secondary link – Link to Browser Portal installation page. Content: `Try the browser portal › Install`

#### Goal 
Visually convey a sense of decentralization, new internet, futuristic technology and guide the user to key content goals while allowing the user to flow quickly and easily down the page or navigate through where they want to go while abiding the [3 click rule](https://en.wikipedia.org/wiki/Three-click_rule).

#### Secondary/Tertiary Goals
- The illustration/hero must captivate and inspire the user within [3-5 seconds](https://speckyboy.com/designing-3-second-rule/).
- Inspire the audience about main mission to decentralize the internet

**Comment by pstan26** [comment]
Added a comment here https://github.com/blockstack/designs/issues/250 -- should this all be in the same issue @guylepage3 ? This is an exciting opportunity to show off blockstack design :-)

**Comment by guylepage3** [comment]
They are actually two separate issues. the illustration in the background of the hero image is based upon conversations that @shea256 and i had that determined that the overall feel for the hero should be a feeling of innovative decentralized internet.

**Comment by guylepage3** [comment]
pinning [#299: Home Page - Goals and Visuals](https://github.com/blockstack/blockstack.org/issues/299)

**Comment by guylepage3** [comment]
As per our conversation that @shea256 and I had about the hero section design/illustration.

Yesterday we decided that the two best visual themes were as follows;
1. **App components** – A visual displaying apps components with icons suggesting that there is something for every developer and gives the user the feeling that this is the place to build apps easily. The icons would also support the main headline "Build decentralized apps with identity, storage and payments."
2. **Apps** – A visual of hundreds of app icons piled up all over the base of the visual viewport. This should subliminally suggest there are hundreds of apps being build on Blockstack. Users will feel like they should get in early and build on the most trusted and secure decentralized app platform.

I have been thinking about this and thought... Hm. What do other successful app platforms visually promote. I took a look at apple and they promote the platform more than apps. Whether it be the device or the OS. In a way, Blockstack Portal is an OS. This is why I feel we should also take a look at and nail down that experience of the Home Screen and add a third possibility for the hero section showcase the Home Screen.

3. **Portal** _(Blockstack WebOS)_ – A visual of the app platform itself selling the developer on the platform with visuals that support the headline, "Build decentralized apps with identity, storage and payments."

Apple developer hero screen shots

<img width="1247" alt="screenshot 2017-05-09 09 26 42" src="https://cloud.githubusercontent.com/assets/1711854/25853161/cd84a13c-3499-11e7-8d39-cfb3957abd2c.png">
<img width="1247" alt="screenshot 2017-05-09 09 26 54" src="https://cloud.githubusercontent.com/assets/1711854/25853162/cd8ac2ec-3499-11e7-83a0-0b1682f7a92c.png">

**Comment by guylepage3** [comment]
A quick and dirty example of what this could look like...

<img width="1439" alt="screenshot 2017-05-09 12 25 00" src="https://cloud.githubusercontent.com/assets/1711854/25861392/9816cf20-34b2-11e7-94a7-cf009a6f82cc.png">

**Comment by shea256** [comment]
@guylepage3 Very interesting. I'll think about this more. Highlighting the platform might be the way to go.

**Comment by cryptocracy** [comment]
might i suggest  ... instead of 
"... running locally without remote servers" 

have it end with 
"... running locally without 3rd party servers" 
or perhaps even
"... running locally without dependency on 3rd party servers" 

Just my two cents, because to me remote servers isn't a bad thing, if I own them lol

**Comment by guylepage3** [comment]
As per the new **Hero section goals** seen here: https://github.com/blockstack/blockstack.org/issues/299#issuecomment-301593023, there are new hero concepts that have arose.

All hero section concepts:
1. **Portal** – Captivate user by focusing on the power of the portal and the strong, bold headline. A visual of the app platform itself selling the developer on the platform with visuals that support the headline, "A New Internet for Decentralized Apps". There could be various ways to execute this. Such as;
  a. Awe-inspiring rastor image in the background that enhances the focal point to the portal itself while instilling a feeling of mystery and intrigue.
  b. Strong focus on the portal home screen in ensuring that it is has wow-factor in the design, inspiring the user to think that they are looking at the future of the internet.
2. **App components** – A visual displaying apps components with icons suggesting that there is something for every developer and gives the user the feeling that this is the place to build apps easily. The icons would also support the main headline "Build decentralized apps with identity, storage and payments."
3. **Apps** – A visual of hundreds of app icons piled up all over the base of the visual viewport. This should subliminally suggest there are hundreds of apps being build on Blockstack. Users will feel like they should get in early and build on the most trusted and secure decentralized app platform.

**Comment by guylepage3** [comment]
<img width="1275" alt="screenshot 2017-05-16 14 58 00" src="https://cloud.githubusercontent.com/assets/1711854/26123213/1c74eb90-3a48-11e7-90af-391ef4261cf2.png">

**Comment by guylepage3** [comment]
Ok. So I have been working on finalizing the ever so important hero section of the home page and i have a couple of communication goal questions that need to be answered.

I think I've devised a highly effective way to lay out the hero that will entice the user's eye to flow down the page pulling them in and captivating them while still accomplishing the main goal of having the user click one of the two buttons to subscribe to the mailing list.

### Option 1
Center all copy and focus on headline, description and the two action item buttons. Then apply some whitespace followed by an isometric hero illustration that is a dissection of the new portal home screen.
**Design decisions**
By focusing on the call to action items we put precedence on importance of signing up which is a positive but a negative in the fact we are leading with a CtA (Call to Action). But we mitigate the negative aspect by opening up some whitespace followed by an intriguing illustration of our main product, portal.

### Option 2
Apply our traditional 1/1 layout with copy and cta on the left and hero image on the right.
**Design decisions**
This 1/1 split layout has been proven to work for us in the past and is highly effective in getting the user to a) read the headline, b) glance at the cta and c) captivate the user to stay by re-enforcing the headline / project with a beautifully captivating illustration of our main product, portal.
- Downside to this version is that we are wanting a 50/50 split between the two cta's. by applying this layout, there is little cognitive ability left in the 2-3 seconds that the user is initially viewing the page. We would be going from 3 highlighted items on the hero to 4 which will cause some loss in captivating the user.
- Solution - One way to solve this is to highlight one of the cta's over the other.

In my opinion i would go with something that we know works and will be highly effective. That option is Option 2. The only downside is that we would require a stronger emphasis on one of the buttons. I personally feel that we should be focusing on the "Developer" cta as they are our primary target market followed by the "User" who is our secondary market at this point in time.

Thoughts? @shea256 @larrysalibra @pstan26 @muneeb-ali 

I will provide visuals for these in a little bit.

**Comment by larrysalibra** [comment]
Sounds good. Agree developers are primary target. Will comment once there are visuals.

**Comment by guylepage3** [comment]
Option 2
<img width="1272" alt="screenshot 2017-05-17 09 44 27" src="https://cloud.githubusercontent.com/assets/1711854/26156807/787286b2-3ae5-11e7-9db5-58d8d63ca891.png">

**Comment by guylepage3** [comment]
Here's a look at what Option 2 could look like.. Button layout and emphasis will need adjusting and Illustration will change of course..

<img width="1272" alt="option-2" src="https://cloud.githubusercontent.com/assets/1711854/26156883/af4b6744-3ae5-11e7-917b-4de0cd59a6b0.png">

**Comment by shea256** [comment]
I love this layout: https://github.com/blockstack/blockstack.org/issues/292#issuecomment-301881040

**Comment by pstan26** [comment]
**Option 1**
> By focusing on the call to action items we put precedence on importance of signing up which is a positive but a negative in the fact we are leading with a CtA (Call to Action).

Will wait for visuals but it would seem capturing email is a light touch CtA, as opposed to "downloading" software. I like the centered CtA buttons too because it highlights that this is the _main_ thing you should do, as it is not off to the side.  Also since Mobile is used 1/3 of the time I'm sure the design will not allow for side to side for that portion of time. I like Option 1.

![screen shot 2017-05-17 at 9 46 26 am](https://cloud.githubusercontent.com/assets/5605552/26157001/fb1000ae-3ae5-11e7-9cb9-58efd4d7f118.png)

**Comment by shea256** [comment]
Also keep in mind we have to say "Users: Join the Waitlist" ... "Developers: Get the Developer Kit". It has to be clear that the waitlist is only for users, while developers can get the product today, which is included in the kit.

**Comment by guylepage3** [comment]
another version of option 2
<img width="1273" alt="screenshot 2017-05-17 09 51 00" src="https://cloud.githubusercontent.com/assets/1711854/26157140/67a72ecc-3ae6-11e7-82b3-c27309381148.png">

**Comment by guylepage3** [comment]
>I love this layout: #292 (comment)

@shea256, just keep in mind we will be less effective in capturing emails with that layout. I have been uneasy the past couple of days, thinking about what is wrong with that stacked layout and it dawned on me this morning. the emphasis is going to the hero image. which is great because it entices the user to learn more, but the user will skip over those to key buttons.

Layout of Option 2 allows for better flow through the content and executes all primary and secondary goals.

Thoughts?

**Comment by pstan26** [comment]
@guylepage3 quick Q where does the hero image go in option 2 when you're using mobile? Does it disappear?

**Comment by guylepage3** [comment]
Cool.. Quick executive decision... Going with the following layout followed by the isometric portal illustration.

<img width="1243" alt="screenshot 2017-05-17 10 01 30" src="https://cloud.githubusercontent.com/assets/1711854/26157721/eee8d9f2-3ae7-11e7-9e33-587c5808c009.png">

**Comment by guylepage3** [comment]
Loving this! It should look pretty cool on mobile as well.

@shea256 we may need/want to hide the description copy on mobile to allow for focus on the two buttons. I'll show a snapshot of this once built out.

**Comment by shea256** [comment]
ok sounds good @guylepage3

**Comment by guylepage3** [comment]
>@guylepage3 quick Q where does the hero image go in option 2 when you're using mobile? Does it disappear?

Yes. it would have been hidden on mobile. But problem is resolved with new chosen layout. The illustration will appear below.

**Comment by guylepage3** [comment]
Complete. Chosen layout.. 

https://github.com/blockstack/blockstack.org/issues/292#issuecomment-302099783

**Comment by guylepage3** [comment]
<img width="1435" alt="screenshot 2017-05-18 17 04 41" src="https://cloud.githubusercontent.com/assets/1711854/26223487/3b332178-3bec-11e7-8ca4-be25f0086401.png">

**Comment by guylepage3** [comment]
@shea256 @larrysalibra 

what do you guys think about this hero layout vs. the one above? I am recommending that we apply this layout as it emphasizes the portal more, allows for more white space between the navbar and content which enables the user to read the headline more. also the chosen background image has light shining down on the portal more which assists the communication goal for the hero.

Thoughts?

<img width="1436" alt="screen shot 2017-05-20 at 11 24 45 am" src="https://cloud.githubusercontent.com/assets/1711854/26276903/58020a80-3d4f-11e7-87b1-dc6b0e139719.png">

**Comment by shea256** [comment]
I like it but I think we should come back to this at the very end.

Let's get the 5 home page visuals out first, then we can revisit.

**Comment by guylepage3** [comment]
Just seeing this now.. Ok. sounds good. I've updated InVision sync as well so who ever wants to view and comment, please do so and follow along here:

**InVision link**:
https://invis.io/8HBT0K14D
