### ISSUE TITLE
FAQ page not loading

### ISSUE THREAD

**Issue by estermer** [blockstack/blockstack.org#294]
#Clicking on the FAQ page link in the footer loads nothing and causes an issue with navigation around the rest of the site.

I did a little digging and some or all of the issue could be coming from the docs.json file is missing the faq markdown. This may have just been missed when the tutorials pages were being reworked, so adding it back in might fix the issue.

<img width="569" alt="screen shot 2017-04-26 at 10 27 44 am" src="https://cloud.githubusercontent.com/assets/17515551/25439660/062609e2-2a6b-11e7-8e51-7edc68eafa95.png">

in `js/pages/FAQPage.js`:

<img width="595" alt="screen shot 2017-04-26 at 10 29 03 am" src="https://cloud.githubusercontent.com/assets/17515551/25439737/45f96ad2-2a6b-11e7-858a-33084a3c68bd.png">

**Comment by pstan26** [comment]
Awesomee thanks Eric, faster we get this up, the better served developers will be.

**Comment by pstan26** [comment]
@guylepage3 @shea256 this is something we should fix before Consensus.

**Comment by pstan26** [comment]
This is still an outstanding issue, recently reported again by a community member.

**Comment by davydog187** [comment]
Secondary to this issue (which may be worth opening up a separate issue), devs that aren't part of the gitub linked dependencies can't run the project locally.

**Comment by davydog187** [comment]
https://github.com/blockstack/blockstack.org/blob/master/package.json#L68-L70 

The above should be published through standard means, rather than as github links.

**Comment by guylepage3** [comment]
hey guys, i'll take a look at this tomorrow at some point. sorry for the delay on this.

**Comment by guylepage3** [comment]
looking at this now

**Comment by guylepage3** [comment]
ok so i just took a look and it looks like the FAQ page was setup differently than the rest of the markdown referenced content and will need to take look at it further in the am.

**Comment by pstan26** [comment]
reping:

https://twitter.com/brian44913/status/880498217443610624

**Comment by guylepage3** [comment]
>Secondary to this issue (which may be worth opening up a separate issue), devs that aren't part of the gitub linked dependencies can't run the project locally.

@davydog187 you shouldn't have an issue running the site locally. everyone else is managing to run it locally without any issues. please follow the [README.md](https://github.com/blockstack/blockstack.org/blob/master/README.md) instructions and you should be ok. 

If you have an issue running the site locally please create a separate issue and we'll get to it. Thanks.

@pstan26 Let me add this to my list of to do's today. Thank you for the reminder.

**Comment by davydog187** [comment]
I'll check again

**Comment by arisgk** [comment]
@guylepage3, @pstan26 Footer link seems to point to a wrong URL. Replacing `/faqs` with `/faq` did the trick.

**Comment by guylepage3** [comment]
👍🏻

**Comment by guylepage3** [comment]
closing issue
