### ISSUE TITLE
Fix Install page on smaller screen widths

### ISSUE THREAD

**Issue by estermer** [blockstack/blockstack.org#295]
<img width="398" alt="screen shot 2017-04-26 at 1 47 20 pm" src="https://cloud.githubusercontent.com/assets/17515551/25448587/f37c5e9c-2a86-11e7-8aa8-ff56d990ea2d.png">

**Comment by guylepage3** [comment]
duplicate issue. please search for relevant issues before creating new issues. thank you. 😄 
https://github.com/blockstack/blockstack.org/issues/290
