### ISSUE TITLE
∆ hero title copy on landing page

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack.org#298]
![screen shot 2017-05-06 at 9 09 08 pm](https://cloud.githubusercontent.com/assets/5605552/25777112/5307a598-32a1-11e7-9140-848637edacaa.png)

**@shea256 arrived at the following headline after seeing Twilio's landing page (below). Need sign off from team first : "Build decentralized apps with identity, storage and payments"**

![screen shot 2017-05-06 at 9 25 14 pm](https://cloud.githubusercontent.com/assets/5605552/25777152/9757c9d4-32a2-11e7-9989-9034b6e8ba5a.png)

**Comment by shea256** [comment]
Thanks for creating this issue Patrick. Let's hear from the team and see what people think.

**Comment by guylepage3** [comment]
I'm all for this messaging. Simple and straight to the point
