### ISSUE TITLE
Add a "contact us" in footer

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack.org#301]
We have had a couple folks over the past month try to get in touch with us, but couldn't figure out how. This hurts PR & BD efforts.

- [ ] We need to make it easy for folks to connect with us, so perhaps for now we put a "For serious business/media related inquires email contact@blockstack.org" below "Made with <3 by the blockstack community.

- [ ] Create contact@blockstack.org

**Comment by guylepage3** [comment]
hey @pstan26 are we still wanting to add this?

**Comment by pstan26** [comment]
What do you think about instead of an email, we create a google form?

**Comment by guylepage3** [comment]
I mean, what are we looking to capture with this? Has there been a strong push for a contact us form?

**Comment by pstan26** [comment]
This was in response to Reason TV having a hard time getting in touch. Not clear to me there is a huge demand for this.

**Comment by guylepage3** [comment]
Ok let's close this and if it arrises that we need this then we'll create a new issue for it.
