### ISSUE TITLE
Update newsletter onboarding content

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack.org#303]
Currently it looks like this:
![screen shot 2017-05-14 at 5 53 51 pm](https://cloud.githubusercontent.com/assets/5605552/26038090/5ab0bbe4-38ce-11e7-91da-50c37474b8ff.png)
![screen shot 2017-05-14 at 5 26 18 pm](https://cloud.githubusercontent.com/assets/5605552/26038094/5e7b1094-38ce-11e7-9c27-21a805bd19f2.png)
![screen shot 2017-05-14 at 5 51 26 pm](https://cloud.githubusercontent.com/assets/5605552/26038095/612d2778-38ce-11e7-8016-21e42af0d923.png)
![screen shot 2017-05-14 at 5 51 46 pm](https://cloud.githubusercontent.com/assets/5605552/26038096/63c79662-38ce-11e7-926e-8e0200304ee2.png)
![screen shot 2017-05-14 at 5 52 26 pm](https://cloud.githubusercontent.com/assets/5605552/26038097/672a81c0-38ce-11e7-8764-8f678eee005f.png)

**Comment by guylepage3** [comment]
Issue moved to [blockstack/designs #295](https://github.com/blockstack/designs/issues/295) via [**ZenHub**](https://www.zenhub.com/)
