### ISSUE TITLE
adjust video div to be flush top, right and left to view port on tutorials item page

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#309]
There is now padding on all sides that needs to be reduced so video div fit flush top, right and left to view port.

**Comment by guylepage3** [comment]
https://blockstack.org/tutorials/hello-blockstack

**Comment by arisgk** [comment]
@guylepage3 we can reduce the padding using one of the following solutions:

**Solution 1**: http://g.recordit.co/ogpK9jUIU6.gif - Use a bootstrap container to align the iframe with the rest of the page elements.

**Solution 2**: http://g.recordit.co/aQ89zci5Y3.gif - Extend the iframe dimensions to fit its current container.

**Current (with padding)**: http://g.recordit.co/Vb95TFQBXC.gif

**Comment by guylepage3** [comment]
@arisgk I think he goal here is to extend the black background to full width.

**Comment by arisgk** [comment]
@guylepage3 In this one I just made the black background full-width http://g.recordit.co/8qaiPF3oLe.gif. We also have the option to make the video itself full-width (padding is automatically adjusted depending on aspect ratio in this case), like here http://g.recordit.co/6N9eLPMUGG.gif.

Let me know if any of these works.

**Comment by guylepage3** [comment]
This is awesome @arisgk. that first gif looks as though it has a `height: 100%;`. Maybe let's make it a fixed height of the video. thoughts?

**Comment by arisgk** [comment]
@guylepage3 In the first gif, the black background div has a fixed height of `600px`. I can remove it, in which case this div and the video will have equal heights (the video height). Is it the desired result?

![video-padding](https://user-images.githubusercontent.com/4354335/28033853-373a46c8-65b8-11e7-9caa-45747466fee4.jpg)

**Comment by guylepage3** [comment]
@arisgk this is awesome. One last task is to pull the video div up to get rid of the whitespace between the navbar and the video.

**Comment by guylepage3** [comment]
PS. Really excited about this. 😄

**Comment by arisgk** [comment]
@guylepage3 Thank you! Here is the version without the whitespace:

![video-padding2](https://user-images.githubusercontent.com/4354335/28056026-1cb86c3c-6624-11e7-9acd-b032905fdd16.jpg)

**Comment by guylepage3** [comment]
complete. great work @arisgk
