### ISSUE TITLE
Broken link on Blockstack Whitepaper: A New Decentralized Internet (Part I) blog page

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#314]
The "Read the Blockstack Whitepaper" button link is broken on the Blockstack Whitepaper: A New Decentralized Internet (Part I) blog post page

https://blockstack.org/blog/blockstack-whitepaper-part-1

**Comment by shea256** [comment]
Fixed, thanks for reporting!

**Comment by guylepage3** [comment]
completed by @shea256
