### ISSUE TITLE
Brand color review

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#320]
One of the issues with the brand status right now is color

Item No. 4 (See below) in the [#277 Brand review & update](https://github.com/blockstack/designs/issues/277) discusses the strong need for a color and palette update. I recognized the need before the consensus conference last week and applied a new fresh neutral tone to the design and build of the browser which was well received.

So the following is a quick brand color iteration with a global focus on neutral brand colors

4. **Color** - One of the major issues as well as we are discovering is the overwhelming need for color and palette neutrality. We did not necessarily "choose" the color purple as much as it chose us. See [Blockstack Brand History](https://github.com/blockstack/designs/issues/247) for more history on the brand and how it came to be.

**Comment by guylepage3** [comment]
Hey guys can we talk about color?

I'd like to present two color scheme options. Both offer a very neutral feel. One is extremely neutral only offering tones with no color options at all. while the second offers a more gradual approach to brand iteration with the addition of purple.

### 1. Pure Neutral

<img width="1482" alt="screenshot 2017-05-31 18 27 24" src="https://cloud.githubusercontent.com/assets/1711854/26657654/2b46f86a-4633-11e7-97f2-91b13096c626.png">

**Pros**
Pure neutral brand – This 100% neutral brand works well with all app brands. Hands down, this will allow our developer team's brands to shine and stand out. This is a very big plus for accomplishing neutrality.

**Cons**
Stereoscopy is harder work with on black background – The stereoscopic logo we created works well with purple because of the deep purple that was was chosen. it's the right balance of magenta and cyan that allow for the desired blur effect on the purple. We could however change the our chosen highlight magenta and cyan to work with on the pure neutral black background.


### 2. Purple Neutral

<img width="1470" alt="screenshot 2017-05-31 18 29 59" src="https://cloud.githubusercontent.com/assets/1711854/26657647/1c886656-4633-11e7-9089-f30768a7e172.png">

**Pros**
Logo works well with the purple brand – The stereoscopic logo we created works well with purple because of the deep purple that was was chosen. it's the right balance of magenta and cyan that allow for the desired blur effect on the purple. We could however change the our chosen highlight magenta and cyan to work with on the pure neutral black background.

**Cons**
Purple does not play well with the entire color spectrum – Purple is not a neutral color and can be problematic to work with when on the same viewport with other colors.

**Comment by guylepage3** [comment]
@shea256 @larrysalibra @estermer @pstan26 @itsProf  Please comment when you get a moment. Thank you.

**Comment by estermer** [comment]
Here is my two cents.

If your looking for a neutral palette for developer teams to pop out. I would say that this is a huge pro. This being the case would it be possible to incorporate the purple in small amounts to retain the blockstack brand as well? I think a middle ground can be found between the two for sure. 

The other piece is, this is blockstack's branding site where people go to learn about what blockstack is all about. To what level is there going to be a need for developer teams brands to pop out on this site? I completely understood the portal being neutral since it involves the end user.

As a suggestion to the picture under number 1. You could make the nav bar more of a light gray or a white which would help the brand in the logo pop and more purple can be used in the logo. or you could do a partial  purple nav bar one that extends from the left of the viewport to just past the edge of the logo.

**Comment by guylepage3** [comment]
>I think a middle ground can be found between the two for sure.

It definitely starts to add complexity to the brand. The reason we are going down this path is to simplify the brand. We are an open source community where the less brand definitions we have the easier it will be for designers and developers of all proficiencies to contribute to the project. Simpler branding is generally stronger branding as well. i.e. Apple. Less is more.

>The other piece is, this is blockstack's branding site where people go to learn about what blockstack is all about. To what level is there going to be a need for developer teams brands to pop out on this site? I completely understood the portal being neutral since it involves the end user.

You raise a good point. But there are a couple of things again that we need to consider here;
1. We are not sure yet. So I feel we do not want to negate our option to apply other's brand to ours.. We actually had thought of something similar to this for our main hero. I just discovered this on Monday —› https://developer.apple.com/distribute/
2. Simplicity of our brand and design system - Again, we want to keep things as simple as possible for efficiency sake and keep down the complexity/barrier to execute the brand. Also, if we can keep the brand consistent across the board, it will allow for stronger brand recognition and will be less taxing on the community to keep a well maintained brand.

**Comment by guylepage3** [comment]
>I think a middle ground can be found between the two for sure.

It definitely starts to add complexity to the brand. The reason we are going down this path is to simplify the brand. We are an open source community where the less brand definitions we have the easier it will be for designers and developers of all proficiencies to contribute to the project. Simpler branding is generally stronger branding as well. i.e. Apple. Less is more.

>The other piece is, this is blockstack's branding site where people go to learn about what blockstack is all about. To what level is there going to be a need for developer teams brands to pop out on this site? I completely understood the portal being neutral since it involves the end user.

@estermer, you raise a good point. But there are a couple of things again that we need to consider here;
1. We are not sure yet. So I feel we do not want to negate our option to apply other's brand to ours.. We actually had thought of something similar to this for our main hero. I just discovered this on Monday —› https://developer.apple.com/distribute/
2. Simplicity of our brand and design system - Again, we want to keep things as simple as possible for efficiency sake and keep down the complexity/barrier to execute the brand. Also, if we can keep the brand consistent across the board, it will allow for stronger brand recognition and will be less taxing on the community to keep a well maintained brand.

**Comment by pstan26** [comment]
+1 to what @estermer said regarding letting the developer teams' brands pop... so long as we are showcasing new apps from devs around the world a la @guylepage3 's example with the apple URL. The neutral is dispassionate, and I mean that in a good way considering we are an open source project.

The purple "looks" better from the consumer-side and was initially my first choice, but through the lens of a developer, it makes sense to provide a neutral canvas to contrast your brand.

Also, it looks like you are [considering](https://github.com/blockstack/designs/issues/277) changing the logo/ wordmark a bit. If there is a move to neutral, I imagine this would force that change to happen as well.

Timing-wise, I think as we introduce new apps in late Summer, this would be a good time to make a transition to neutral, if we chose to do so.

**Comment by guylepage3** [comment]
>Also, it looks like you are considering changing the logo/ wordmark a bit. If there is a move to neutral, I imagine this would force that change to happen as well.

Not really looking to do that but may have to depending on the color outcome.

>Timing-wise, I think as we introduce new apps in late Summer, this would be a good time to make a transition to neutral, if we chose to do so.

It's a good time to start the transition now. iterate it slowly across the brand as the brand is broken right now.

**Comment by vsund** [comment]
I think that Blockstack itself should stay with its strong brand (and thereby color) but don't require (3rd party) apps to completely align with it. We should draw a line between _what's Blockstack_ and _what's on Blockstack_. For example OpenBazaar has it's own brand, but though uses Blockstack. Is it a Blockstack app that should use branding?

However, especially requiring new apps to build on Blockstack's brand, would raise the barrier to get in and build something. I totally agree with @estermer, that we don't need (or want) to assure branding for every thing that's some day on Blockstack. I think that we should solve this with not assuring the brand to "external apps" and use a strong brand for Blockstack itself.
But I don't know which plan do you have for integrating future 3rd party apps :)

**Comment by jcnelson** [comment]
I'm impartial.  I slightly prefer purple due to consistency.

**Comment by guylepage3** [comment]
@vsund, @estermer, @pstan26 

If you had to choose.. 
- [ ] - 1. Pure Neutral
- [ ] - 2. Puprle Neutral

**Comment by pstan26** [comment]
@guylepage3 I'm having second thoughts about pure neutral now. I like Purple Neutral...lol!

**Comment by vsund** [comment]
@guylepage3 I'm for Purple Neutral, although not 100% sure.

**Comment by shea256** [comment]
I intellectually like the idea of pure neutral but I'm not so sure about the look of that implementation. Apple nailed it I feel. Is there another approach we can take with pure neutral? Perhaps the black black is throwing it off.

**Comment by larrysalibra** [comment]
+1 pure neutral

**Comment by guylepage3** [comment]
>I'm not so sure about the look of that implementation

Neither am I. But it will never be right. We will constantly iterate it. We're just looking at color and how it works as a whole from execution, simplicity, efficiency, application of goals, etc.

**Comment by shea256** [comment]
OK it makes sense to me. Just so long as black isn't used as a primary color but more as a font color like in the case of Apple. At least that's my assessment on the bounds of this working well for us.

**Comment by guylepage3** [comment]
Actually it was heavily inspired by apple's black/white brand

![screencapture-apple-1496348362450](https://cloud.githubusercontent.com/assets/1711854/26699153/b9176450-46e6-11e7-91f0-903bbe6097d3.png)
![screencapture-apple-apple-events-june-2017-1496348440360](https://cloud.githubusercontent.com/assets/1711854/26699152/b917562c-46e6-11e7-9da6-40d9dec8c2d4.png)
![screencapture-apple-mac-1496348460041](https://cloud.githubusercontent.com/assets/1711854/26699154/b917f5b4-46e6-11e7-998d-b5d70aebb175.png)

**Comment by shea256** [comment]
Ah yes, it seems the key difference is in the implementation. Seems like a good direction.

**Comment by guylepage3** [comment]
yes but i feel we have to also be careful not to be a complete Apple rip-off. 🙈🙃😂

**Comment by guylepage3** [comment]
Issue moved to [blockstack/designs #288](https://github.com/blockstack/designs/issues/288) via [**ZenHub**](https://www.zenhub.com/)
