### ISSUE TITLE
Propose of new section: Partners / What's already on Blockstack

### ISSUE THREAD

**Issue by vsund** [blockstack/blockstack.org#321]
I'd like to propose a new section that shows "Partners" or "What's already on Blockstack" at the bottom of the current homepage.

Benefits of "Partners" are:
* it's good for gaining (additional) reputation from partners
* preach collaboration (we work together instead of against each other)
* catch people that would bounce after scrolling down the page and which then realise that there are some big players around (mostly thinking of Microsoft here)

And in case of "What's already on Blockstack" you can
* show off some apps (Blockstack apps, OpenBazaar, ...)
  * show what can be done on Blockstack
  * give inspiration / examples
* advertise competition
* advertise permanent activity
* have a call-to-action button "Your app next here"
* catch users (non-developers); if the target group isn't defined yet, this should happen soon :)

Most of these things are actually points from @waynevaughan from the weekly meeting.

**Comment by guylepage3** [comment]
All good points @vsund. 

Do you feel that if we took the contributors out of the "About" link in the footer and created a "Contributors" page that that would be enough? Or even just a simple change from "About" to "Contributors" would suffice? https://blockstack.org/about

**Comment by vsund** [comment]
I think the "About" page makes an additional point: Saying that the community is backed by a company that assures progress and works 24/7 on the project.Besides, a "Contributors" page sets the focus on people and not apps.
