### ISSUE TITLE
update hero design

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#323]
After two quick and dirty design implementations of the blockstack hero. A new design layout was discovered when developing the [Brand color review](https://github.com/blockstack/designs/issues/288). The **Purple Neutral** iteration of the blockstack.org hero section is a much much more mature and effective layout than it's predecessor, [restructure home page hero for better flow](https://github.com/blockstack/blockstack.org/issues/317) 

#### Purple Neutral layout
<img width="1470" alt="screenshot 2017-05-31 18 29 59" src="https://cloud.githubusercontent.com/assets/1711854/26657647/1c886656-4633-11e7-9089-f30768a7e172.png">

**Comment by guylepage3** [comment]
Pinning
- [#310: restructure home page hero for better flow](https://github.com/blockstack/blockstack.org/issues/310)
- [#292: design new landing view hero section and illustration](https://github.com/blockstack/blockstack.org/issues/292)

**Comment by guylepage3** [comment]
quick update with background image. https://github.com/blockstack/blockstack.org/commit/d38385b1b49b1d0b212cdf8fc4af67457db305a2

Old:
<img width="1083" alt="screenshot 2017-06-16 12 53 22" src="https://user-images.githubusercontent.com/1711854/27236407-ea053800-5292-11e7-9239-07fa0f2771cc.png">

New:
<img width="1084" alt="screenshot 2017-06-16 12 53 29" src="https://user-images.githubusercontent.com/1711854/27236449-15c05a92-5293-11e7-965c-28e444a360da.png">

**Comment by shea256** [comment]
@guylepage3 Faded background image?

Also, can we increase the size of those stats as we discussed? Large numbers.

**Comment by guylepage3** [comment]
>Faded background image?

Everything in this layout actually.. from headline font to placement, spacing, header, etc.
https://cloud.githubusercontent.com/assets/1711854/26657647/1c886656-4633-11e7-9089-f30768a7e172.png

>Also, can we increase the size of those stats as we discussed? Large numbers.

Yes.

**Comment by guylepage3** [comment]
@shea256 based upon the conversation we just had, I will be going with the layout below showing the browser.

https://cloud.githubusercontent.com/assets/1711854/26657647/1c886656-4633-11e7-9089-f30768a7e172.png

Please confirm. Thanks.

**Comment by guylepage3** [comment]
doing this now

**Comment by shea256** [comment]
@guylepage3 I know you plan on getting around to the hero section. Let's make sure to bang this out before we move on to the sale site. Also the large stats are very important so let's not forget to make that update.

**Comment by guylepage3** [comment]
>@guylepage3 I know you plan on getting around to the hero section. Let's make sure to bang this out before we move on to the sale site. Also the large stats are very important so let's not forget to make that update.

Sounds good. moving this to my list of deliverables to be done before token site.

**Comment by guylepage3** [comment]
new hero section..

![hero-1 2x](https://user-images.githubusercontent.com/1711854/28524353-2175e018-704e-11e7-98ed-206cfaa9df21.png)

**Comment by guylepage3** [comment]
new hero with new browser home screen.

![hero-1 2x](https://user-images.githubusercontent.com/1711854/28527142-a77f4c72-7057-11e7-8250-afadce063b29.png)

**Comment by guylepage3** [comment]
new hero with new browser home screen status bar.

![hero-1 2x](https://user-images.githubusercontent.com/1711854/28527227-e68f3db4-7057-11e7-825a-12caa9d740b9.png)

**Comment by guylepage3** [comment]
update. added "Health" to "Afia"...

![hero-1 2x](https://user-images.githubusercontent.com/1711854/28529595-f5e6ff3e-705e-11e7-9479-6f81b9e6238f.png)

**Comment by pstan26** [comment]
hot hot hot
