### ISSUE TITLE
Add Airbnb's enzyme testing utility

### ISSUE THREAD

**Issue by arisgk** [blockstack/blockstack.org#344]
Airbnb's [enzyme](https://github.com/airbnb/enzyme) library provides very useful testing utilities for React. It plays well with Mocha so we will just have to add it to our dependencies and import it in our tests. 

It is also mentioned in React documentation [Test Utilities](https://facebook.github.io/react/docs/test-utils.html) page.

**Comment by guylepage3** [comment]
What do you think about adding this @larrysalibra @shea256 @estermer?

**Comment by larrysalibra** [comment]
Sounds great to me. We currently don't really have any tests for react rendering. @arisgk it would be great if you'd like to take a stab at adding some.

**Comment by arisgk** [comment]
@larrysalibra Sure, that would be great!
