### ISSUE TITLE
Break main CSS file into smaller ones

### ISSUE THREAD

**Issue by arisgk** [blockstack/blockstack.org#345]
Our [main.css](https://github.com/blockstack/blockstack.org/blob/master/app/styles/main.css) file is already big and it could get bigger as the project evolves. This can make it difficult to find styles, choose the best place (in the file) to add new ones or create conflicts. We could consider some different approaches in order to have more modular stylesheets. 

Since React introduces a component-based approach, in my opinion, the best would be to have a CSS file per **presentational component** (if needed). For example, footer-related styles can be included in a `footer.css` stylesheet in the same folder with the `Footer` component. With this approach though, we would be benefited by using [Webpack](https://webpack.js.org/) as a build tool instead of Gulp. More info about this approach can be found in [this](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-stylesheet) `create-react-app` repo docs section.

An easier solution which would not lead us to change a build tool would be to just split `main.css` into smaller (component-based or page-based) files.

Other approaches proposed can be better than these, I think it would be beneficial to start a discussion on this.

**Comment by guylepage3** [comment]
@arisgk this would be an awesome task for you to tackle. 😄 

Do you notice how i've started break things up in anticipation for a move to the latest `Boostrap v4` and an eventual move to our own Blockstack Design System?

```
/* Table of Contents */
/*  1. Colors */
/*  2. Options */
/*  3. Spacing - Note: b4 has resolved a lot of spacing issues. for this version we are utilizing the custom spacing rules from blockstack.com. Upon import of blockstack-bootstrap, go through styles and replace with latest spacing rules from b4. */
/*  4. Body */
/*  5. Links */
/*  6. Grid breakpoints */
/*  7. Grid containers */
/*  8. Grid columns */
/*  9. Fonts */
/* 10. Components */
/* 11. Tables */
/* 12. Buttons */
/* 13. Forms */
/* 14. Dropdowns */
/* 15. Z-index master list */
/* 16. Navbar */
/* 17. Navs */
/* 18. Pagination */
/* 19. Jumbotron */
/* 20. Form states and alerts */
/* 21. Cards */
/* 22. Tooltips */
/* 23. Popovers */
/* 24. Tags */
/* 25. Modals */
/* 26. Alerts */
/* 27. Progress bars */
/* 28. List group */
/* 29. Image thumbnails */
/* 30. Figures */
/* 31. Breadcrumbs */
/* 32. Media objects */
/* 33. Carousel */
/* 34. Close */
/* 35. Code */
/* 36. Status Bars */
/* 37. Misc */
```

**Comment by guylepage3** [comment]
From conversation on Jul 7, 2017

@arisgk  love that you're taking initiative about breaking up / cleaning up our `main.css` file. :smile:

I've replied to your initial GitHub issue.. We should really start planning out a 2 phase approach..
1. Break everything up in anticipation of moving over to the latest version of `Bootstrap v4`
2. Then the move over to our own [Blockstack Design System (BlockstackDS) Roadmap Plan](https://github.com/blockstack/design-system/issues/5)

Always try to keep in mind that our `Blocsktack Design System` is something that will work with ALL Blockstack products. Products that we have today and products that we will have in the future.

So the steps should go...
1. Break everything up in anticipation of moving over to the latest version of `Bootstrap v4`
    1. Break everything up into the 37 categories in one file, `main.css`.
    2. thorough test on `blockstack/blockstack.org` for breakages while documenting high level issues.
    3. repeat steps a & b on all Blockstack products

**Comment by matheusml** [comment]
Are we considering [CSS Modules](https://github.com/css-modules/css-modules)?
I have some experience with it, I can help to explain why it should be a good idea and how to implement it in case you're considering to use it.

**Comment by guylepage3** [comment]
>Are we considering CSS Modules?

Yes we are... Really like their concepts as they seem to fit will with React.js
