### ISSUE TITLE
Email signup language is confusing 

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack.org#350]
I think that our current email signup language is confusing. There are a couple of things here:

1. We use the email list as the primary way of joining the Blockstack community. We used to have blockstack.org/join for this (which still re-directs) with the language "Join the Blockstack community and stay updated" or something similar. That was a much clearer way to communicate what was going on. Saying "User waitlist" is confusing because people don't know that they're actually signing up for frequent updates from the community. Also, I've seen people ask on Twitter that "how long is the waitlist?". I'm not sure if we'll be releasing the consumer release to these people in particular order of signup and maintain an explicit "waitlist". I'd suggest changing the language back to "Join the Blockstack community". 

2. The link "Developers > Browser Kit" should go to our Github or it should say "Sign up for our developer mailing list" which seems to be the intention here. 

I think that presenting the two mailing lists as "General community mailing list" and "Developer mailing list" can work. Most people understand what these things are. We can even have a simple interface where people can click/check the respective options and sign up for both mailing list by entering their email once.

**Comment by muneeb-ali** [comment]
Here is a tweet relevant to this issue:

https://twitter.com/chris__martin/status/895088608658341888

I agree with Chris, a "wait list" doesn't go well with an open-source project (I should be able to use the open-source software in whatever current form it is in) and it doesn't go well with a decentralized project (I should not need permission to use the software).

**Comment by pstan26** [comment]
I think highest priority is email capture, since re-engagement will be
critical as we send new tutorials etc.

- Starting with "Developers > Browser Kit", as Muneeb mentioned could we
make this redirect to github in a new tab (also less dropoff from fewer
clicks and puts them closer to documentation), so they still have a chance
to join the mailing list without having to click back?

- I think it is worth replacing "Users > Join the Waitlist" with something
simple like "Get Updates" that leads to a simple email form field where you
must check off at least one option: (1) General Updates (2) Developer
Updates. The sooner we do this the better, because our email list is only
growing as we arrive closer to a consumer product and segmentation of users
& devs will become all the more important.

**Comment by guylepage3** [comment]
@shea256 do you want to take a quick stab at this issue and then I'll come around and clean things up?

**Comment by guylepage3** [comment]
@estermer do you want to take this one?

**Comment by jimodo** [comment]
Is there a potential to ask users what they want? Might ensure we give them the right level of involvement and aren't being too much. 

Email: _________
What do you want to hear about? (Tick box)
(a) "Give me all the news, announcements, etc"
(b) "Tell me about the breakthroughs" - less frequent, big announcements e.g blockstack summit videos.
(c) "Waitlist - Tell me when X is here"
(d) "All of the above"

Might help?

**Comment by vsund** [comment]
I actually think this would have benefits over the current implementation.
* More precise graduation of user groups without much more friction (user get better targeted mails)
* User enter their email address and have to decide then (so only one mail input box and no decisions before using it)

I'm for an input box and a popup with the question when entering an address 👍

**Comment by muneeb-ali** [comment]
![image](https://user-images.githubusercontent.com/669932/29622113-855c40a4-87f0-11e7-9155-6eccd764a405.png)

Checking in on this. What's the ETA for this?

I'd love to figure out a faster way of pushing out small changes like this.

**Comment by muneeb-ali** [comment]
Checking in again. CC: @guylepage3, @shea256, @larrysalibra. 

The process for making small changes to the website seems pretty broken right now. Let's discuss this in our weekly meeting on Monday. We need to reduce the friction to making these updates and make quicker iterations on the live website. This issue, for example, has been pending for 5+ weeks now and we need faster iteration cycles for things that need fixing/improvement on the live website.
