### ISSUE TITLE
live design blockstack summit 2017 summary page

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#354]
Live design Blockstack Summit 2017 summary page

**Comment by pstan26** [comment]
Hey @guylepage3 

(1) What do you think about blockstack.org/summit17 for a URL?
(2) I've also have a ton of great professional photos from the Summit now on my laptop (cc @larrysalibra :-) ). Maybe we can list these below the videos? Lmk what you think.
(3) Here is some intro copy as well as the speaker list and their talks:

On July 27th, 2017, we hosted the Blockstack Summit at the Computer History Museum. It was a day to take people back to the original dream of the internet back in 1989 -- one of a shared space where we could be free to create together. Attendees and speakers from all over the world came together for this one day event to envision a new internet built for freedom, security, and innovation. 

It was a star-studded lineup of speakers and they did not disappoint. You'll find videos and photos below from the event. We hope you enjoy them as much as we did, and would love to hear what your favorite parts were by tweeting your favorite speaker quotes and clips mentioning [@blockstackorg](twitter.com/blockstackorg).

**Videos:**
"Welcome to Blockstack Summit" Muneeb Ali and Ryan Shea, Blockstack Co-founders

"The Next Wave of Computing" Muneeb Ali, Blockstack Co-founder

"A New Blockstack Internet" Ryan Shea, Blockstack Co-founder

"The Importance of Layer Two" Elizabeth Stark, Lightning Labs Co-founder

"Blockstack App Ecosystem"  Patrick Stanley, Blockstack Growth Partner
"Building Decentralized Consumer Applications: Casa Case Study" Jeremy Welch, Casa / Bedkin Founder
"OpenBazaar 2.0 and Blockstack" Brian Hoffman, OpenBazaar Founder

"A Conversation with Bram Cohen & Muneeb Ali"
Bram Cohen, BitTorrent Creator
Muneeb Ali, Blockstack Co-founder

"Identity Panel"
Daniel Buchner, Microsoft Head of Decentralized Identity
Drummond Reed, Evernym Chief Trust Officer
Melanie Shapiro, Tokenzie CEO
Ryan Shea, Blockstack Co-founder
Moderated by Dan Elitzer, IDEO coLAB Blockchain & Digital Identity Lead

"Storage Panel"
Muneeb Ali, Blockstack Co-founder
Juan Benet, Filecoin, IPFS Founder
Galen Wolfe-Pauly, Urbit Founder
Moderated by Dan Elitzer, IDEO coLAB Blockchain & Digital Identity Lead

"Quantifying Decentralization" Balaji Srinivasan, Andreesen-Horowitz Board Partner and 21 CEO

"Payments Panel"
Ryan X Charles, Yours Network CEO
Elizabeth Stark, Lightning Labs Co-founder
Balaji Srinivasan, Andreessen Horowitz Board Partner and 21 CEO
Moderated by Tuur Demeester, Adamant Research, Economic & Investor, Editor in Chief

"Investing in Decentralized Applications Panel"
Meltem Demirors, Digital Currency Group Director
Naval Ravikant, AngelList Founder
Garry Tan, Initialized Capital Managing Partner
Moderated by Brian Lio, Smith + Crown CEO

"A Conversation with Naval Ravikant & Ryan Shea" Naval Ravikant, AngelList Founder, Ryan Shea, Blockstack Co-founder

"Decentralization & the Knowledge Age" Albert Wenger, Union Square Ventures General Partner

"Creating the Decentralized Connectivity Layer" Daniela Perdomo, goTenna CEO and Co-founder

"Q&A" Muneeb Ali & Ryan Shea, Blockstack Co-founders, Moderated by Alice Lloyd George, RRE Ventures Principal

"Closing Remarks" Muneeb Ali & Ryan Shea, Blockstack Co-founders

"Governance" Arthur Breitman, Tezos Co-founder

"Yours: Improving Content Quality with P2P Micropayments" Ryan X Charles, Yours Network CEO

"How Blockchain will Revolutionize Supply Chain & Insurance" Leanne Kemp, Everledger Founder

"UX Talk - Design Thinking" Tyler Schmidt, UX Design Consultant

"Economics of Distributed Systems" Zavain Dar, Lux Capital Partner

**Comment by guylepage3** [comment]
@pstan26 

>(1) What do you think about blockstack.org/summit17 for a URL?

Let's go with `blockstack.org/summit2017` for the URL

>(2) I've also have a ton of great professional photos from the Summit now on my laptop (cc @larrysalibra :-) ). Maybe we can list these below the videos? Lmk what you think.

Let's not go to crazy with the number of images. More concerned about finding quality shots to break up copy/content on the page. Maybe we can have a "> More photos" button taking users to Flickr or something like that.

**Comment by pstan26** [comment]
Sounds perfect. re: photos, how many do you think is reasonable? There are some quality shots that I can select for/with you.

**Comment by guylepage3** [comment]
if you can pick out 6 close ups, 6 from farther out, 6 group shots, 6 lunch and 6 of the main room that would be amazing for me to choose from. 😄

**Comment by pstan26** [comment]
perf, shall I send them in a zip file in here?

**Comment by guylepage3** [comment]
If you can upload them here that would be ideal. If not you can just dm me a dropbox link.

**Comment by pstan26** [comment]
k

**Comment by pstan26** [comment]
https://drive.google.com/a/blockstack.com/file/d/0BxRgEJM6X5t-Z013TklLRVA3V3c/view?usp=sharing shared with you via google drive since file size was so large

**Comment by pstan26** [comment]
just updated the post containing all the titles with all the YouTube URLs. Going to Queue up an email

**Comment by guylepage3** [comment]
thank you for the links @pstan26 👍

**Comment by guylepage3** [comment]
Here's a screen shot of what we have so far for the summit page..

<img width="1248" alt="screen shot 2017-08-11 at 6 22 46 am" src="https://user-images.githubusercontent.com/1711854/29209633-8b914f10-7e5d-11e7-8b39-41cbbae3f94e.png">
<img width="1249" alt="screen shot 2017-08-11 at 6 23 22 am" src="https://user-images.githubusercontent.com/1711854/29209646-9e51ecea-7e5d-11e7-88f9-b356d988f544.png">

**Comment by guylepage3** [comment]
@pstan26 here are your image choices for the email.

![summit-image](https://user-images.githubusercontent.com/1711854/29213590-df05eac0-7e71-11e7-99d6-9ea6e502e6be.png)
![summit-image2](https://user-images.githubusercontent.com/1711854/29213591-df0b1b8a-7e71-11e7-9ca8-e89e9cadcf49.png)

**Comment by guylepage3** [comment]
complete. closing issue.
