### ISSUE TITLE
update the team section so that it's pulling from a markdown document with bios found on /blockstack/blockstack instead of config.js

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack.org#356]

**Comment by shea256** [comment]
This is the file that needs to be updated so that it has a build process for the team section that is similar to the build processes for the video section and the roadmap section: https://github.com/blockstack/blockstack.org/blob/master/gulp/tasks/buildConstants.js

**Comment by jackzampolin** [comment]
So the [`config.js`](https://github.com/blockstack/blockstack.org/blob/master/app/js/config.js#L159) has a bunch more information about the team members than the comparable document in [`blockstack/blockstack`](https://github.com/blockstack/blockstack/tree/master/contributors). Should we move the data in `config.js` to the `blockstack/blockstack` repo?
