### ISSUE TITLE
adjust width of all videos through out site on mobile

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#363]
Videos do not shrink when with the viewport of the browser as they shrink down.

**Comment by guylepage3** [comment]
Assigning issue to @arisgk as he is familiar with the video component on the site.

**Comment by guylepage3** [comment]
Hey @arisgk, here's the issue..

The video is actually remaining the same height and not resizing as seen in the image below..

<img width="1334" alt="screenshot 2017-08-10 11 21 18" src="https://user-images.githubusercontent.com/1711854/29178115-a1c1ead2-7dbe-11e7-8099-e01a19fbf8b3.png">

<img width="635" alt="screenshot 2017-08-10 11 20 21" src="https://user-images.githubusercontent.com/1711854/29178121-a9dae2fa-7dbe-11e7-8626-a58a8acbbc83.png">

When you play it it opens to the standard video player of your device, on mobile. But reframes in the iframe on desktop.

The better way to look at this issue is what we are trying to accomplish.

Goal:
- Have the video and video frame scale down on smaller viewports/devices.

Currently the video and video frame do not scale down and we can see that Youtube is smart enough to detect the width of the viewport and scale the video down so it does not get cut off. But we are then left with an odd looking frame on the website. See below

<img width="1029" alt="screenshot 2017-08-10 11 28 30" src="https://user-images.githubusercontent.com/1711854/29178341-44cdbc7e-7dbf-11e7-8339-a80efe65f36d.png">

**Comment by guylepage3** [comment]
What are are looking for is a video frame that will scale down as seen here.

![screenshot-2017-08-10-11 28 30](https://user-images.githubusercontent.com/1711854/29178744-759798ce-7dc0-11e7-8b62-fd836b5ec6b2.png)

**Comment by arisgk** [comment]
iframe height stays the same, which seems to cause the problematic behavior

**Comment by guylepage3** [comment]
Correct.. 😄

**Comment by guylepage3** [comment]
hey @arisgk did you have a chance to work on this?

**Comment by arisgk** [comment]
@guylepage3 For tutorials page, https://github.com/blockstack/blockstack.org/pull/365 fixed this. I just pushed a PR for funding page and https://github.com/blockstack/blockstack.org/issues/383 which is relevant. Do you think we should apply similar changes anywhere else?

**Comment by guylepage3** [comment]
hey @arisgk can you bring this up in tomorrows scrum as a reminder for me?

**Comment by guylepage3** [comment]
>Do you think we should apply similar changes anywhere else?

@arisgk awesome work! 😄 

Yes. Do you think you could go through the site and anywhere we are using the `EmbedYouTube.js` component apply the same method?

**Comment by guylepage3** [comment]
closing issue.
