### ISSUE TITLE
create transparent background VC logos for blockstack.org/funding

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#375]
Create temporary high resolution logo in the partners section of blockstack.org/funding that have transparent backgrounds.

**Comment by guylepage3** [comment]
@pstan26 can we request SVG images from the following firms?

- [ ] OpenOcean
- [ ] LUX
- [ ] VersionOne
- [ ] RisingTide

I have Compound's SVG image. Thank you. :)

**Comment by pstan26** [comment]
Thanks! I've emailed all VCs and cc'd you for good measure.

**Comment by guylepage3** [comment]
@pstan26 complete. I created svg images for Rising Tide and Lux
