### ISSUE TITLE
integrate ui from api.onename.com for FAQ section

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#380]
We have a beautiful UI that we built on http://api.onename.com for FAQ's/documentation.

Let's integrate that UI from api.onename.com into blockstack.org so that we can finally have a nice UI that is nice to visit on all devices.

**Comment by estermer** [comment]
I will be point for this 👍

**Comment by estermer** [comment]
So I had a question about the layout for this, were you thinking of keeping the column where the code is shown in the FAQ page because there is no code examples in the current FAQ's, unless you were thinking of mixing the docs page with the FAQ's?

**Comment by guylepage3** [comment]
>I will be point for this 👍

Super awesome @estermer! 

@shea256 can we officially add @estermer to the contributors list so that we may assign him issues directly?

**Comment by guylepage3** [comment]
>So I had a question about the layout for this, were you thinking of keeping the column where the code is shown in the FAQ page because there is no code examples in the current FAQ's, unless you were thinking of mixing the docs page with the FAQ's?

Let's remove the "code" column and expand the middle column. Then let's set the two columns as a 30%/70% width on the `@media` query `Small devices (tablets, 768px and up)`. That should look nice.

Let's have you take a stab at adjusting the type, logo, colors and design as well by creating a new artboard for the page inside the blockstack.org sketch file. Time to dog food some of our design contribution guidelines. :)

>Another question is what is the path for this going to be like? will it be a subdomain like onename or just a path like the current FAQ's page?

Let's keep the URL the same as what we currently have for the FAQ's page.

**Comment by estermer** [comment]
@guylepage3 I am getting close to getting the FAQ page down, I just wanna make sure this ticket is also calling for the docs page as well.

**Comment by guylepage3** [comment]
@estermer how do you mean the docs page as well?

**Comment by estermer** [comment]
the page with the path '/docs' has this has a nice sidebar for navigation of the documentation for the browser, cli and explorer, but it is not positioned very well.

**Comment by estermer** [comment]
btw here are some pictures of what is currently in progress

Here It shows the sidebar with the footer displayed in the content container with the FAQ's
<img width="1440" alt="screen shot 2017-09-12 at 9 42 58 pm" src="https://user-images.githubusercontent.com/17515551/30355802-894f4756-9803-11e7-9f81-c4f46d646bd5.png">

Here is the content with the hovering colors over the list item in the sidebar

<img width="1200" alt="screen shot 2017-09-12 at 9 42 33 pm" src="https://user-images.githubusercontent.com/17515551/30355805-90d84572-9803-11e7-9eb5-26824d252de3.png">

Here is what happens when the width goes below 768px the sidebar just disappears and the content and footer take up the full width.

<img width="746" alt="screen shot 2017-09-12 at 9 46 56 pm" src="https://user-images.githubusercontent.com/17515551/30355897-1c2655c4-9804-11e7-9431-c2d67018d943.png">

**Comment by guylepage3** [comment]
@estermer this is great to see! This will be a huge improvement.

I would consider wrapping everything into a container similar to what the folks over at Stripe have done.

https://stripe.com/docs
<img width="1702" alt="screenshot 2017-09-13 12 04 21" src="https://user-images.githubusercontent.com/1711854/30387890-ffb8cc64-987b-11e7-9604-9a2a69619990.png">

Also, let's keep all styling the same to what we see on api.oneneame.com. Once we are happy with how that looks we will then start restyling to fit the brand.

>We have a beautiful UI that we built on http://api.onename.com for FAQ's/documentation.
>the page with the path '/docs' has this has a nice sidebar for navigation of the documentation for the browser, cli and explorer, but it is not positioned very well.

Yes. but let's finish up the FAQ's first before moving over. 👍

**Comment by guylepage3** [comment]
So @estermer let's just go with this for now..

![screenshot-2017-09-15-12 05 07](https://user-images.githubusercontent.com/1711854/30492534-d8d1d9b2-9a0e-11e7-9d19-a8d50a9c57ca.jpg)

Let's replicate what we see above with the following changes.

- [ ] `font-size` same as api.onename.com
- [ ] change `font` to lato
- [ ] change `font-color` to our chosen `body` font color
- [ ] change buttons to be Blockstack buttons

once this is complete, lets review before merging it in. 

Great work so far by the way.. LOVING it. 👍

**Comment by estermer** [comment]
Here is the list of FAQ's if we can pick a top 5 and categorize them @shea256 @muneeb-ali:

What is Blockstack?
What is a Blockstack ID?
What is a decentralized internet?
What problems does Blockstack solve?
What opportunities does Blockstack enable?
What is a "serverless" app?
What is a "decentralized" app?
Who should build on Blockstack?
How are Blockstack domains different from normal DNS domains?
What is Blockstack Core and who is working on it?
What is a virtual chain?
What's the difference between Onename and Blockstack?
How is Blockstack different from Namecoin?
I heard you guys were on Namecoin, what blockchain do you use now?
How is Blockstack different from Ethereum for building decentralized apps?
Can Blockstack only run on Bitcoin?
Does Blockstack use a DHT (Distributed Hash Table)?
Can the Blockstack network fork?
How is the Blockstack network upgraded over time? What parties need to agree on an upgrade?
Can miners take down Blockstack?
How many public Blockstack nodes are there?
Who gets the registration fees for name registrations?
How long has the project been around? What does the current development roadmap look like?
Who started the project? Who maintains it?
Where are the current core developers based? What are the requirements for being a core developer?
I heard some companies working on Blockstack have raised venture capital, how does that impact the project?
Can Blockstack control my data or ID when I use it?
How long can I own my Blockstack ID?
Where is my data stored and how do I control who access it?
Why should I trust the information, like name ownership or public key mappings, read from Blockstack?
Can anyone register a TLD?
Do apps using Blockstack work with a regular browser?
Where can I discover apps using Blockstack?
What programming language can I use to build these apps?
What is the Blockstack Portal?
How can I use the Blockstack CLI?
How do I get started using Blockstack to build apps?
Do I need to run a full Blockstack node to use Blockstack?
What is the capacity per block for registrations using Blockstack?
What language is the Blockstack software written in?
What incentives are there to run a Blockstack node?
How does Blockstack perform against building apps on Heroku or AWS?
Can Blockstack apps scale, given that Blockstack uses blockchains which don't scale that well?
What if the current companies and developers working on Blockstack disappear, would the network keep running?
What are the business models for companies working on Blockstack?

**Comment by guylepage3** [comment]
@estermer can you make a quick recommendation of category names for @shea256 @muneeb-ali?

**Comment by estermer** [comment]
we could do 3 main categories with these suggested sub categories:
- For Developers
  - Blockstack tools
  - App Development
  - Technical Specs
- For Users
  - Identification
  - Browser
  - Storage
- Misc

What do you guys think @guylepage3 @shea256 @muneeb-ali?

**Comment by guylepage3** [comment]
this is a great start @estermer 👍  can you recommend the top 5 as well?

maybe add in a "Token" main category as that is a category that we receive a lot of questions about.

**Comment by estermer** [comment]
Top 5 i think should probably come from:

What is Blockstack?
What is a Blockstack ID?
What is a decentralized internet?
What problems does Blockstack solve?
What opportunities does Blockstack enable?
What is a "serverless" app?
What is a "decentralized" app?
Who should build on Blockstack?

If we want, we don't have to choose 5. We could do all 8?

- For Developers
  - Blockstack tools
  - App Development
  - Technical Specs
  - Token
- For Users
  - Identification
  - Browser
  - Storage
- Misc

**Comment by guylepage3** [comment]
Awesome! Maybe let's go with something like this? 

@shea256 @muneeb-ali what are your thoughts?

What is Blockstack?
What is a Blockstack ID?
What is a decentralized internet?
What problems does Blockstack solve?
What opportunities does Blockstack enable?
Who should build on Blockstack?

- Token
- For Developers
  - Blockstack tools
  - App Development
  - Technical Specs
  - Token
- For Users
  - Identification
  - Browser
  - Storage
- Misc

**Comment by estermer** [comment]
@guylepage3 I know you said to match the content container to the width of the  https://stripe.com/docs but with a sidebar that is 220px wide it leaves a lot of white space.

<img width="1911" alt="screen shot 2017-09-25 at 11 21 33 am" src="https://user-images.githubusercontent.com/17515551/30816351-c38fde3c-a1e3-11e7-9727-5fcaa6ea2735.png">

What do you propose?

**Comment by guylepage3** [comment]
we have the solution above... https://github.com/blockstack/blockstack.org/issues/380#issuecomment-329827933

**Comment by guylepage3** [comment]
also the stripe example

**Comment by estermer** [comment]
OOOOOOOh  K! haha

now that i understand what you were referring to, here is the update with the strip solution

<img width="1917" alt="screen shot 2017-09-25 at 12 10 59 pm" src="https://user-images.githubusercontent.com/17515551/30818858-c3aa7bbe-a1ea-11e7-8f31-d366e701b426.png">

**Comment by guylepage3** [comment]
YES!!!!!!!! 💥 This is awesome! Whoot!!!

**Comment by muneeb-ali** [comment]
+1 for having categories. I can edit what the categories are and what questions should go in. Questions for the token should definitely be there.

**Comment by guylepage3** [comment]
Great work on this @estermer. if you could create a pull request for this on `feature/bootstrap` that would be super awesome sir. :)

**Comment by guylepage3** [comment]
closing this issue
