### ISSUE TITLE
resolve spacing issue on funding hero

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#381]
Resolve spacing issue on the funding hero below the apply here button as the button has no whitespace and gets lost.

Resolve by adding more margin-bottom spacing below button.

<img width="1313" alt="screenshot 2017-08-31 11 29 13" src="https://user-images.githubusercontent.com/1711854/29931673-ddf31738-8e3f-11e7-973d-91f9ac8060df.png">

**Comment by pstan26** [comment]
Assuming we also want to tighten up margin on stripe below hero?

**Comment by guylepage3** [comment]
>Assuming we also want to tighten up margin on stripe below hero?

There is another issue for that open

**Comment by brettdewoody** [comment]
@guylepage3 Appears this issue can be closed - more margin has been added - https://blockstack.org/funding

<img width="1440" alt="blockstack381" src="https://user-images.githubusercontent.com/409070/33986876-40480976-e0bf-11e7-80c7-7dc3536fc4b6.png">
