### ISSUE TITLE
reduce btn width on funding hero

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#382]
Reduce the width of the apply here button on the hero section of the funding page.

<img width="1313" alt="screenshot 2017-08-31 11 29 13" src="https://user-images.githubusercontent.com/1711854/29931715-009a022e-8e40-11e7-92f0-1360890fe76b.png">

**Comment by brettdewoody** [comment]
@guylepage3 This issue can be closed - https://blockstack.org/funding 

<img width="1440" alt="blockstack382" src="https://user-images.githubusercontent.com/409070/33986785-efe4d8ce-e0be-11e7-96f1-daadcd28df6d.png">

**Comment by guylepage3** [comment]
Thanks for catching that this issue was complete @brettdewoody
