### ISSUE TITLE
Broken nav links in tutorial pages

### ISSUE THREAD

**Issue by dhealy05** [blockstack/blockstack.org#386]
The tutorial pages' (https://blockstack.org/tutorials/todo-list, https://blockstack.org/tutorials/hello-blockstack, https://blockstack.org/tutorials/cli-basics) nav bar links don't work. I can see the address in my browser but it does not trigger navigation. Tried on Chrome and Safari.

**Comment by guylepage3** [comment]
Hey @larrysalibra this is an urgent issue.. Can you take a look at it?
