### ISSUE TITLE
Fix Logo Sizing in Footer

### ISSUE THREAD

**Issue by estermer** [blockstack/blockstack.org#387]
In the footer when you resize the width, from 974px-992px the brand logo in the footer sizes funky.

<img width="942" alt="screen shot 2017-09-11 at 11 46 51 am" src="https://user-images.githubusercontent.com/17515551/30283818-2df52942-96e7-11e7-9586-bee2742cfe3b.png">

**Comment by estermer** [comment]
I submitted a PR: #389

**Comment by guylepage3** [comment]
Oh. Whoa. Thanks for this @estermer. Great catch!

This is one of those `blockstack-bootstrap` issues that we will resolve in switching over to the latest stable version,v4.0.0-beta, of [Bootstrap](http://getbootstrap.com/).
