### ISSUE TITLE
Story: improve blockstack.org update process

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack.org#388]
As a team member or community member, it should be easy for me to make small changes to the website and get them review for push to production.

**Comment by larrysalibra** [comment]
I see two general areas that we can improve:

* Technical process
* Coordination process

# Technical process

## Problem
To make changes to the website and see the results, you need to:
* have a working node development environment. 
* to download and install approximately 750 megabytes of dependencies. 
* have a decent amount of experience with node, npm and javascript stack to get it up and running locally
* understand which commit is currently deployed to production
* run `npm run prod` to build a production copy - it's easy to commit a change, view it locally and forgot to rebuild the production build before pushing to firebase, inadvertently deploying an old version missing the commit you were trying to include
* upload the (currently 60 megabyte) result to firebase - this can take on the order of minutes when the connection to firebase's upload endpoint is slow (happens to me!)

## Proposed solution

Switch from firebase to a system that supports continuous deployment from github. Each commit and pull request should automatically generate a deploy to a unique preview URL so that the contributor can see what the deployed version of the site including their changes looks like without having to fiddle with building it locally. Automatically deploy production from the `master` branch so that it is always clear which code is live.

[Netlify](https://www.netlify.com) is a service that provides such a solution. I've already set it up to provide automatic builds for commits and pull requests. I've also temporarily set up a domain (https://blockstack.org.appartisan.com) as the production deploy location so that we can try out performance before making the switch.

To finish implementing this, we would need to
* port the firebase specific server config over (including rewrites/redirects) 
* update the DNS of blockstack.org to point to the right location ( @shea256 would need to do this)

 # Coordination process (notes coming after dinner!)

**Comment by larrysalibra** [comment]
Would love your feedback: @shea256 @muneeb-ali @guylepage3 @pstan26

**Comment by estermer** [comment]
This is actually a great idea. I noticed a little lag in the contribution process, which was why @guylepage3 and I were working on some guidelines to where it made it a little more clear who was in charge of merging to the develop branch and when that gets merged to master for production deployment. Also, in the case of the technical process... YEEEESSSSSS! haha
If learning how to code has taught me anything, development environment setup is sometimes harder than writing the code. Not that I should't learn more complex setup's but as a contributor, it is nice to not have to waste time with set up for sure.

Looking forward to the feedback on this.

**Comment by guylepage3** [comment]
I'm 100% behind this @larrysalibra. Great work on picking up the ball on this. It's been a very big problem with our website since we stopped using Firebase to deploy back in late 2015.

>It isn't clear who "owns" the website - who makes the final decision as to what is included or excluded - and how frequently updates should be made.

Very true. @estermer has done a great job creating our ["Contribution guidelines"](https://github.com/blockstack/blockstack.org/blob/master/CONTRIBUTING.md) but it should be clear directly on the README.md, who is the owner. Having said that, I've discussed things with @shea256 that I will take ownership of blockstack.org and the browser. I will need assistance from time-to-time with certain items but if I am the designated owner I will schedule things with either @larrysalibra or @yknl once we've implemented this new process.

>Assign someone as owner of the website. This person is responsible for making judgement calls as to what contributions should be included or excluded and to deploy updates.

>In the absence of a specific sprint user story that requires updating the website at a specific time (the announcement of the signature fund fund would have been such a story) or a critical issue, PRs and small fixes should be reviewed and pushed to production once a week.

>More complicated potential changes or changes that require the input of multiple stakeholders should be raised for discussion during the weekly sprint meeting and assigned as a user story (this issue would be an example of one that should be a sprint user story: #350)

Yes to all of these.

Great work here @larrysalibra

**Comment by larrysalibra** [comment]
We've come to agreement on process...all that is remaining is to implement it.

**Comment by shea256** [comment]
+1 on Netlify.

+1 on choosing a point person for deployment. @larrysalibra let's assign that to you.

**Comment by guylepage3** [comment]
>+1 on Netlify.
>+1 on choosing a point person for deployment. 
>@larrysalibra let's assign that to you.

👍

**Comment by larrysalibra** [comment]
We're going to hold off on the technical changes until after the token sale.

With regards to the organization process, I'm the person that you should bother to make a deployment. I'll plan to review pull requests etc on fridays and deploy or mark for further discussion on the following monday weekly meeting.

Outside of regularly weekly deployments, please loop me in when a deployment needs to be made before a deadline. Changes for the deadline should be complete by the end of business day (6pm NYC time) the day before they need to go live.
