### ISSUE TITLE
add closing issues via pull request to contribution guide

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#394]
One thing that we should add to our contribution guide is that the contributor should include a reference to the issue they are resolving in their commit message. This will assist the repository owner with merges.

See https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by guylepage3** [comment]
@estermer do you want to take this one?

**Comment by estermer** [comment]
on it

**Comment by guylepage3** [comment]
Whoa. this has brought something else to my attention. the `README.md` should be better organized. We should have a TLDR or **Quickstart to Contributing** in the `CONTRIBUTING.md` guide itself and less on the `README.md`.

So we should take what we have on the README.md for contributing and put it into the top of CONTRIBUTING.md with a dividing line underneath.

I'll make a quick edit to the README.md once this is complete. See #397

**Comment by nickthetait** [comment]
I think this issue can be closed now
