### ISSUE TITLE
Story: Security reviews: public facing web properties

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack.org#395]

**Comment by shea256** [comment]
Here are some firms we can try for this:

- liftsecurity.io
- binaryedge.io
- cure53.de
- recurity-labs.com
- sakurity.com
- github.com/stacktitan
- https://www.carvesystems.com/

**Comment by shea256** [comment]
@pstan26 Just introduced you to securisea.com.

Muneeb sent an intro to an Amazon security engineer as well.

The intro I made yesterday was to r10n.com for overall security assessments.

**Comment by shea256** [comment]
We're meeting with Josh tomorrow.

**Comment by shea256** [comment]
Security reviews on track:

- Securisea
- Ryan Lackey

@pstan26 please confirm on these and whether we're missing any others:

- Ryan McGeehan
- Danial Ranjha

Thanks!

**Comment by shea256** [comment]
Ah I just realized there are two stories for this.

Thinking we can merge this one and https://github.com/blockstack/blockstack/issues/350 to make logging simpler.
