### ISSUE TITLE
UI styling on new Press Page 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack.org#408]
Links : [https://docs.google.com/document/d/1HcDIX5EEuGQGgGVHABWbvzbQM-QHEAlbQZ3B9MFgUkI/edit?usp=sharing](url)

**Comment by GinaAbrams** [comment]
[IB Times.eps.zip](https://github.com/blockstack/blockstack.org/files/1325988/IB.Times.eps.zip)
[NASDAQ.eps.zip](https://github.com/blockstack/blockstack.org/files/1325989/NASDAQ.eps.zip)
[techcrunch.ai.zip](https://github.com/blockstack/blockstack.org/files/1325990/techcrunch.ai.zip)
[Forbes_com.eps.zip](https://github.com/blockstack/blockstack.org/files/1325991/Forbes_com.eps.zip)
[The_Observer_Advertising.eps.zip](https://github.com/blockstack/blockstack.org/files/1325992/The_Observer_Advertising.eps.zip)
[Wall_Street_Journal.eps.zip](https://github.com/blockstack/blockstack.org/files/1325993/Wall_Street_Journal.eps.zip)
[MIT Tech Review logo.zip](https://github.com/blockstack/blockstack.org/files/1325995/MIT.Tech.Review.logo.zip)
[BITCOIN MAGAZINE.zip](https://github.com/blockstack/blockstack.org/files/1325996/BITCOIN.MAGAZINE.zip)

**Comment by guylepage3** [comment]
Thanks for this @ginaabrams. This is a big help. 🙂

**Comment by GinaAbrams** [comment]
[Google Doc with Links to Articles](https://docs.google.com/document/d/1HcDIX5EEuGQGgGVHABWbvzbQM-QHEAlbQZ3B9MFgUkI/edit)

**Comment by guylepage3** [comment]
Update styling for https://blockstack.org/press

**Comment by guylepage3** [comment]
Reassigning to @yknl
