### ISSUE TITLE
Integrate ui from api.onename.com to Docs page

### ISSUE THREAD

**Issue by estermer** [blockstack/blockstack.org#413]
This is a relative issue to #380. So far the changes for the FAQ page have been submitted in this PR #412.

reference layouts:
- [api.onename.com](api.onename.com) (main layout)
- [stripe.com/docs](stripe.com/docs) (just for helper solutions)

@guylepage3 is there any additional features you would like?

I can see us wanting the black code segments, but also i can foresee there being a lack of space on the sidebar for all the potential links needed for the docs page like we ran into with the FAQ page. This may need a reorganizing of the Docs page content. What do you think @guylepage3 @larrysalibra @muneeb-ali @shea256 @pstan26?

**Comment by guylepage3** [comment]
Thanks for bringing that up @estermer. We will need the `code` section for the Docs. Do you have time to work on that today?

**Comment by estermer** [comment]
I can work on that today.

**Comment by guylepage3** [comment]
Awesome! :)

**Comment by estermer** [comment]
how does this look so far?

<img width="1482" alt="screen shot 2017-09-26 at 2 45 43 pm" src="https://user-images.githubusercontent.com/17515551/30877971-7a5610b0-a2c9-11e7-82ee-3e0f74ea6c78.png">

**Comment by guylepage3** [comment]
This is awesome @estermer!! 💥 A super GREAT start.. Let's go with this for today and add to it at a later date. 😄

**Comment by guylepage3** [comment]
The latest version of FAQ and Docs.. 😄 

<img width="1677" alt="screenshot 2017-09-29 07 43 06" src="https://user-images.githubusercontent.com/1711854/31019697-8ba10b36-a4fe-11e7-9fe4-bc5d4cb76e79.png">

**Comment by guylepage3** [comment]
Closing
