### ISSUE TITLE
Add Explorer Tutorial to /tutorials page

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack.org#414]
Here is the new Explorer Tutorial: https://youtu.be/xvclSzG1CyY

If this video needs its own page, the copy that can live below it is:

`In this video you'll learn how to use Blockstack Explorer and take your first step on the new decentralized internet. This tutorial is designed for anyone, and all you need is an internet connection and a web browser.  Check out explorer.blockstack.org`

Thank you!

**Comment by brettdewoody** [comment]
@guylepage3 The two other tutorial videos have detailed text walkthroughs, like [this one](https://blockstack.org/tutorials/hello-blockstack). Does this content exist already? Or need to be created? 

Also, is there a template file for creating the video thumbnails, like [this one](https://blockstack.org/images/tutorials/todo-list.png)?

**Comment by guylepage3** [comment]
>Does this content exist already? Or need to be created?

@brettdewoody it would need to be created.

>Also, is there a template file for creating the video thumbnails, like this one?

Not really. Those are one off's.
