### ISSUE TITLE
Build UI placeholder image for Reason TV video home page

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#416]
Build UI placeholder image for Reason TV video that will appear on the home page

**Comment by guylepage3** [comment]
See https://codepen.io/hugsbrugs/pen/WQdOBe for example on how to build this out.

**Comment by guylepage3** [comment]
Screen shot generator.. http://www.youtubescreenshot.com/

**Comment by guylepage3** [comment]
<img width="1920" alt="screenshot 2017-09-26 18 39 29" src="https://user-images.githubusercontent.com/1711854/30887617-20a5a9ce-a2ea-11e7-9ebb-ff364e0c891b.png">

**Comment by guylepage3** [comment]
![reason-tv-video-placeholder](https://user-images.githubusercontent.com/1711854/31099617-9f48244c-a794-11e7-84f7-5f0d15c7e27e.jpg)

**Comment by shea256** [comment]
@guylepage3 We're trying to work with an image that doesn't feature either myself or Muneeb. Let's run through a few options here. It should evoke "blockstack" more than anything.

**Comment by guylepage3** [comment]
Gotcha.

**Comment by guylepage3** [comment]
@yknl can you give this a go? looks like it will take a little bit of javascript magic to be able to execute this.

Here's a like to a site that generates the javascript required execute our goals.
- https://codegena.com/generator/Youtube-Embed-Code-Generator

**Comment by yknl** [comment]
@guylepage3 I added a custom preview image property to the embed video component.

**Comment by guylepage3** [comment]
Thank you @yknl.. Hope that wasn't to much trouble. Thought I could execute it via pseudo selectors but turned out I wouldn't go for me. Thanks again.

**Comment by guylepage3** [comment]
complete.
