### ISSUE TITLE
Build in sticky video embed into tutorial items

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#428]
Build in sticky video embed into tutorial items

![tutorial-mini-video](https://user-images.githubusercontent.com/1711854/31035516-503d1b42-a536-11e7-9e9c-f42bd09c10ed.png)

**Comment by guylepage3** [comment]
@pstan26 check it out..

**Comment by pstan26** [comment]
@guylepage3 looks cool -- would it make sense to translate the text tutorial to the left and expanding the video?

**Comment by guylepage3** [comment]
Like this..

<img width="1920" alt="screenshot 2017-09-29 17 12 37" src="https://user-images.githubusercontent.com/1711854/31036281-6f58dd2e-a539-11e7-9bec-b814bf2b3731.png">

**Comment by guylepage3** [comment]
I suppose it depends on what the user prefers.. text over video.. I actually kind of like having a smaller video with the text there larger. reason being is that I can always just scroll to the top, watch the video in full and then scroll down and use the video as a quick reference that can expand full screen.

**Comment by guylepage3** [comment]
example here: http://www.htmlgoodies.com/html5/other/theres-more-than-one-way-to-play-embedded-youtube-videos.html
