### ISSUE TITLE
Build new multi-video player functionality

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#434]
Reference: - [#433: Live design new multi-video player for all 4 views](https://github.com/blockstack/blockstack.org/issues/433)

@yknl Can you assist with JS functionality of building out the new video section functionality as a **NEW** component?

### Description
There will be a main large video frame where videos play. There will be 3 small video thumbnails/links that will appear underneath the "Main" large video. 

```
@guylepage3 to build a static version of the new video section prior to @yknl building
```

### Work flow
**1. Default initial view**
- When the user lands on the home page they see the default Reason TV pic image of both ryan and muneeb in the main large video player frame view with the first small video thumbnail/link active state on.

**2. User clicks to view a video**
- When the user clicks on any of the small video thumbnail/links the main large video player frame starts playing the corresponding video to small video thumbnail.
    - The small video thumbnail/link becomes an active state.

NOTE: Please do not delete the current version of the `EmbedYouTube.js` component as I would like to use that component in the future.

**Comment by yknl** [comment]
Sounds good, I will proceed with the JS functionality when the static version is done.

**Comment by guylepage3** [comment]
Thank you sir.

**Comment by guylepage3** [comment]
@yknl I've finalized all interactive `:hover` states as well as `:active` states for the new home page video section. Please have a look and let me know if you have any questions. I will be going to bed at 10pm and will be up again at 4am.

<img width="858" alt="screenshot 2017-10-05 21 25 31" src="https://user-images.githubusercontent.com/1711854/31259355-0f493372-aa14-11e7-887d-3b951c070abf.png">

Please follow the instructions in the initial comment of this issue for the build. Thank you sir.

**Comment by guylepage3** [comment]
Please pull from the `feature/multi-video` branch.

**Comment by yknl** [comment]
@guylepage3 Checkout the new multi video player component on the home page. (Pull latest from `feature/multi-video` branch) 

I put up 2 placeholder videos there. You can change the `this.state.videos` array in the home page to set the videos being shown. The `thumbnailImageUrl` property determines the image shown in the thumbnails, whereas the `previewImageUrl` is what's shown in the large preview format. The first video in the array is the default enlarged video. 

Let me know of any other changes we need in the morning.

**Comment by guylepage3** [comment]
Great job on this new multi-video player @yknl! 😄  And thank you for making it a new component. Works very well. 

Did you test it out on mobile?

**Comment by guylepage3** [comment]
great work again @yknl. closing this issue. :)
