### ISSUE TITLE
Add Ken to About page

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#442]
Hey @yknl can you add yourself to the https://blockstack.org/about page?

**Comment by yknl** [comment]
Will do

**Comment by guylepage3** [comment]
@yknl can you write a quick bio with roughly the same word count as everyone else's that are on the About page and place it here for @shea256 to review? Thank you sir.

**Comment by yknl** [comment]
Let me know if this is good.

Ken Liao studied Computer Engineering at the University of Waterloo and co-founded the fashion brand marketplace, PR-A-PO. He designed and built mobile apps which were featured as Best New App on the Apple App Store.

**Comment by guylepage3** [comment]
@yknl what's your blockstack id?

**Comment by yknl** [comment]
My Blockstack ID is yukan.id

**Comment by brettdewoody** [comment]
@guylepage3 Ken's bio is already on the [About page](https://blockstack.org/about), this issue can be closed.
