### ISSUE TITLE
Update Patrick's bio on About page

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#443]
Update @pstan26's bio on the https://blockstack.org/about page

>Patrick Stanley studied Economics and Psychology at Johns Hopkins, and was the first employee at data-driven lending startup Earnest which sold to Navient for $155m in 2017. In a growth role there, he helped it scale from from 1 to 200 employees and go from $0 to $2B in originations within 3 years.

**Comment by larrysalibra** [comment]
Thanks to @brettdewoody this is complete!
