### ISSUE TITLE
Loader on blog seems odd

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#445]
Went on to a blog post and saw the loader image and was taken by it.. Would really like to see the simple loading content layout similar to how facebook loads content. A far better experience than a loading wheel.

![image](https://user-images.githubusercontent.com/1711854/31776205-e104fa32-b4b8-11e7-9a1f-ea9358c46658.png)

**Comment by guylepage3** [comment]
![image](https://user-images.githubusercontent.com/1711854/31776230-f3954dd2-b4b8-11e7-938f-99b2710494f4.png)

**Comment by estermer** [comment]
I agree with this.

We actually implemented this same thing in our app here at work because of the same exact reason.

**Comment by estermer** [comment]
<img width="803" alt="screen shot 2017-11-17 at 10 56 03 am" src="https://user-images.githubusercontent.com/17515551/32956133-f59d314c-cb85-11e7-8dd7-4732e205e0ff.png">

**Comment by guylepage3** [comment]
Nice! @estermer. How difficult was it?

**Comment by estermer** [comment]
this really wasn't difficult, just created a quick component and displayed it under the same conditions you would display a loading wheel.

**Comment by estermer** [comment]
How bout this @guylepage3 ?

<img width="1422" alt="screen shot 2018-01-04 at 12 14 23 am" src="https://user-images.githubusercontent.com/17515551/34575320-4e6f71e4-f148-11e7-8e14-81b6631326de.png">
