### ISSUE TITLE
Add Bounties section to Funding page

### ISSUE THREAD

**Issue by estermer** [blockstack/blockstack.org#448]

**Comment by guylepage3** [comment]
@pstan26 can you provide @estermer with some requirements when you get a moment? S'il vous plaît.

**Comment by pstan26** [comment]
yes indeed. @estermer would love to get this section in before Nov 1:

right below the text screencapped here, I'd love to add a slim section in the same stripe with the following details:

Small headline: *Current and past Signature Bounties*        *Submission Deadline*
Bounty list: [*Encrypted Token Portfolio App*](tokenportfolio.eventbrite.com)  Dec 1, 2017

**Comment by estermer** [comment]
@pstan26 did you forget to add the screen capture?

**Comment by pstan26** [comment]
![screen shot 2017-10-25 at 12 15 52 pm](https://user-images.githubusercontent.com/5605552/32014987-b7f95258-b98d-11e7-930e-d6da08a3b8b8.png) yerp, also feel free to provide suggestions on how/if this could be done better
Thanks Eric

**Comment by guylepage3** [comment]
How's this coming along @estermer @pstan26 ?

**Comment by estermer** [comment]
@pstan26 so something like this?

<img width="1393" alt="screen shot 2017-10-26 at 9 08 27 am" src="https://user-images.githubusercontent.com/17515551/32054695-4bcd767c-ba2d-11e7-9627-e642a162e553.png">

BTW do you know how many bounties you are expecting to have? should the list be in a container that has an over flow on it when the list is getting larger? or will something like this do for now?

AND the link you used in your comment above is not working, would you mind providing the working one?
