### ISSUE TITLE
Registration step requested insufficient amount

### ISSUE THREAD

**Issue by maddo** [blockstack/blockstack.org#449]
Saw this message after choosing my id:
```
Buy *********.id
Send at least 0.001 bitcoins to your wallet:
1BYNqxHANdJQgi3FwVXNP7SiMr1fuDAPMK
```

Sent `.001` to wallet, then got stuck on "Buying" screen. Console says:

```
2017-10-23T16:47:41.747-0400 ERROR profiles/store/registration/actions.js: register failed.
Address 1BYNqxHANdJQgi3FwVXNP7SiMr1fuDAPMK does not have enough balance (need 125460, have 100000).
```
I see I can fix this by adding more bitcoin to my wallet, but for reasons unrelated, that's difficult to do and knowing the right amount initially would have been better!

Cheers

**Comment by maddo** [comment]
Hello! Why was this closed?

**Comment by jeffdomke** [comment]
Hi Maddo. Sorry, I closed all the old tickets here because we just replaced the entire site. This particular issue isn't related to this repo. I can move it for you, or you can start a new one in: https://github.com/blockstack/blockstack-browser/issues sorry for the confusion.
