### ISSUE TITLE
Update "About" content on blockstack.org

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack.org#457]
See this [issue](https://github.com/blockstackinc/tokensale/issues/80)

@shea256 @muneeb-ali are we good to go with the paper doc content? 🙂 

cc: @guylepage3 @larrysalibra

**Comment by guylepage3** [comment]
>paper doc content?

@GinaAbrams Can you provide a bit more of a description as to which doc that is? Thank you.

**Comment by GinaAbrams** [comment]
yeah, its linked in the issue referenced above. Title in Paper docs: Blockstack.org About Content

**Comment by guylepage3** [comment]
Ahh.. gotcha the Papers section of the site. Correct?

**Comment by GinaAbrams** [comment]
Ah sorry I was unclear. This is what I meant 🙂 

[Dropbox Paper Content](https://paper.dropbox.com/doc/Blockstack.org-About-Content-55yjtSW9pin7Nigo6qQwr) for [about section](https://blockstack.org/about)

**Comment by guylepage3** [comment]
👍 [Blockstack.org About Page Content](https://paper.dropbox.com/doc/Blockstack.org-About-Page-Content-55yjtSW9pin7Nigo6qQwr) in Dropbox Paper.

**Comment by GinaAbrams** [comment]
@shea256 please confirm copy. Can we try to get this done by Tuesday 11/7? Do you think that's reasonable?
