### ISSUE TITLE
Reinstate the banner for the token sale and link to blockstack.com

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack.org#458]
Related to #398.

Marking this as high priority.

Tagging @guylepage3.

**Comment by estermer** [comment]
I may be able to tackle this

**Comment by guylepage3** [comment]
I’ll add the label

**Comment by guylepage3** [comment]
That would be awesome @estermer. Thank you sir.

**Comment by guylepage3** [comment]
on this now.

**Comment by guylepage3** [comment]
closing issue
