### ISSUE TITLE
Add countdown timer to banner

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#459]
Add countdown timer to banner.

@guylepage3 to build static version and @jackzampolin to implement timer automation.

**Comment by jackzampolin** [comment]
@guylepage3 I mentioned a couple of times, and I will mention again, I don't have the perms to do this. I could write the JS, but could not push live. You will need to get @yknl to help you with this

**Comment by guylepage3** [comment]
yes. i'll build it in a bit and then get @jackzampolin to build it and then get @yknl to push it live.

**Comment by guylepage3** [comment]
Issue is here.. https://github.com/blockstack/blockstack.org/issues/459

**Comment by guylepage3** [comment]
working on this now.

**Comment by guylepage3** [comment]
Current copy of blockstack.org banner
>Blockstack Token Sale Registration Now Open  ›  Register Now

@muneeb-ali What would you like the new banner say..
<img width="732" alt="screenshot 2017-11-08 11 01 32" src="https://user-images.githubusercontent.com/1711854/32559163-7b196868-c474-11e7-8a46-e97ece6ef29c.png">

**Comment by muneeb-ali** [comment]
3 days 01 hour

**Comment by guylepage3** [comment]
<img width="667" alt="screenshot 2017-11-08 11 43 28" src="https://user-images.githubusercontent.com/1711854/32561352-11dd2c6c-c47a-11e7-9a12-26a80017bd9d.png">

**Comment by guylepage3** [comment]
@yknl we're ready to apply some automation to this banner.
