### ISSUE TITLE
Can't scroll side menu in docs

### ISSUE THREAD

**Issue by dhealy05** [blockstack/blockstack.org#464]
The side menu at https://blockstack.org/docs/ doesn't scroll, there is content that doesn't show up. Using Chrome

**Comment by guylepage3** [comment]
👍 Thanks for the reminder on this one @dhealy05. Please note: you are still able to access all the content at the moment. But definitely something we should resolve.

**Comment by brettdewoody** [comment]
@guylepage3 This can be closed. 

Github doesn't seem to be autoclosing issues when the related PR (mentioning the issue) is merged.
