### ISSUE TITLE
Developer reviews section

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack.org#466]
Could be helpful to get developers over the hump by having quotes from other devs on how easy it is to use blockstack.

Near this section I could imagine a button leading to tutorials for auth & storage being convenient.

<img width="766" alt="screen shot 2017-11-27 at 10 17 12 am" src="https://user-images.githubusercontent.com/5605552/33273737-32197ac6-d35c-11e7-8e50-e0384eab0050.png">

Can provide the name of this dev once he gives me permission.

**Comment by cwackerfuss-rl** [comment]
Blockstack takes care of all your auth, storage, and encryption worries so you can just start building your app. We launched a fully fledged web app on top of Blockstack in only a month, and it's much safer and even faster than a traditional web app. The future of programming on the decentralized web is intuitive and the concepts map smoothly from centralized paradigms. Jump in and build something on Blockstack, you'll be surprised how easy it really is.

**Comment by cwackerfuss** [comment]
Blockstack takes care of all your auth, storage, and encryption worries so you can just start building your app. We launched a fully fledged web app on top of Blockstack in only a month, and it's much safer and even faster than a traditional web app. The future of programming on the decentralized web is intuitive and the concepts map smoothly from centralized paradigms. Jump in and build something on Blockstack, you'll be surprised how easy it really is.

**Comment by guylepage3** [comment]
>We launched a fully fledged web app on top of Blockstack in only a month

YES! 😄
