### ISSUE TITLE
Proposal: Separate entrance point for developers (developer.blockstack.org)

### ISSUE THREAD

**Issue by vsund** [blockstack/blockstack.org#474]
This issue of having two entrance points (one for users and one for developers) already was discussed some time ago, but back then was delayed because the main target group were developers. With the [consumer release](https://blockstack.org/blog/introducing-the-blockstack-browser-a-gateway-to-a-new-decentralized-internet) of the browser and especially the publicity of the token sale this became relevant again.

The current entrance page handles consumers and developers. Both groups obviously need fundamentally different arguments / have fundamentally different needs. Consumers want to know what's Blockstack (mostly Blockstack Browser) and why should they care, while developers want to know how to develop with Blockstack's software stack and why should they better do so.

Furthermore developers use this entrance point when searching for resources, problems, inspiration, and so on. In my opinion it would be extremely useful if we elevate such a new entrance point to a site where you can get to every available information (from open GitHub issues over finished apps to video tutorials). Currently all these things are scattered around (Github, website, forum, Slack, ...) and it's not easy to find the information needed.

---
A good example for how to design such a page is https://minio.io. They target only developers so it's their default front page. The first thing the visitor reads is the big headline of what Minio is, then the tag line with a little more information (telling *a developer* what Minio is and why one should care). The component below is a great showcase for directly getting introduced in available tech stacks and what's possible (you can even figure it out without reading a single word on the page). The "Features, Architecture, SDK and Tools" box is also very great (kind of self explanatory).
Additionally they have a single source for developer information at https://docs.minio.io.

Also a look worth: https://link.fish/api/ (great showcase) and their docs at https://api.link.fish/docs/ (completely built around their API specification, single place for important information).
(They use https://sourcey.com/spectacle/ for their documentation)

Also good: The code box at https://kloudless.com (shows you different code snippets for a selectable language).

**Comment by vsund** [comment]
cc @pstan26 @guylepage3

**Comment by vsund** [comment]
Topics such a developer portal would need (in my opinion):
* Short intro what Blockstack is and why a developer should care about
* A slightly deeper dive into how Blockstack works
  * Layers
  * Archticture
  * Design decisions
  * Security implications
* List of available libraries (and their state (heaving `go-blockstack` in mind, which has a slightly different target as `blockstack.js`)
* Link to other places of documentation
* Where to ask for help (see e.g. https://github.com/blockstack/blockstack/issues/377)
* Developer FAQs (common mistakes, questions but this time with developers as target group)
* Currently available bounties (generic and individual ones)

**Comment by jackzampolin** [comment]
I have some more thoughts here but the above list ☝️ should include a getting started with a new app experience.

**Comment by vsund** [comment]
Also some kind of "Blockstack 101" with common terms and components of the ecosystem would be useful. Saw this this week in another project (unfortunately can't remember where).

**Comment by mrjmd** [comment]
This list is great! I think prominently featuring a "Quickstart" is really important, as many developers want to get their hands dirty immediately, we should make it as straightforward for them to do so as possible.

Maybe a Quickstart section that is tabbed for different languages / frameworks (similar to how minio.io lets you tab through technology integrations) so that regardless of their familiarity with existing toolsets, they can pick what they're most comfortable with and dive in.

**Comment by guylepage3** [comment]
>https://github.com/blockstack/blockstack.org/issues/474#issue-281824201

This is great @vsund. I brought this up in our weekly meeting this past Monday. This is something we will more than likely keep on discussing as some of Blockstack core are in agreement. A few of us are on holidays until the new year but I will definitely keep bringing this up in our meetings.

>This list is great! I think prominently featuring a "Quickstart" is really important, as many developers want to get their hands dirty immediately, we should make it as straightforward for them to do so as possible.

@mrjmd this is something @shea256 and I had on the original blockstack.org. I am in total agreement here that there should be a "Quickstart" button/ section where developers can get up and running as quickly as possible. cc: @pstan26 @muneeb-ali @jackzampolin @larrysalibra @yknl

**Comment by nigoyal** [comment]
[Blockstack.pdf](https://github.com/blockstack/blockstack.org/files/1558736/Blockstack.pdf)
Attaching a file as the formatting gets lost if I paste here.

**Comment by vsund** [comment]
The consensus for this issue in Slack was to compile a few questions to asks what our developers expect from this. See below for possible questions, feedback welcome.

---
### Have you developed an app with Blockstack yet?

* Yes
* No, but plan to
* No, not planned


### If you have a problem while developing, where do you currently look for information?

* GitHub (at the respective repository)
* Google (as search for other resources, e.g. StackOverflow/GitHub)
* StackOverflow
* Forum (https://forum.blockstack.org)
* Slack (e.g. #support or #apps)
* Asking other developers / team
* Other: <text_field>


### What do you think of the current version of `blockstack.org` as frontpage for developers?

* <text_area>


### Should a potential developer portal (e.g. `developer.blockstack.org`) target new developers or active developers?

#### In other words: Should `developer.blockstack.org` be a portal for active developers or a site showcasing Blockstack?

* Only active developers, because <text_field>
* Only new developers, because <text_field>
* Both, because <text_field>


### What do you expect of a potential `developer.blockstack.org`?

* <text_area>


### Which components would you like to see?

* Quickstart (code examples for different situations and libraries)
* In-Depth tutorials (e.g. links to video tutorials etc.)
* Short intro into Blockstack
* Blockstack 101 (common components and concepts)
* A slightly deeper dive into how Blockstack works
* Links to other places with documentation
* FAQs for developers (common mistakes / questions / problems)
* Where to ask for help
* Currently available bounties
* Other: <text_field>


### Any other comments

* <text_area>

**Comment by jackzampolin** [comment]
Depending on the audience here we might want to reduce the number of text areas. Is this going to be given to a focus group after discussion? If so, we can expect more engagement from the survey takers, and the text areas are fine. If not we should eliminate the text areas and try to use the survey to find out which platforms/areas we should focus our work on first.

**Comment by vsund** [comment]
@jackzampolin That's a good point. I personally like the answers from free-text areas the most, because that's the point where new ideas come in (other answers are just a sign of preference).

But though, I'm happy with removing these (making them optional would work as a reasonable compromise I think).

**Comment by vsund** [comment]
Additionally: meeting notes?

**Comment by vsund** [comment]
@jackzampolin @pstan26 @guylepage3 and co. could you leave some feedback on the questions? :)

Happy to send this out this weekend 👍

**Comment by vsund** [comment]
Talked with @jackzampolin shortly about this. We'll wait with this until the team is completely present again in ~two weeks 👍

**Comment by muneeb-ali** [comment]
@vsund thanks a lot for the suggestion and ideas! 

In our general communication, we kinda need to cover both consumers and developers -- we understand that it's hard but other projects in this space face the same challenge as well. 

I love the idea of a dedicated place for developers in general but view it more as a resource for people who're looking for advanced info. It can be on the website or even just Github. Most non-technical people are not going to read things on Github and that can act as a filter to focus more on developers there.

The general communication is the larger funnel and more people will hit the general communication, so we need to really iron it out.

**Comment by shea256** [comment]
Yes I believe another option we discussed was blockstack.org/developer.

This conversation is a good one to have and definitely something we should mark for our future meetings around marketing, product, and communication.

**Comment by vsund** [comment]
Yeah, there are many single issues that need to be discussed, first of all whether we need such a page at all.

I would say that we definitely would benefit from an own page, because we can do things GitHub readmes (or in general markdown documents) cannot do. Furthermore it would be _the one place_ to search for information which links then to the repository and more detailed information. In my opinion especially the last part is very important and not to underestimate. Currently information are scattered over many pages (several repositories (markdown/html documents, issues), forum, website, Slack, blog posts / video tutorials). It's not really easy and fun for developers to find what they need. I think we have all we need, it's only not that easy to get to it.

Happy to get a little bit more structure into this, I guess this was a bit of a rush. Let's discuss first the need and concept and then moving to the survey.

**Comment by vsund** [comment]
I'd like to throw in https://angular.io/docs as a positive example for a "all in one" documentation for developers.
They provide a short tutorial which walks you through all important aspects of Angular in the style of a tour (and most important: They assure that it's up-to-date at every point).

Although that might already be enough for a new "How to best get people started" issue, it might be somehow related to this issue and important here too.

**Comment by jackzampolin** [comment]
I'm going to leave this earlier discussion on this topic here as well: https://github.com/blockstack/blockstack/issues/233

**Comment by guylepage3** [comment]
>I'd like to throw in https://angular.io/docs as a positive example for a "all in one" documentation for developers.

Much like @vsund has done, I don’t know the last time folks have run through the Heroku Node.js App setup process but WOW. Spectacular. The last time I ran through their “Get Started” documentation it was ok. But their latest version of it is spectacular. Would suggest everyone checking it out… https://www.heroku.com/

**Comment by vsund** [comment]
Also probably helpful: Blockstack's key concepts on different levels.

* Low-level stuff as:
  * Mutable / immutable / Atlas storage
  * The different layers
  * Core endpoints
  * Own namespaces
  * Name purchase process
  * etc
* High-level stuff as:
  * How to build apps with `blockstack.js` (tutorials)
  * How to debug decentralized apps
  * Usage of CompassDB (an similar libraries)
  * Concepts for decentralized apps (working without centralized server infrastructure)
  * etc

**Comment by vsund** [comment]
To not lose it in all my open tabs: I recently stumbled across https://www.mailgun.com. I really like their interpretation of a "multi-language box for trying out the library", imo the best one I currently know.

We'd definitely need such a box with being able to type in there with syntax highlighting (for the curl/JavaScript parts maybe even a "Run" button)
