### ISSUE TITLE
Change copy on https://blockstack.org/tutorials/todo-list

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack.org#477]
<img width="696" alt="screen shot 2017-12-18 at 5 23 12 pm" src="https://user-images.githubusercontent.com/5605552/34131106-4ab26148-e418-11e7-980a-91421d46a71a.png">

@larrysalibra is it safe to say folks don't need this since we automatically give them a non-human-readable string?

**Comment by jackzampolin** [comment]
https://github.com/blockstack/blockstack/pull/389

**Comment by larrysalibra** [comment]
Yep. Thanks Jack.
