### ISSUE TITLE
Add 4 new team members to About page 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack.org#482]
Please see content on: https://github.com/blockstackinc/blockstack-dot-com/issues/233

**Comment by GinaAbrams** [comment]
also please add Clint Nelsen 
[Twitter](https://twitter.com/clintnelsen)
[Github](clintnelsen)

**Comment by GinaAbrams** [comment]
@yknl could you potentially help out with this today? 🙏

**Comment by yknl** [comment]
Can we get a short bio for each member we want to add?

The current page looks like this:
![image](https://user-images.githubusercontent.com/29081231/35114383-80e92c36-fc52-11e7-9659-237517febef2.png)

**Comment by GinaAbrams** [comment]
ah yes good call. Will follow up once we have bios.

**Comment by shea256** [comment]
+1 Shannon, Xan and Sebastian

Same as the list found at https://coinlist.co/blockstack and formerly at blockstack.com

**Comment by GinaAbrams** [comment]
yep, included in the first comment with issue linked here. gathering bios now.
