### ISSUE TITLE
Add banner that links to Berlin event

### ISSUE THREAD

**Issue by pstan26** [blockstack/blockstack.org#483]
Copy for banner: _Attend "Blockstack Berlin" featuring Edward Snowden & Nick Szabo March 2nd_

event link for blockstack.org: https://blockstacksignatureberlin.eventbrite.com/?aff=blockstackorg
event link for blockstack.com: https://blockstacksignatureberlin.eventbrite.com/?aff=blockstackdotcom 

Thanks @guylepage3 !

**Comment by guylepage3** [comment]
@pstan26 should we include that nice image of the 4 presenters? I feel that will work best.

**Comment by pstan26** [comment]
@guylepage3 Oh I thought this would be similar dimensions to the Token banner i.e. just text. If we can somehow fit in the image of the 4 presenters nicely that could be cool..

**Comment by guylepage3** [comment]
@pstan26 We could make this banner as big as we made the 2015 Summit banner on desktop and that would allow for the visual which is quite powerful.

**Comment by pstan26** [comment]
Cool looks like you've done this before. Do you need the image or do you already have it?

**Comment by guylepage3** [comment]
Yes yes.. I am the one that does this. 😄 

If you could upload the image here that would be super helpful. Thank you.

**Comment by guylepage3** [comment]
![signatureberlin_twitter_11 6 17](https://user-images.githubusercontent.com/1711854/35013039-f860242e-fad9-11e7-8b98-42d9fcf18890.jpg)

**Comment by guylepage3** [comment]
Hey @yknl assigning this over to you.. Just waiting on approval for the design.

**Comment by shea256** [comment]
Let's do a banner that's similar to the token sale banner. Very thin, minimal, no photos.

**Comment by shea256** [comment]
cc @pstan26 @guylepage3

**Comment by guylepage3** [comment]
Sounds good. will whip this up.

**Comment by pstan26** [comment]
Sweet thanks!

**Comment by pstan26** [comment]
Thank you!

**Comment by guylepage3** [comment]
<img width="1437" alt="screen shot 2018-01-23 at 6 27 34 pm" src="https://user-images.githubusercontent.com/1711854/35306341-205ed902-006b-11e8-9c79-d093b0815ec1.png">

**Comment by guylepage3** [comment]
complete. @yknl can you push this live when you get a moment? it will assist with ticket sales. thank you sir.

**Comment by yknl** [comment]
hey @guylepage3 is this design only or is it living on a branch and ready to push live?

**Comment by guylepage3** [comment]
Hey @yknl, i just ended up doing a live design of it so it's ready to go live on `develop`.
