### ISSUE TITLE
Switch domain to netlify

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack.org#489]
I've already added the domain `blockstack.org` in netlify and set it to be the primary domain:

<img width="932" alt="screen shot 2018-01-24 at 4 10 10 pm" src="https://user-images.githubusercontent.com/597182/35321126-314f6b8a-0121-11e8-8217-598d086b97ca.png">

Since we use cloudflare and cloudflare offers support for CNAME flattening (and not ALIAS records), we'll want to add a CNAME for `blockstack.org` that points to `blockstack.netlify.com`.

<img width="773" alt="screen shot 2018-01-24 at 3 43 27 pm" src="https://user-images.githubusercontent.com/597182/35320912-76478494-0120-11e8-92aa-137ac35c8ee3.png">

We'll also want to add a CNAME for `www.blockstack.org` to `blockstack.netlify.com`

<img width="756" alt="screen shot 2018-01-24 at 4 10 04 pm" src="https://user-images.githubusercontent.com/597182/35321142-3f966c98-0121-11e8-9627-d4190719d82c.png">

Tagging @shea256 to make these changes.

**Comment by larrysalibra** [comment]
@shea256 we addressed the pages that were inaccessible in #490 - can switch DNS back to netlify at your convenience.

**Comment by larrysalibra** [comment]
@yknl @cwackerfuss @jeffdomke - i was trying to update the download links for the browser and the deployed site on firebase is out of sync with what's on master again.

@kantai can we change the DNS back to netlify so that we can stop running into the production site and master being out of sync problem? alternatively, if we want to keep using firebase we should set up circleci so that deploys are automatic.

**Comment by yknl** [comment]
I second the switch back to netlify.

**Comment by kantai** [comment]
I am happy to do this, but will want to coordinate with someone to check the site when the DNS change goes through, as I'm not in a position to verify that everything is working.

**Comment by aulneau** [comment]
+1

**Comment by aulneau** [comment]
May I make the request that when we switch over, we enable their prerendering service -> https://www.netlify.com/docs/prerendering/

**Comment by yknl** [comment]
> May I make the request that when we switch over, we enable their prerendering service -> https://www.netlify.com/docs/prerendering/

+1

**Comment by cwackerfuss** [comment]
+1

**Comment by kantai** [comment]
Switched to netlify!
