### ISSUE TITLE
Update home page featured apps

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack.org#495]
Update home page featured apps to be

- [x] Coins
- [x] Graphite
- [x] Casa
- [x] Afia
- [x] DotPodcast

**Comment by guylepage3** [comment]
Current layout.. 

<img width="1555" alt="screen shot 2018-01-31 at 12 25 55 pm" src="https://user-images.githubusercontent.com/1711854/35637354-f3ef407e-0681-11e8-812d-abfbc4b50321.png">

**Comment by guylepage3** [comment]
@shea256 @pstan26 @xanbots Can I get one of you to provide a writeup for Coins, Graphite and DotPodcast? Thank you. 👍

**Comment by xanbots** [comment]
@guylepage3 coins: “Coins is a decentralized and encrypted cryptocurrency portfolio app. Analyze your performance with flexible, customizable reporting. Track your holdings painlessly by syncing to your preferred exchanges. Watch your favorite tokens and optionally send pricing alerts."

**Comment by xanbots** [comment]
**Graphite**: “Graphite gives you ownership over your data and files. Write, create, connect—all without giving up your privacy.”

**Comment by xanbots** [comment]
**DotPodcast**: “DotPodcast helps creators get paid, protects against censorship, and allows listeners to enjoy podcasts without privacy-invading tracking.”

**Comment by guylepage3** [comment]
@xanbots There is a rough word count requirement for the app descriptions..

>Casa is the world's first open source homesharing protocol and decentralized network. Book rooms without platform fees or trusted intermediaries and securely transact with encrypted chat and multi-party escrow.

Otherwise we get wonky column heights on the website which makes is a bad user experience. Can you add to the Graphite and DotPodcast descriptions? Thank you. sir. 😄

**Comment by xanbots** [comment]
@guylepage3 FYI Casa has a new logo/description. For all intents and purposes should be considered a completely different app. Can add some more to the descriptions but that looks like a lot of text, and not sure we want to mandate a description has to be at least 3 lines of words. In some cases (like Casa) they have a great one liner that would be better to use.

**Comment by guylepage3** [comment]
>FYI Casa has a new logo/description. For all intents and purposes should be considered a completely different app

Cool. Can you provide copy and a new logo for that please sir.

> Can add some more to the descriptions but that looks like a lot of text, and not sure we want to mandate a description has to be at least 3 lines of words. In some cases (like Casa) they have a great one liner that would be better to use.

We can either add content or edit content.

Let me know which works for you. Thanks.

**Comment by xanbots** [comment]
New Casa logo 
![casaiconbig](https://user-images.githubusercontent.com/31934541/35706695-ba04c458-0774-11e8-8a5b-5a770face62e.png)

**Comment by guylepage3** [comment]
Thank you @xanbots I'll take a first stab at editing the copy for the page. 👍

**Comment by guylepage3** [comment]
complete
