### ISSUE TITLE
Improve tutorial onboarding traffic rates

### ISSUE THREAD

**Issue by cwackerfuss** [blockstack/blockstack.org#506]
We should tweak the blockstack.org experience so that we can get more developer users onboarded with the tutorial. Currently, our numbers are pretty weak in this department.

Can this problem be solved by putting a more prominent call to action onto the homepage to get users to navigate to the tutorial? Should we attempt to separate out content more with a "For Devs" homepage, where the tutorial link is featured prominently?

@clintnelsen @pstan26 please weigh in.

Lets shoot for decisions on the deliverable here in the next few days, and implementation done by mid next week.

**Comment by clintnelsen** [comment]
Hi Chase,

A few things we've been talking about:
- redirect blockstack.com to .org and add a page for the token sale.  People that land on blockstack.com have no place to go at the moment as it's just a token landing page.

A dedicated "For Devs" section would be ideal.  I like how Ethereum calls out there core functionality on their homepage.   https://www.ethereum.org
- What is blockstack 
- Install blockstack
- Authentication
- Data

Compare that to the sections on Ethereum's homepage.  They have four different tracks they walk users through based on what they are looking for and it's clear they are pretty much only speaking to developers on their page.  My vote would be we essentially mimic their approach and we can add more modules in the future.

**Comment by pstan26** [comment]
Yep, I posted an issue back in April which i think is still relevant re: how we could learn from Ethereum the project here.

CTA's all the way down targeted at Developers. I think we could do something similar to this.

> Ethereum actually does a decent job of providing context, possibilities and a call-to-action -- which feels very aligned with the developer journey when they hit their home page.

https://github.com/blockstack/blockstack.org/issues/259

**Comment by pstan26** [comment]
Woah...also theres no actual links to the tutorials where it says tutorials on the site right now:

<img width="1097" alt="screen shot 2018-02-14 at 6 01 07 pm" src="https://user-images.githubusercontent.com/5605552/36232813-3b3f491c-11b1-11e8-8a29-e2979538e1d0.png">

**Comment by jw2013** [comment]
Just came here as I tried to click on the code snippet in the new home page only to find out it is not clickable as @pstan26 already commented above.

Wondering if it is intentional or the video link would be available some time in the future? I just thought with this new homepage design already rolled out, later when the tutorial link is really added the user previously been to this page might never click again if there is no copy change as a new hint (as they thought nothing changed).

Just curious what is your guys' decision on this. Thank you!! :)
