### ISSUE TITLE
Update messaging on Blockstack.com

### ISSUE THREAD

**Issue by cwackerfuss** [blockstack/blockstack.org#507]
The messaging on blockstack.com is hardly useful to users -- we're currently just saying that the token sale has ended. Would love to see how many users are actually visiting this site still.

@pstan26 please feel free to supply traffic insights here on how often users are still navigating to blockstack.com.

Personally, I think it makes sense to just redirect blockstack.com traffic to blockstack.org. Unless there is a good reason why we'd want to use blockstack.com to fulfill another purpose. The other "redirect" option is to send blockstack.com traffic to a FAQ about the Blockstack token sale, hosted on blockstack.org

Thoughts @pstan26 and @clintnelsen 

Same with #506, lets shoot for decisions on the deliverable here in the next few days, and implementation done by mid next week.

**Comment by pstan26** [comment]
Blockstack.com gets 1,700 hits per week. I personally am leaning
toward the "redirect"
option to send blockstack.com traffic to a FAQ about the Blockstack token
sale, hosted on blockstack.org

Thanks Chase!

**Comment by cwackerfuss** [comment]
Agreed! I've also seen a lot of folks asking about the token sale in Slack.

Would a new page on the site be the best path for a Token FAQ?

I see we have: https://blockstack.org/blog/blockstack-token-sale-recap

So if we were to create a new page of content on the site for Token FAQ, we could extract FAQs from:
1. [The recap post](https://blockstack.org/blog/blockstack-token-sale-recap)
2. [Whitepaper Announcement](https://blockstack.org/blog/announcing-the-blockstack-token-whitepaper)
3. [Whitepaper](https://blockstack.com/tokenpaper.pdf)
4. [Token sale announcement](https://blockstack.org/blog/blockstack-token-sale)
5. [USV Announcement](https://www.usv.com/blog/blockstack-browser-and-token)
6. [Our forum](https://forum.blockstack.org/search?q=token)

**Comment by pstan26** [comment]
On the surface that makes sense. There should be a one stop shop for token
IMO. Adding @shea256 to comment

**Comment by sebdunkel** [comment]
Second this @cwackerfuss @pstan26. I've been getting token sale related questions via Zendesk, too. 
Regarding content, there is also a Paper doc that includes [Token Sale FAQ](https://paper.dropbox.com/doc/Token-FAQ-6rV7IYMbXYIxQIqoyr2xM) copy.

**Comment by cwackerfuss** [comment]
@sebdunkel That's actually exactly what we need. Amazing!

We could also easily reuse this component (swap out copy and image) on the top of the Token FAQ for the Token Whitepaper:
<img width="1170" alt="screen shot 2018-02-13 at 2 15 43 pm" src="https://user-images.githubusercontent.com/4405356/36171475-6b73e118-10c8-11e8-9b4e-454e76237a7a.png">

**Comment by sebdunkel** [comment]
Awesome @cwackerfuss! I'm not sure how far the content has been edited, but I know @muneeb-ali and @GinaAbrams have been working on it. I assume it will need a final pass before it can go live.

**Comment by muneeb-ali** [comment]
+1 on redirect (having two sites creates confusion). 

And we can have a custom page for the token visitors. We should have the token FAQ as part of our general FAQ anyway.

There is a version that can go live (I reviewed it earlier) and then we can iterate. Gina can point to it. Thanks,

**Comment by cwackerfuss** [comment]
Thanks Muneeb! Just waiting on the version from @GinaAbrams and then we can get started building the page. Will link to the Token FAQ from an item on the general FAQ.

**Comment by GinaAbrams** [comment]
@cwackerfuss please take from [here](https://paper.dropbox.com/doc/Token-FAQ-6rV7IYMbXYIxQIqoyr2xM )*Please note that only the top section is to be published.

**Comment by GinaAbrams** [comment]
And thank you! 🙏
