### ISSUE TITLE
Add our Swag Shop to Website 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack.org#514]
I believe at the very bottom, under "community" listings would be a good spot! Please link it to [here](https://blockstack.myshopify.com/)

**Comment by GinaAbrams** [comment]
hey @cwackerfuss just wanted to see if this is hiding somewhere or if we can add it to next rendition? 🙏

**Comment by cwackerfuss** [comment]
Hey, yes @GinaAbrams! It's hiding in the homepage redesign. We'll get this up soon!

**Comment by GinaAbrams** [comment]
sweet, sorry for bugging!
