### ISSUE TITLE
Key Values should be two words on careers page

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack.org#522]
<img width="508" alt="screen shot 2018-03-02 at 1 24 40 am" src="https://user-images.githubusercontent.com/597182/36877074-95ad03ea-1db8-11e8-95d5-71e0697514fb.png">

**Comment by shea256** [comment]
@cwackerfuss How about we mark @larrysalibra as the sponsor for this page. Once he approves this can be merged.

**Comment by cwackerfuss** [comment]
@shea256 I approved this a few days ago and merged. Waiting on it to be deployed in the next release!
