### ISSUE TITLE
As a blockstack engineer, I should be given information about ways to consolidate content and improve the SEO and perf of the marketing website.

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack.org#527]
Hey everyone!

After this mornings engineering meeting it came to light that there are some concerns related to the current website. As I've been poking around and looking through things, I think there are a lot of places where the website can be streamlined and optimized, while also bringing some of the tooling around it up to newer standards.

### Prismic

[Prismic](https://prismic.io/) is a headless content management system where you can define content models in JSON and then build out those models which will form a rest api with the content you have created. 

I think moving the site's content and blog content into prismic would alleviate a lot of the issues we're having now, and it would also allow content producers access to everything related to the marketing efforts on blockstack.org.

Doing this would also allow the content to drive the website, versus having to design a new page each time. When I use prismic, I take advantage of `slices` which are reusable content blocks that can be used anywhere. Examples would be a hero section for a page, or content sections with variants (eg, content section with image, with mock up, with video, etc), a breaker section, or various call to actions. These slices can be anything and they can be combined however the content producer would like. It gives anyone the ability to build out new pages. 

Prismic has some pretty great features baked in:
![screen shot 2018-03-12 at 12 42 41 pm](https://user-images.githubusercontent.com/11803153/37300009-e8351e44-25f2-11e8-83bd-0becb1ab1ae1.png)

### Next.js

[Next.js](https://github.com/zeit/next.js/) is a react framework for creating universal applications (server side rendering). A huge issue we have right now for blockstack.org is that it's a react application without anything like prerender.io running on it, so the seo of the application is essentially nonexistent. One of the major advantages for using something like next.js is the content is rendered before the user views the page, and so it is highly consumable for SEO purposes. There are also significant performance improvements that come along with this.

Next.js also allows for a static export of the application to html. A process I have set up for a few sites goes like this: 

- Make some edits on a new branch
- PR -> production branch
- Merge after consensus/approval
- CircleCI(or any CI tool) then builds the site and deploys the static files to something like Github Pages / netlify.com (or just use netlify.com in place of CI tool)
- New site is live

Another option is to run the non-static version of the site which would then consume the live data from Prismic, and we could have something like `staging.blockstack.org` to see data that has not been published from Prismic before pushing it live to the production site.

cc @cwackerfuss @shea256 @muneeb-ali @larrysalibra

**Comment by cwackerfuss** [comment]
Prismic's "slices" remind me of how Advanced Custom Fields + the ACF Components plugin works to build page modules. Much faster and more predictable way to build out new pages.

One huge benefit to me for using Next.js is that we don't have to move away from React. We can still keep all of our code the same and leverage React componentization, but we still deploy a static app.

**Comment by aulneau** [comment]
💯 exactly -- plus we can integrate any react components we want in the future, too (mini app store, other blockstack components, etc)
