### ISSUE TITLE
Update browser download links to v0.26.1

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack.org#534]
I started to do this but as I mentioned on https://github.com/blockstack/blockstack.org/issues/489#issuecomment-373314695, the deployed site is different than what's on master. Not sure what version is deployed so I'm holding off on updating these.

The download link for macOS v0.26.1 is https://github.com/blockstack/blockstack-browser/releases/download/v0.26.1/Blockstack-for-macOS-v0.26.1.dmg

@cwackerfuss can you update the links when you get a chance? @kantai will need to create the windows and linux builds and provide the links

**Comment by aulneau** [comment]
I have used this little microservice in the past -> https://github.com/evenchange4/micro-github-latest to prevent from having to redeploy a site to only update a couple links to the latest release of a package. We could deploy a version of this and have it be something like `downloads.blockstack.org/browser/macos/latest`, just a thought!
