### ISSUE TITLE
Add a contact page

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack.org#555]
A community member who reached out to me pointed out there's no "official" contact page with email, mailing addresses and/or phone number our website. 

Also, searching for "contact blockstack" returns coinlist on duckduckgo and crunchbase on google instead of something on our website.

Adding a contact page might reduce the number of people that contact us via our personal emails (from our personal websites) or other contact methods and allow them to get more timely responses.

**Comment by sebdunkel** [comment]
#552 – https://github.com/blockstack/blockstack.org/issues/552

Contact Email Address – Press/Speaking Engagements: press@blockstack.com

Contact Email Address – Support/General Inquiries: support@blockstack.com
