### ISSUE TITLE
Update Team Section 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack.org#556]
We need to add Bios for everyone highlighted [here](https://docs.google.com/document/d/1737l4H1ig1Hgd25gKi_ecrdOEL4xZNT3S_xajF_TvX0/edit?usp=sharing) - headshots and Blockstack IDs [here](https://docs.google.com/document/d/1GNpeADPdYulahr6JKULxIE-O1LANPSGmx_o7er-zsys/edit?usp=sharing) and remove Chase, Clint, and Jack. 

I'll have all the info by tomorrow afternoon. 

Thanks, @yknl!!

**Comment by thaonguyenle** [comment]
Hi there, right now Mary is on the same line as Mike Freedman, our advisor, so it looks a bit odd. I wonder if we can separate between team and advisor?
