### ISSUE TITLE
Get mailchimp working

### ISSUE THREAD

**Issue by mattgordils** [blockstack/blockstack.org#563]
<form action="//blockstack.us14.list-manage.com/subscribe/post?u=394a2b5cfee9c4b0f7525b009&amp;amp;id=0e5478ae86"

Slack Mitchell to confirm it's working

**Comment by robincwillis** [comment]
Mailchimp is working, need to add this environment variable on the staging / production environment

MAILCHIMP_URL=https://blockstack.us14.list-manage.com/subscribe/post?u=394a2b5cfee9c4b0f7525b009&amp;id=0e5478ae86
