### ISSUE TITLE
Update meta data

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#572]
Description should be something like: 

"Blockstack is building an ecosystem that gives your users control over their fundamental digital rights: Identity, data-ownership, privacy, and security. Join us and help build the new internet."

**Comment by aulneau** [comment]
This should be the default, and then overwritten on a page-by-page basis? (eg blog posts will have different meta descriptions, as should each page)

**Comment by jeffdomke** [comment]
Currently each page has a unique title, and then a default global description used in tags for meta description, twitter description, and open graph description. I don't think we need a unique one for each page.

**Comment by aulneau** [comment]
For SEO it's better, and I think for the key pages, eg home, jobs, about, what is blockstack, funding, tutorials, etc, unique descriptions makes sense imo.

**Comment by aulneau** [comment]
![screen shot 2018-07-15 at 3 42 57 pm](https://user-images.githubusercontent.com/11803153/42738226-ce716610-8845-11e8-9bca-bdccc7a6d016.png)

We wouldn't want the same description showing up for each of these links on search engines

**Comment by jeffdomke** [comment]
Sure, agreed. I inspected a couple pages and see the same descriptions on all. So on most of those it is using the page content itself.

**Comment by jeffdomke** [comment]
Checked the social preview on twitter — nothing displays. 
Checked the main page — no description or social metadata.

**Comment by aulneau** [comment]
I typically use this when testing:

https://developers.facebook.com/tools/debug/

Things that still need work:

- need a default OG image
- unique descriptions for each page
- different title for home page

**Comment by jeffdomke** [comment]
http://iframely.com/debug?uri=https%3A%2F%2Fblockstackorgv2.netlify.com%2F
