### ISSUE TITLE
Videos page – mobile formatting weirdness

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#581]
![Screen Shot 2018-07-15 at 7:38 PM](http://marker.screenshots.prod.s3.amazonaws.com/3401ca41d3424bedab64e59aea7b44c3-1531683488098.png)
---
### More Info

**Source URL**: [file:///Users/jeffdomke/Downloads/IMG_0250.PNG](file:///Users/jeffdomke/Downloads/IMG_0250.PNG)

**Comment by jeffdomke** [comment]
All the video previews are busted

**Comment by aulneau** [comment]
ah thanks! small bug should be fixed next time I push

**Comment by aulneau** [comment]
fixed -> https://blockstackorgv2.netlify.com/videos/
