### ISSUE TITLE
Curate Video

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack.org#588]
Ask: specify which videos to keep and which to add (if any)

here is the data for it -> https://github.com/blockstack/blockstack.org/blob/feature/new-landing-pages-next/pages/videos/data.js

**Comment by jeffdomke** [comment]
Muneeb shared a doc with the videos he wants: 

A New Internet Where You're In Control
Ryan Shea - TheNextWeb 2017 - December 12, 2017

The Future of the Internet is Decentralized
Muneeb Ali - The Conference - September 1, 2017

A Conversation with Naval Ravikant and Ryan Shea
Ryan Shea & Naval Ravikant - Blockstack Summit 2017 - July 27, 2017

Welcome to the New Internet
Muneeb Ali - TEDxNewYork - September 10, 2016

**Comment by wbobeirne** [comment]
Closed via b8a1ba5f.
