### ISSUE TITLE
Set up a bot to greet new Slack members with a welcome message

### ISSUE THREAD

**Issue by john-light** [blockstack/blockstack.org#59]
e.g. https://github.com/payloadpk/paybot

**Welcome to the Blockstack Slack!**  
- We are encouraging new members to change their user handle to "firstname_project" so that others can quickly identify who's in the channel and who they want to chat with.  
- You can change your notifications preferences in the "Notifications" menu under "Profile and Account," including changes on a per-channel basis.  
- Everyone who is a member of this public Slack group can see your email address; this is a default Slack setting that cannot be changed. Therefore, you should only display an email address that you do not mind being public.  

**What is Blockstack?**  

Blockstack is shorthand for "the blockchain stack." Our mission is to create common infrastructure stack for decentralized applications. You can read more about our community and mission here:  

http://blockstack.org/about  

and you can check out and contribute to the code that's already been written here:  

https://github.com/blockstack  

If you have a blockchain or decentralized application project that you'd like to have added to the list of supporters on the About page, let us know in the #blockstack-site channel. We'll just need the name, URL, and a brief summary of what the project is about. Or, you can open an issue & send a pull request on GitHub:  

https://github.com/blockstack/blockstack-site  

You are welcome to introduce yourself and any projects you might be working on in the #lounge channel and in the introductions thread in the forum:  

https://forum.blockstack.org/t/introduce-yourself/123

If you have any ideas or problems regarding decentralized application development, this is the perfect place to share them and get feedback from your peers. Simply start a new forum thread introducing the topic and share the link in the relevant Slack channel for real time discussion.  

And finally, if you have any questions or suggestions about Blockstack, please don't hesitate to let us know! Thanks for being here 😄

**Comment by kbariotis** [comment]
Hello there, I came on this thread just now and saw that is open so I would like to suggest https://janitr.net, the Slack bot that welcomes new users based on your preferences. Try it ou! :)

**Comment by guylepage3** [comment]
Thanks @kbariotis. Will give it a try.. cc:ing @shea256 @larrysalibra

**Comment by guylepage3** [comment]
Issue moved to [blockstack/blockstack #323](https://github.com/blockstack/blockstack/issues/323) via [**ZenHub**](https://www.zenhub.com/)

**Comment by guylepage3** [comment]
Moved issue to the `blockstack/blockstack` repository.
