### ISSUE TITLE
Ping apps devs and ask for better open source examples. 

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack.org#590]
Current featured:

Graphite
Hermes
Dotpodcast --> Fupio
Kanstack
Coinfort --> Dappy

Here are the ones I considered:

https://github.com/BCNetio/BlockStackWallet
https://github.com/fupio/fupio
https://github.com/swarmfund/swarm-js-base
https://github.com/DemocracyEarth/sovereign

Sovereign – might be a little too hard to grok?
Swarm – not a good project to learn on?

**Comment by jeffdomke** [comment]
Current featured: 

Graphite
Hermes
Dotpodcast --> Fupio
Kanstack  
Coinfort --> Dappy

Here are the ones I considered: 

https://github.com/BCNetio/BlockStackWallet
https://github.com/fupio/fupio
https://github.com/swarmfund/swarm-js-base
https://github.com/DemocracyEarth/sovereign

Sovereign – might be a little too hard to grok? 
Swarm – not a good project to learn on?

**Comment by jeffdomke** [comment]
Waiting for comments. Tomorrow we should swap these unless something changes.

**Comment by jeffdomke** [comment]
Also please update Graphite: https://github.com/Graphite-Docs/graphite

**Comment by eugeneives** [comment]
Hi guys. Where will it be? Main page?

**Comment by jeffdomke** [comment]
Yes, main page.

**Comment by eugeneives** [comment]
@jeffdomke timeline?
