### ISSUE TITLE
Fix the tech stack diagram design

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#591]
<img width="1130" alt="screen shot 2018-07-19 at 4 51 22 pm" src="https://user-images.githubusercontent.com/767828/42969388-09bd6364-8b74-11e8-82ad-e3d36a1b9ad1.png">

**Comment by jeffdomke** [comment]
@muneeb-ali trying to incorporate all the changes you mentioned yesterday. `Stacks` `Atlas` and `Virtual Chain` have been removed from this one.

**Comment by wbobeirne** [comment]
Looks like this has been resolved.
