### ISSUE TITLE
Update Disclaimer for Token LLC website

### ISSUE THREAD

**Issue by lizblockstack** [blockstack/blockstack.org#600]
Change to new Token LLC domain name on Blockstack.org and https://explorer.blockstack.org/:

"The Blockstack Tokens are a crypto asset that is currently being developed by Blockstack Token LLC, a Delaware limited liability company, whose website can be found at www.blockstack.com. The website you are currently visiting (www.blockstack.org) is sponsored by Blockstack PBC, an affiliate of Blockstack Token LLC, and should not be viewed as an offer or sale of securities."

**Comment by wbobeirne** [comment]
Closed via 12f50e3e.
