### ISSUE TITLE
Tutorial and Berlin Event links are incorrect

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack.org#602]
The Authentication tutorial should be linking to `/tutorials/todo-list`
and the Storage tutorial should be linking to `/tutorials/multi-player-storage`

The Blockstack Berlin link is currently linking to `/berlin2018`

**Comment by kantai** [comment]
Fix pushed, will update the test server soon

**Comment by kantai** [comment]
Test deployment is updated.
