### ISSUE TITLE
Improve formatting on /blog

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#605]
![Screen Shot 2018-07-26 at 2:52 PM](http://marker.screenshots.prod.s3.amazonaws.com/59d15ac7dd134cc3992434a8340a058a-1532616735868.png)
---
### More Info

**Source URL**: [https://deploy-preview-569--blockstackorgv2.netlify.com/blog/](https://deploy-preview-569--blockstackorgv2.netlify.com/blog/)

**Comment by wbobeirne** [comment]
Fixed in a63e198e. Here's what it looks like:

<img width="733" alt="screen shot 2018-07-26 at 11 39 06 am" src="https://user-images.githubusercontent.com/649992/43272740-bb57b152-90c8-11e8-8b54-ae223094d6af.png">
