### ISSUE TITLE
Blog pages – include author

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#606]
![Screen Shot 2018-07-26 at 2:53 PM](http://marker.screenshots.prod.s3.amazonaws.com/0c5d2bedf29447649536e9b43ed6b09a-1532616837120.png)
---
### More Info

**Source URL**: [https://deploy-preview-569--blockstackorgv2.netlify.com/blog/universal-wallet-bounty-recap/](https://deploy-preview-569--blockstackorgv2.netlify.com/blog/universal-wallet-bounty-recap/)

**Comment by wbobeirne** [comment]
Closed via aeb2a603. Now looks like:

<img width="819" alt="screen shot 2018-07-26 at 1 13 47 pm" src="https://user-images.githubusercontent.com/649992/43277359-d3d89fcc-90d5-11e8-94a5-797f8949ee15.png">
