### ISSUE TITLE
Stack formatting bug

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#607]
![Screen Shot 2018-07-26 at 3:03 PM](http://marker.screenshots.prod.s3.amazonaws.com/f301710946ca43079db13b8005447b2f-1532617428096.png)

Formatting breaks at this width and also on the phone. Suggestion to try "App.co: Publish your app" that might fix it in all conditions. And also remove the last app when the size is borked. 

---
### More Info

**Source URL**: [https://deploy-preview-569--blockstackorgv2.netlify.com/](https://deploy-preview-569--blockstackorgv2.netlify.com/)

**Comment by wbobeirne** [comment]
Closed via 18d4937d.
