### ISSUE TITLE
Email sign up tell people when it doesn't work because of content blocker 

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack.org#617]
It stays at “processing”.

![img_7092 2](https://user-images.githubusercontent.com/597182/43351327-f756ab6a-9242-11e8-9994-551f6af10286.png)

**Comment by larrysalibra** [comment]
This looks like it's caused by the adblocker i'm using, Firefox Focus (recommended to me by @kantai).


<img width="999" alt="screen shot 2018-07-31 at 11 13 46 pm" src="https://user-images.githubusercontent.com/597182/43468817-71d70dc2-9517-11e8-8a7a-22ce261eb29d.png">

Enough people use ad/tracker blockers that the page should handle the error and tell people what's going on so that they can disable their content blocker.

Better yet, signing up for our email address should hit our own api which then adds the user to the mailing list instead of sending IP info of the user to mailchimp.

**Comment by larrysalibra** [comment]
Update: while i was writing this post, the page crashed presumably as a result of this and turned all blue/purple:

![img_7204](https://user-images.githubusercontent.com/597182/43469183-2df1aabc-9518-11e8-8e96-7920136ab722.png)


<img width="1013" alt="screen shot 2018-07-31 at 11 16 11 pm" src="https://user-images.githubusercontent.com/597182/43469189-3146fcbc-9518-11e8-8df0-0f9267a67992.png">

**Comment by wbobeirne** [comment]
Looks like the problem there is that browser doesn't have the `String.includes` function. I also encountered this lack of polyfilling in #624, so it's definitely not doing the right thing.

**Comment by larrysalibra** [comment]
Safari on both iOS and Mac has String.includes: https://caniuse.com/#feat=es6-string-includes

Just verified in the console by trying 
```
"a".includes("a")
```

**Comment by wbobeirne** [comment]
Ah, then the alternative here is that `this.state.error` is not a string. Could very well be an `Error` object.

**Comment by aulneau** [comment]
@larrysalibra I'm not sure I can check for this, as I'm not positive it's returning an error status code. What are you using to block this content? I have ublock and it's allowing it through.

**Comment by larrysalibra** [comment]
@aulneau - I’m using firebox focus’s content blocker - Aaron suggested it to me. (This is on iOS)

**Comment by aulneau** [comment]
This should be resolved as the site is different now. closing.
