### ISSUE TITLE
Email input should be of type email

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack.org#618]
This was reported on the forum post asking for feedback: https://forum.blockstack.org/t/blockstack-org-update/5452/11?u=larry

**Comment by larrysalibra** [comment]
Using the `text` type field causes behavior on mobile to be incorrect. (auto capitalizing email, etc)

**Comment by markmhx** [comment]
@larrysalibra thanks for raising this issue – one of my pet peeves!

I've confirmed it's resolved in https://github.com/blockstack/blockstack.org/pull/640.
