### ISSUE TITLE
Email sign up shouldn't tell people if they are already signed up 

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack.org#619]
This leaks as you can check if someone has signed up for the email list. It is a privacy issue.

It should always accept sign ups even if the user has signed up before.

<img width="693" alt="screen shot 2018-07-28 at 8 46 38 am" src="https://user-images.githubusercontent.com/597182/43351362-58c89188-9243-11e8-810c-bcf932d56717.png">

**Comment by markmhx** [comment]
I've confirmed this is resolved in https://github.com/blockstack/blockstack.org/pull/640.
