### ISSUE TITLE
Blockstack logo only partially clickable

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack.org#620]
By convention, clicking on a website logo takes you back to the homepage.

Our logo is only clickable on the image and "Block" portion of the logo.

Reproduced on Browsers:
* Safari Version 11.1.2 (13605.3.8)
* Chrome Version 68.0.3440.75 (Official Build) (64-bit)

See video: 
https://www.icloud.com/iclouddrive/0isu3Go6euAM_jXMGEBUtvNWQ#logo_issue

**Comment by markmhx** [comment]
The active click area appears larger on https://github.com/blockstack/blockstack.org/pull/640. However, nitpick: the area is now *too* big in that it extends to the right all the way to the hamburger menu:

<img width="1092" alt="screen shot 2018-08-30 at 11 30 57" src="https://user-images.githubusercontent.com/28991/44843360-737d1480-ac48-11e8-8ad3-a962b6c14d60.png">

My recommendation would be to constrain it to dimensions immediately surrounding the full logo itself to prevent accidental activations:

<img width="1092" alt="screen shot 2018-08-30 at 11 30 57 copy" src="https://user-images.githubusercontent.com/28991/44843378-81cb3080-ac48-11e8-9130-f38dc9f6559c.png">

Lots of people click randomly on webpages out of nervous habit and we don't want them losing their place =)

**Comment by aulneau** [comment]
@markmhx must be fixed as I cannot recreate this with the latest code on the feature branch!
