### ISSUE TITLE
Older blog articles are not reachable, not linked from blockstack.org

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack.org#621]
We should maintain links to the blog articles from the site for SEO. The way it's setup right now is terrible for SEO. All blog articles past the first 15 are not visible or linked to, and won't be crawled by search engines.

**Comment by jeffdomke** [comment]
Checked SEO on these and there is very little activity. First step is to sort through everything at https://github.com/blockstack/blockstack/tree/master/posts and figure out stuff we actually want to port vs. stuff that is just old and not needed.

**Comment by yknl** [comment]
The posts in your link are different from the blog articles which are loaded and cached from the ghost blog during build. The blog articles in question are the ones listed on https://www.blockstack.org/blog but are so old that they don't appear on the list. They definitely aren't getting any activity because they're completely unreachable.

**Comment by jeffdomke** [comment]
> The blog articles in question are the ones listed on https://www.blockstack.org/blog but are so old that they don't appear on the list. 

They are in ghost? 
They are not loaded and cashed? 
Or they are not displayed for some reason? 

@aulneau think both you and I are confused on this.

**Comment by yknl** [comment]
The site loads blog articles from https://blockstack.ghost.io/
There are articles going back to 2015 on there, however the code on blockstack.org that fetches the blog posts only gets the most recent 15 articles. If you scroll to the bottom, the last one from is nov 1, 2017. All articles before that are not accessible, so we're not getting any SEO benefits from them. Also, any outside links to older articles would give 404's, and that's really bad for SEO.

**Comment by aulneau** [comment]
@yknl I see that the server we have proxying the ghost blog needs a page param, rather than serving up all the data and putting the responsibility of pagination on the client. I will add a check for if n pages exist, and then fetch data for them. should be fixed soon!

**Comment by markmhx** [comment]
I'm seeing 42 blog posts now on staging for https://github.com/blockstack/blockstack.org/pull/640, going back to February 17, 2015 announcing the "Initial release of Blockstack Core".

@yknl is that the total number and oldest post you'd expect to see on the blog page with this fix?
