### ISSUE TITLE
Add a sitemap

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack.org#622]
This will help with getting crawled by search engines more frequently

**Comment by jeffdomke** [comment]
Took a look at the sitemap and noticed it is missing /roadmap. Wondering if this is just due to some branching weirdness or if this thing actually isn't generating correctly?

**Comment by aulneau** [comment]
@jeffdomke so the static pages aren't added automatically, it's a step in the process of adding a new page to manually add it to the sitemap. I will make it so that all of our routes live in one place though and add a section to the readme on how to add a new route.

**Comment by aulneau** [comment]
fixed in https://github.com/blockstack/blockstack.org/commit/9ff6ee527914775e10e9542cfce76b591cfe5759

**Comment by markmhx** [comment]
I've confirmed that a sitemap is now available on staging for https://github.com/blockstack/blockstack.org/pull/640 and it includes `/roadmap`.
