### ISSUE TITLE
Careers Page Updates 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack.org#625]
Request #1: 
Please make KeyValues link to our [profile](https://www.keyvalues.com/blockstack)

Request #2: 
Can we *remove* the following text? 🙏 

We get a lot of applicants, and have historically hired people who are proactively involved in our work and mission of decentralizing the internet. Even a simple pull request goes a long way in signaling interest in the project. We hope you explore our Github, Whitepaper, Browser, and Slack prior to submitting your resume.

Danke!

**Comment by markmhx** [comment]
@GinaAbrams was that text scaring off potential applicants? 😃

**Comment by markmhx** [comment]
I've confirmed both of these changes have been made on staging for https://github.com/blockstack/blockstack.org/pull/640.

**Comment by GinaAbrams** [comment]
haha @markmhx I'm actually not sure, just figured that we could be a bit more welcoming 😄

**Comment by GinaAbrams** [comment]
and thank you!!
