### ISSUE TITLE
Mixed content warning

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack.org#643]
We have some content from @muneeb-ali 's website that's served over http and causing mixed content warnings:

```
10:43:05 AM: Minifying bundle
10:43:12 AM: Mixed content detected in: /blog/why-blockstack-is-migrating-to-the-bitcoin-blockchain/index.html
10:43:12 AM: --> insecure img urls:
10:43:12 AM:   - http://muneebali.com/static/img/posts/block_confirmation_times.png
10:43:13 AM: Minifying bundle
```

**Comment by aulneau** [comment]
@larrysalibra do you have access to the ghost blog? It's not in 1pass. I need access to be able to go in and change the urls. I have a basic fix which I am not sure why it's not being applied: https://github.com/blockstack/blockstack.org/blob/39217634bbd87b3766ec7f6d2e8486adcda7b30a/common/es6/index.js#L77

cc @shea256 for ghost login

**Comment by aulneau** [comment]
Should be fixed now!
