### ISSUE TITLE
Broken build process

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack.org#645]
The current package.json has an unstable build process -- it depends on a bunch of beta releases for various build utils. Intermittently, this breaks the build. So, currently:

```
$ git clone blockstack.org
$ cd blockstack.org
$ npm i
$ npm run prod
```

Leads to a huge amount of babel errors -- but this seems to be the root cause.

```
> Failed to build
{ Error: (client) ./pages/papers/index.js
Module build failed: TypeError: programPath.hub.addHelper is not a function
```

**Comment by aulneau** [comment]
@kentai this is resolved with #640. I'm not sure it was a result of the beta version as much as a combination of improper implementation / mis matched versions.
