### ISSUE TITLE
Blue bar visual weirdness 

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#650]
![Screen Shot 2018-08-28 at 2:43 PM](http://marker.screenshots.prod.s3.amazonaws.com/5a053b6676d948aba605aa89dbc34156-1535467414403.png)

Two suggestions: 
– Put a slight shadow under the bar
– Make the bar bg color slightly darker in general. 

---
### More Info

**Source URL**: [https://deploy-preview-640--blockstack.netlify.com/](https://deploy-preview-640--blockstack.netlify.com/)

**Comment by aulneau** [comment]
fixed with https://github.com/blockstack/blockstack.org/commit/f2f50416bbad71c7b70f70c0cc27135d034ea154 and https://github.com/blockstack/blockstack.org/commit/110e5c5ad89d30187a7f2efab23bfe1a760cc3f7
