### ISSUE TITLE
Careers Page Edit -- Office Locations 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack.org#651]
Feel like our intl offices are a bit misleading. Can we change "Blockstack PBC has offices in New York City, San Francisco, Hong Kong, and Toronto." to: Blockstack PBC is headquartered in New York City, with a globally distributed team located across Hong Kong, Gambia, Barcelona, Toronto, and Seattle.

**Comment by aulneau** [comment]
fixed with https://github.com/blockstack/blockstack.org/commit/e8bd00015c2d25fec825ca2889c0f491f8e5774c!
