### ISSUE TITLE
Careers Page Edit -- Copy Changes 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack.org#652]
The section under Blockstack Values: 

Can we add links to this section? 

...the team engages with users via.....  [Slack](https://docs.google.com/a/blockstack.com/forms/d/e/1FAIpQLSed5Mnu0G5ZMJdWs6cTO_8sTJfUVfe1sYL6WFDcD51_XuQkZw/viewform), [Github](https://github.com/blockstack), [Twitter](https://twitter.com/blockstack), and the Blockstack [Forum](https://forum.blockstack.org/). [And end sentence, please take out "in order to build the best product possible."]

**Comment by aulneau** [comment]
fixed with https://github.com/blockstack/blockstack.org/commit/a85700b18016ce257b2f434dab6f8825ba6dba70
