### ISSUE TITLE
Menu bar get updates UI is not working and disappearing

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#653]

**Comment by jeffdomke** [comment]
![2018-08-28 10_51_02](https://user-images.githubusercontent.com/767828/44731113-793ff200-aab0-11e8-9b85-a915a6b07172.gif)
![2018-08-28 10_51_47](https://user-images.githubusercontent.com/767828/44731116-7b09b580-aab0-11e8-8313-1649a11f2fa7.gif)

**Comment by jeffdomke** [comment]
Two observed issues.
– The button/input appear and disappear erratically. 
– I can get into a state where clicking on the email input acts like a page refresh (take me to the top of the page, reloads images, etc).

**Comment by aulneau** [comment]
I'm going to punt this to the 1-off improvements section. I think these issues happen when you are stress testing it, but will not happen very often during real use cases. I'm going to have to rewrite a lot of the code that we got from the freelancers that handle this behavior. I will look into the email input refresh issue though.

**Comment by aulneau** [comment]
I am not able to reproduce:
> I can get into a state where clicking on the email input acts like a page refresh (take me to the top of the page, reloads images, etc).

can you please provide a detailed list of steps to reproduce this state?

**Comment by jeffdomke** [comment]
Can't reproduce either day. Oh well.
