### ISSUE TITLE
Menu nav is missing new items in footer

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#654]

**Comment by aulneau** [comment]
I will go ahead and make a single navigation component that displays the same links. Which items are missing?

**Comment by jeffdomke** [comment]
Telegram (English)
Telegram (中文群)

**Comment by aulneau** [comment]
fixed in https://github.com/blockstack/blockstack.org/commit/d859709eb4206242f4d8b4b7a5fb7d32bd4312e7
