### ISSUE TITLE
Documentation link should go to documentation site

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack.org#666]
The current Documentation link just goes to the Javascript reference. We should send people to the new documentation site.

**Issue Type (check one)**

- [x ] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question / Other

**Comment by jeffdomke** [comment]
@moxiegirl  No problem, will do. 

You also want to point to the new to tutorials? I assumed that once the new docs site was up we would rethink that whole top section. Do you want a single CTA pointing to `hello-blockstack.html` or we can keep both tutorials. Happy to do whatever you recommend.

**Comment by moxiegirl** [comment]
Thanks @jeffdomke I am working on the todo list tutorial today. Once that is done, we should take a look at shifting things.  I thought this little change was ok to put in now as very low disrupt level.
