### ISSUE TITLE
Footer needs correcting

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack.org#675]
The Blockstack Tokens are a crypto asset that is currently being developed by
Blockstack Token LLC, a Delaware limited liability company, whose website can be
found at www.blockstack.com. The website you are currently visiting
www.blockstack.org is sponsored by Blockstack PBC, an affiliate of Blockstack
Token LLC, and should not be viewed as an offer or sale of securities.

"whose website an be found at www.blockstack.com" is the issue. It just redirects to www.blockstack.org

**Issue Type (check one)**

- [x] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question / Other

**Comment by moxiegirl** [comment]
Moved this issue from the browser https://github.com/blockstack/blockstack-browser/issues/1713

**Comment by moxiegirl** [comment]
@krtb here you go, this is the right place. If you fork this repo, you should be able to locate the footer. Apologies for the confusion.

This is the corporate website and I can understand if you wanted to work on the browser instead. If you prefer to work on the browser, here is a list of the good first issues: on that repo.

https://github.com/blockstack/blockstack-browser/labels/good%20first%20issue

**Comment by krtb** [comment]
thanks @moxiegirl!

**Comment by krtb** [comment]
@moxiegirl, every time I write "www.blockstack.com" in my own browser's search bar, I get rerouted to the .org site. I thought it was a simple href fix in the footer, but now I don't know where to look for the bug?

**Comment by moxiegirl** [comment]
@krtb Apologies for the delay in getting back to you.  I totally dropped the ball. The reason www.blockstack.com reroutes you is there is a redirect. The actual footer text is in the `disclaimers.md`file.

I think we just need to change this:

```
The Blockstack Tokens are a crypto asset that is currently being developed by
Blockstack Token LLC, a Delaware limited liability company, whose website can be
found at [www.blockstack.com](https://www.blockstack.com).
```

to this:

```
The Blockstack Tokens are a crypto asset that is currently being developed by
Blockstack Token LLC.
```

**Comment by krtb** [comment]
@moxiegirl, no worries! I forked the project, added the changes, and submitted a pull request. The link to it can be found here (https://github.com/blockstack/blockstack.org/pull/686)
