### ISSUE TITLE
Suggestions for what-is-blockstack doc

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack.org#69]
The description on [what is blockstack](https://github.com/blockstack/blockstack-site/blob/master/app/docs/what-is-blockstack.md) is great. Great job. One issue I have with the current description is that it does not mention the word blockchain at all. A related thing is that it's hard to make statements like "more secure by design than traditional DNS and much more resilient to outside tampering and control" without pointing out the why/how. 

I'd update the description along the lines of:

```With the Blockstack software, a network of computers collectively maintain a global registry of domain names. This registry is secured by an underlying blockchain."

When you run a Blockstack node, you join this network, which is more secure by design than traditional DNS and much more resilient to outside tampering and control. This is because an attacker will require an extremely large amount of compute power to tamper the underlying blockchain.``` 

A second thing that jumped out at me was use of the word "browser". 

>  associated with instructions for how browsers and other software should resolve the name

Right now there seems to be focus on browsers supporting this and people generally think that it's hard to make browsers to add support for non-traditional DNS systems. We can say something like:

```
associated with instructions for how DNS resolvers and other software should resolve the name
```

Somehow, to me, it's easier to imagine that we can patch DNS resolvers to support this vs. thinking that we can convince Chrome/Firefox/Safari to add support for this.

**Comment by jcnelson** [comment]
> Somehow, to me, it's easier to imagine that we can patch DNS resolvers to support this vs. thinking that we can convince Chrome/Firefox/Safari to add support for this.

Yeah, we might even want a blurb about how one might convert a Blockstack DNS node's information into a config directory tree for $YOUR_FAVORITE_DNS_SERVER.  I could add a diagram, for example.

**Comment by shea256** [comment]
Great suggestions! I'll incorporate them in.

**Comment by shea256** [comment]
And @jcnelson I agree that we should have that somewhere, but not in the "What is Blockstack?" post because it's a bit too technical and this post is meant to be very introductory and high-level. Ideally we'd have an entire article where users could learn how to set up unbound to work with a Blockstack server.

**Comment by muneeb-ali** [comment]
Agreed that it's an important topic and should be there for advanced users. People who're just reading the introduction are probably not the target audience for this.

**Comment by guylepage3** [comment]
@muneeb-ali @shea256 @jcnelson where are we with this issue? can i close it out?
