### ISSUE TITLE
Footer menu item updates

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack.org#696]
Remove 'Newsletter Archive' from Community column, we don't have this anymore and I don't want to push folks to MailChimp. I'll work on setting up another option for the archive, but we should pull out for now. 

Second, update the link for Signature Fund to https://signature.vc (this site won't load in the NY office, but it is definitely up and good. 

Last, add link for 'Twitter' above YouTube to https://twitter.com/blockstack and remove from the 3rd column where it currently is. I want the Twitter to be part of community, not just about us. This reflects how we're going to start using it more accurately and it makes sense to find it next to the other social networks. 

Thanks!

**Comment by aulneau** [comment]
Great! will most likely get to these after the holiday.
