### ISSUE TITLE
RSS/Atom feed

### ISSUE THREAD

**Issue by rEnr3n** [blockstack/blockstack.org#697]
**Issue Type (check one)**

- [ ] Bug Report
- [x] Feature Idea
- [ ] Technical Discussion
- [ ] Question / Other

Please add rss/atom feed to your blog. The previous one is not working. https://blockstack-site-api.herokuapp.com/v1/blog-rss

**Comment by aulneau** [comment]
We have an rss feed for the blog at https://blog.blockstack.org/feed/
