### ISSUE TITLE
Add board to About page

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#699]
![Screen Shot 2018-11-29 at 3:44 PM](http://marker.screenshots.prod.s3.amazonaws.com/cbb42a3bf47e43a79bc7ac2196ba5a18-1543506288888.png)

Suggestion: Create a section on top for `Board`. Include all board members. Then `Team` section below can start with Jude and Aaron. 

---
### More Info

**Source URL**: [https://blockstack.org/about/](https://blockstack.org/about/)

**Comment by jeffdomke** [comment]
@muneeb-ali just confirming this change. Having bio information for board members would be helpful, we can hunt around for it but if there is a good place to look that would be fastest.

**Comment by muneeb-ali** [comment]
Initial text can come from Albert's bio from the Reg A filing. JP's bio is already on the website.

I might need to edit the bios after we have those drafts.
