### ISSUE TITLE
Redirect Onename to blockstack.org

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#700]
![Screen Shot 2018-11-29 at 3:47 PM](http://marker.screenshots.prod.s3.amazonaws.com/4046bd7e8ff3451da926e731832f9f4c-1543506433009.png)

Suggestion 1: Redirect ULR to Blockstack.org. 

Suggestion 2: Retain the page but remove the signup/signin. 

Suggestion 3: Review docs and decide if we need to port any content or simply remove.  

---
### More Info

**Source URL**: [https://onename.com/](https://onename.com/)

**Comment by aulneau** [comment]
I think rather than changing this site, we should just redirect it permanently. cc @kantai

**Comment by jeffdomke** [comment]
@moxiegirl feel like you might have thoughts on the best way to deprecate this. @muneeb-ali just confirming you want to completely shut this down correct?

**Comment by muneeb-ali** [comment]
Yep completely shutdown and redirected to Blockstack.com (as blockstack.org is changing to blockstack.com)

**Comment by jeffdomke** [comment]
@kantai can you please take care of this when you have a bit of time.

**Comment by kantai** [comment]
Sure... I'm not sure of what we want to actually do here. I can come up with a kind of plan of action, but it may involve roping some other people in (sending mass e-mails, etc.), because unless I'm mistaken, I don't think we just want to flip a switch and have the domain redirect.

**Comment by jeffdomke** [comment]
Sorry to bug @kantai just following up here. `we just want to flip a switch and have the domain redirect` I think that is what we want.

**Comment by markmhx** [comment]
I'm closing this issue out in favor of the newer one here: https://github.com/blockstackpbc/devops/issues/222
