### ISSUE TITLE
Blockstack.org --> Blockstack.com

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#701]
URL change and then redirect `.org` to `.com`

**Comment by jeffdomke** [comment]
@muneeb-ali might be helpful if you could outline the rational here. I expect many people won't think this is a positive change.

**Comment by muneeb-ali** [comment]
We can announce this with the following context:

As the Blockstack ecosystem is growing with independent entities, it's becoming important to differentiate Blockstack PBC, a US-based Public Benefit Corp, from the broader ecosystem. Blockstack.com is a website managed by Blockstack PBC and it'll list the corporate structure, investors etc and have official Blockstack PBC updates and communication. 

Examples of other web properties maintained by other entities include: 

Stacktoken.com, operated by Blockstack Token LLC 
Signature.vc, operated by Blockstack Signature Fund I LLC (I need to double check the exact name)
<Larry's entity when he has a website>

**Comment by jeffdomke** [comment]
cc @kantai @wileyj 

@muneeb-ali The announcement framing sounds fine, but I'm still not understanding the objective? The announcement could equally apply to `.org` correct?

**Comment by moxiegirl** [comment]
If we do this to `blockstack.org` we should also move `ocs.blockstack.org` to > `docs.blockstack.com`

**Comment by jeffdomke** [comment]
Thought I caught some side conversations that some people are opposed to `.com` over `.org` and that we have a viable alternative. Closing this, let me know if I heard that wrong.
