### ISSUE TITLE
New Page: blockstack.org/pbc

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#707]
Title: Blockstack PBC

Headline: `About Blockstack PBC`

```Blockstack PBC, a Public Benefit Corp, upholds specific commitments to the greater public good in addition to stockholder interests. The mission of Blockstack PBC is to enable an open, decentralized internet. Blockstack PBC is committed to always keep the core Blockstack software open-source, and to support the decentralization of the Blockstack network. Blockstack PBC has historically taken the lead on Blockstack protocol development, but in the future will work with other parties to build a fully transparent and adaptable decentralized internet.```

Headline: `Blockstack PBC Board`

- Muneeb
- Albert
- JP

Headline: `Blockstack PBC Investors`

Logo list: 
- Union Square Ventures
- Lux Capital
- Naval Ravikant

**Comment by jeffdomke** [comment]
@muneeb-ali please edit copy above.

**Comment by aulneau** [comment]
@jeffdomke does `Naval Ravikant` have a 'logo'?

**Comment by jeffdomke** [comment]
Haha. I mean he should. Maybe that is a vote to non-logo-ize this list.
