### ISSUE TITLE
Update Careers page to add accounting position

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack.org#728]
1. [Current website](https://blockstack.org/careers/ 
)
2. Can we please update it to reflect the new accounting role as listed [here](https://jobs.lever.co/blockstack)?

Tagging @aulneau, please let me know if I should ping someone else 🙏

**Comment by aulneau** [comment]
These are generated automatically by fetching the data. We just need to redeploy the site and it will update. cc @kantai

**Comment by aulneau** [comment]
I believe this is resolved. closing.
