### ISSUE TITLE
Add featured hyperlinks to browser.blockstack.org 

### ISSUE THREAD

**Issue by GInxh** [blockstack/blockstack.org#729]
blockstack.org

Putting a link on the website to browser.blockstack.org in the top right hand corner or a "try blockstack" link at the top before diving into the nature of full stack development and app mining would be helpful.

FILL OUT THE FORM BELOW OR THE ISSUE WILL BE CLOSED

--->

**Issue Type (check one)**

- [ ] Bug Report
- [X ] Feature Idea
- [ ] Technical Discussion
- [ ] Question / Other

**Comment by aulneau** [comment]
We now have this. Closing.
