### ISSUE TITLE
Dynamically populate homepage apps

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#735]
It seems that the homepage's app listings are getting stale as quickly as the Browser homepage, which [we're changing](https://github.com/blockstack/blockstack-browser/pull/1823) to render apps dynamically using App Mining and categories.

Should we do the same for blockstack.org's homepage here? This is the first consumer-centric thing that inquirers of Blockstack presumably see when they load our website, so it seems important that we show the best apps here based on recent data.

<img width="1013" alt="screen shot 2019-02-21 at 10 00 01" src="https://user-images.githubusercontent.com/28991/53156390-9832c300-35bf-11e9-8935-3214bb151c0c.png">

**Comment by GInxh** [comment]
@markmhx there are two other issues related to this open already, please cross link and add inside appropriate epics upon creation to avoid technical debt and iceboxing issues in progress.

**Comment by markmhx** [comment]
Sorry, not sure which issues you have in mind?

**Comment by aulneau** [comment]
This issue is no longer relevant with the latest design. Closing.
