### ISSUE TITLE
https://blockstack.org/updates/ – formatting? 

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#739]
Not sure where this is hosted or what is going on, but it isn't running our same templates.

**Comment by aulneau** [comment]
This is under the control of @cuevasm.

**Comment by cuevasm** [comment]
it's just an index of old quarterly update emails, you can format this differently if you like, Muneeb asked for it quickly and I made it in a pinch. In the meantime I brought it up to speed with the newer design, I've been trying to slowly do this in the background and have got to some pages on the community site, but have been busy with token stuff - https://newsletters.blockstack.org/
