### ISSUE TITLE
FAQ appears in mobile as a blue header

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack.org#743]
**Describe the bug**
When going to the direct link blockstack.org/faq the page first appears without content and only a blue header:

![image](https://user-images.githubusercontent.com/1347209/54048700-6577f580-418f-11e9-81a3-592d58886920.png)

A refresh resolves the problem.  May be related to how we produce the site.

First reported by @muneeb-ali via email. I repro'd it on my phone today

**To Reproduce**
1. Open Iphone.
2. Open Chrome
3. Enter `blockstack.org/faq` in the address field

**Expected behavior**
FAQ page should appear.

**Screenshots**

![image](https://user-images.githubusercontent.com/1347209/54048700-6577f580-418f-11e9-81a3-592d58886920.png)

**Smartphone (please complete the following information):**
 - Device: Iphone 10
 - OS: Ios 12.1.4
 - Browser Chrome

**Comment by aulneau** [comment]
Site has been updated, closing now
