### ISSUE TITLE
Add section for other / 3rd party browsers on Install page

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#744]
We may want to add a section on [the Install page](https://blockstack.org/install/) that lists other browser options, especially ones made by third parties, now that both @friedger has created [a native Android browser](https://github.com/friedger/blockstack-browser-twa) and @MichaelFedora has created [a Chrome extension](https://github.com/MichaelFedora/unofficial-blockstack-extension).

**Comment by friedger** [comment]
The native browser as TWA needs to be published by the owner of the domain browser.blockstack.org

**Comment by aulneau** [comment]
@jeffdomke thoughts?
