### ISSUE TITLE
Dead link in FAQ

### ISSUE THREAD

**Issue by thaonguyenle** [blockstack/blockstack.org#748]
**Describe the bug**
The link in the FAQ https://blockstack.org/faq/ under 'What's the difference between Onename and Blockstack?' is dead/not working

**To Reproduce**
1. Go to https://blockstack.org/faq/ 
2. Find Difference between Onename and Blockstack
3. Click on the link. 

**Expected behavior**
I expect for the link to be updated to an answer

**Screenshots**
no screen shot

**Desktop (please complete the following information):**
 mac, chrome

**Additional context**
THank you!

**Comment by GInxh** [comment]
Thanks TN for point this out

**Comment by aulneau** [comment]
Thanks for this! do you mean the 'namecoin' question?

**Comment by aulneau** [comment]
for myself later, this is the URL to update to -> https://docs.blockstack.org/core/naming/comparison.html#blockstack-vs-namecoin

**Comment by thaonguyenle** [comment]
Nope, it's the difference between 'onename' and Blockstack. here: What's
the difference between Onename and Blockstack?
<https://blockstack.org/faq/#whats-the-difference-between-onename-and-blockstack>

Onename is the free Blockstack ID registrar run by Blockstack. It makes it
easy to register your name and setup your profile. Once the name has been
registered in Onename you can transfer it to a wallet you control, or leave
it there and use it as you like.

**Comment by aulneau** [comment]
![Screen Shot 2019-04-03 at 10 18 56 AM](https://user-images.githubusercontent.com/11803153/55490767-ea70f600-55f9-11e9-86f5-ad535da8b04c.png)

There is no link in that question to be broken. The link in the namecoin section is present and broken. Can you clarify what you mean @thaonguyenle

**Comment by thaonguyenle** [comment]
Ah, got it. It's not meant to be a link there. But bc there's an underline
and the appearance is just like the other item, with links (like Namecoin),
the person who reported it (a candidate) must have thought it was a dead
link.
Should we remove the underline to make it not seem like a link?

**Comment by aulneau** [comment]
It is a link, the link is to the anchor of that question, so that people can send you to that specific place on the page. `https://blockstack.org/faq/#whats-the-difference-between-onename-and-blockstack`

**Comment by thaonguyenle** [comment]
Ok. Thanks!
