### ISSUE TITLE
Updating Stats in About Us 

### ISSUE THREAD

**Issue by thaonguyenle** [blockstack/blockstack.org#749]
**Describe the bug**
The stats in the https://blockstack.org/about/ page is outdated and needs to be updated.
Here's what it is right now:
Stats
3+ years in production
74,000+ domains registered
Over 7,000 members in the developer community
4,000+ Slack community members
7,000+ Meet-Up Members, with events spanning 23 cities in 12 countries

When I posted it to #OKR6, here's what Muneeb said: 
muneeb [5:32 PM]
I think a bunch of them should just be removed

**Expected behavior**
We currently have 6,800+ Slack Community Members. 
I don't know what else should be added or removed, but perhaps someone in Marketing knows.

**Comment by aulneau** [comment]
This has been resolved with the latest updates to the site
