### ISSUE TITLE
Swap out apps

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#756]
![Screen Shot 2019-04-09 at 3:43 PM](http://marker.screenshots.prod.s3.amazonaws.com/fdd4d904f5584b06a8feeb6a87661337-10000x10000-1554824636576.png)

Link directly to apps websites vs. github

New list: 

Graphite
Blockusign
Recall
Blockvault
Sigle

---
### More Info

**Source URL**: [https://blockstack.org/](https://blockstack.org/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 73.0.3683.86</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.2</td></tr><tr><td><strong>Viewport Size</strong></td><td>2024 x 1262</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by jeffdomke** [comment]
![Screen Shot 2019-04-10 at 10.45.52 AM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/8c976bd1-d0ff-4eb7-bb46-2c644b5cc2fe)

@aulneau can you mess with the formatting a bit to make it resemble this quick mockup in terms sizing, padding, lack of CTA, etc.

**Comment by aulneau** [comment]
![Screen Shot 2019-04-10 at 11 03 06 AM](https://user-images.githubusercontent.com/11803153/55894735-4c90a480-5b80-11e9-9c4d-fa7eba8c2c6b.png)
