### ISSUE TITLE
Update About with most recent content

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#759]
@cuevasm has the most recent draft.

**Comment by cuevasm** [comment]
https://paper.dropbox.com/doc/Blockstack.orgabout--Aa4RhhP26nFCorOQXnzxa_SFAg-ddMmSELAMftN0EPkWLka7

**Comment by jeffdomke** [comment]
Revision: We should edit out list of rights/manifesto. The rest looks good to me.

**Comment by cuevasm** [comment]
That's fine, Muneeb was good with this version of them and I included since
they are referenced. Any particular reason not to include?

**Comment by jeffdomke** [comment]
Update with latest revision from Muneeb.
