### ISSUE TITLE
Update blockstack.js used by Community Rewards

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#760]

**Comment by moxiegirl** [comment]
Can you elaborate on what this is in the description? Which community rewards?

**Comment by markmhx** [comment]
The login with Blockstack feature of this page doesn't work basically: https://contribute.blockstack.org/login

We realized after discussing on the browser call and creating this issue, however, that the above page is actually managed by a different platform, so I'm going to ask the growth team internally about this.
