### ISSUE TITLE
Text strangeness in updated App.co card

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#766]
![Screen Shot 2019-04-10 at 5:37 PM](http://marker.screenshots.prod.s3.amazonaws.com/c51690efc0a04ba88bcc6b0bd100332c-10000x10000-1554917830737.png)
---
### More Info

**Source URL**: [https://deploy-preview-761--blockstack.netlify.com/](https://deploy-preview-761--blockstack.netlify.com/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 73.0.3683.86</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>1554 x 1362</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by aulneau** [comment]
fixed with https://github.com/blockstack/blockstack.org/pull/761/commits/ff776dc669e757e180dcf506e6fffdf32809c515
