### ISSUE TITLE
Update papers page

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#767]
“Blockstack PBC has a draft of whitepaper 2.0 that is currently being reviewed by relevant experts. Stacks Improvement Proposal (SIP) for the new consensus algorithm and smart contract language are respectively available as SIP-001 and SIP-002.

The Blockstack technology has evolved a lot in the last 2 years and the papers listed below don’t fully reflect the current decentralized computing stack.”

**Comment by aulneau** [comment]
resolved with https://github.com/blockstack/blockstack.org/pull/761/commits/c0d39da9674822a97c5578c7e12cdedcd1a92c7b
