### ISSUE TITLE
Press revision and addition

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#768]
Press: two additions:

1. https://www.coindesk.com/blockstack-crypto-winter-funding-token (we can drop the other Coindesk article about Two Big Crypto Startups)
2. http://fortune.com/2018/06/08/blockchain-silicon-valley-new-internet-blockstack/

**Comment by aulneau** [comment]
resolved with https://github.com/blockstack/blockstack.org/pull/761/commits/a43b55e573318c9e6500799e22d5df31e72f4348
and https://github.com/blockstack/blockstack.org/pull/761/commits/84d4326c40ecf7f420087e4a5984cfbf8fdefda5

**Comment by jeffdomke** [comment]
One edit here, don't think we need to drop the old/current Fortune article. We can add that one back in and get 9 posts.
