### ISSUE TITLE
Remove the slashes

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#769]
![Screen Shot 2019-04-10 at 10:18 PM](http://marker.screenshots.prod.s3.amazonaws.com/1c80bf7926b44718bfd4778e1817756c-10000x10000-1554934689531.png)
---
### More Info

**Source URL**: [https://blockstack.org/roadmap/](https://blockstack.org/roadmap/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 73.0.3683.86</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>1604 x 1091</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by jeffdomke** [comment]
Occurs 4 or 5 places anyplace with $

**Comment by aulneau** [comment]
resolved with https://github.com/blockstack/blockstack.org/pull/761/commits/7670da5fd5b273eb58ac75794f1f33f0699a861a
