### ISSUE TITLE
Live apps go to app mining latest

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#770]
1. Top section: View all live Blockstack dapps
2. Live apps in menu
3. Footer Live apps

And anyplace else.

**Comment by aulneau** [comment]
resolved with https://github.com/blockstack/blockstack.org/pull/761/commits/3b4f83ae3d1b001b55f1ced775a2d0c6667d0803

**Comment by markmhx** [comment]
This doesn't appear to be auto-updating to the _latest_ latest.

I'm seeing it link to [the March results](https://app.co/mining/march-2019) for example even though [April is now available](https://app.co/mining/april-2019).
