### ISSUE TITLE
Link changes on About

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#773]
![Screen Shot 2019-04-10 at 11:54 PM](http://marker.screenshots.prod.s3.amazonaws.com/ee285afe93ae4366a7aa2b27162055d2-10000x10000-1554940454798.png)

Blockstack apps already in production --> App Mining page

---
### More Info

**Source URL**: [https://deploy-preview-761--blockstack.netlify.com/about/](https://deploy-preview-761--blockstack.netlify.com/about/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 73.0.3683.86</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>1642 x 1177</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by jeffdomke** [comment]
Killed the change on funding.

**Comment by jeffdomke** [comment]
Sorry meant this page: https://app.co/mining/march-2019

**Comment by aulneau** [comment]
resolved with https://github.com/blockstack/blockstack.org/pull/777/commits/31efcc39cc764682fcf99e6fbe003119c6c92c8b
