### ISSUE TITLE
[Home] first section links

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack.org#782]
<img width="1055" alt="Screen Shot 2019-05-03 at 4 33 01 PM" src="https://user-images.githubusercontent.com/11803153/57166884-2d70e580-6dc1-11e9-8ddb-8565c749fd06.png">

Where does learn more go?

**Comment by aulneau** [comment]
cc @jeffdomke @moxiegirl

**Comment by jeffdomke** [comment]
The Blockstack ID page / try Blockstack page, sorry not sure what the route will be there.

**Comment by moxiegirl** [comment]
I have this page:

https://docs.blockstack.org/browser/ids-introduction.html
