### ISSUE TITLE
[Home] Case studies

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack.org#783]
We have three case studies on the homepage, where do they live? (need links)

**Comment by aulneau** [comment]
@jeffdomke what are the status of these?

**Comment by jeffdomke** [comment]
https://www.wired.com/story/santiago-siri-radical-plan-for-blockchain-voting/

https://blog.producthunt.com/how-this-maker-quit-his-job-and-made-his-side-projects-profitable-in-1-year-9c24ece56133

https://www.indiehackers.com/interview/how-taking-back-my-privacy-inspired-a-product-that-became-a-business-bd931dfc1d
