### ISSUE TITLE
[About] Determine hero links / photos

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack.org#786]
Currently we have a grid of content that contains links to various articles/other things we want to show.

There are some filled in, with others missing. 

<img width="1654" alt="Screen Shot 2019-05-03 at 4 27 27 PM" src="https://user-images.githubusercontent.com/11803153/57166659-7ecca500-6dc0-11e9-9c1a-5a8cb097a80b.png">

**Comment by jasperjansz** [comment]
Tedx: https://www.youtube.com/watch?v=qtOIh93Hvuw
NYT: https://www.nytimes.com/2018/04/01/technology/blockchain-uses.html
Wired: https://www.wired.com/story/the-decentralized-internet-is-here-with-some-glitches/
Economist (may be added, but need to make a custom image for this one): https://www.economist.com/special-report/2018/06/28/blockchain-technology-may-offer-a-way-to-re-decentralise-the-internet
