### ISSUE TITLE
[Technology] Grid items need links

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack.org#794]
![Screen Shot 2019-05-08 at 4 00 35 PM](https://user-images.githubusercontent.com/11803153/57408131-730b2500-71aa-11e9-9df8-3f045281140a.png)

**Comment by aulneau** [comment]
@jeffdomke @moxiegirl where should each of these links go?

**Comment by jeffdomke** [comment]
Authentication = Tech page
Data storage = Tech page
App Funding = app.co/mining
Users = Try Blockstack / Blockstack ID page
Community = community.blockstack

**Comment by moxiegirl** [comment]
@jeffdomke ultimately, we likely need to send them outside the blockstack.org flow. It is kind of circular and confusing to send them to learn links that go to promo pages. YMMV -- your mileage may vary of course.

Authentication = [Understand Blockstack Auth](https://docs.blockstack.org/develop/overview_auth.html)
Data storage = [A decentralized storage architecture](https://docs.blockstack.org/storage/overview.html) [Work with Storage](https://docs.blockstack.org/develop/storage.html)
App Funding = app.co/mining or the guide [App Miners Guide](https://docs.blockstack.org/community/app-miners-guide.html)
Users = Try Blockstack / Blockstack ID page or [Get and use a Blockstack ID](https://docs.blockstack.org/browser/ids-introduction.html)
Community = community.blockstack

**Comment by aulneau** [comment]
@jeffdomke these items are on the tech page, so we need some external links. I think what @moxiegirl is suggesting makes sense.

**Comment by jeffdomke** [comment]
Makes sense I think I just spaced that the user was already on the tech page.
