### ISSUE TITLE
Navigation Structure

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack.org#800]
There has been some debate over the structure of the navigation. We need to determine the top level links and their children.

**Comment by moxiegirl** [comment]
![image](https://user-images.githubusercontent.com/1347209/57792262-6aa77280-76f3-11e9-85f1-3027ca25e753.png)

## LInks detailed

| Technology |  | Resources |  |  |  |
|-----------------------|-------------------------------------------|------------------|---------------------------------------------------------------|--------------------------------|-------------------------------------|
| Create an ID | https://browser.blockstack.org/ | FAQs | https://docs.blockstack.org/faqs/allfaqs |  |  |
| Sign In | https://browser.blockstack.org/ | Zero-to-DApp | https://docs.blockstack.org/develop/zero_to_dapp_1.html |  |  |
| Find DApps | https://app.co/ | DApp user guides | https://docs.blockstack.org/browser/browser-introduction.html |  |  |
| App mining | https://app.co/mining | Developer guides | https://docs.blockstack.org/develop/dapp_principles.html |  |  |
| Stacks Wallet | https://wallet.blockstack.org/ | App mining guide | https://docs.blockstack.org/ |  |  |
| Blockchain explorer | https://explorer.blockstack.org/ | All the docs | https://docs.blockstack.org/ |  |  |
| Whitepapers | https://blockstack.org/papers/ | Support |  |  |  |
| Roadmap | https://blockstack.org/roadmap/ |  |  |  |  |
|  |  |  |  |  |  |
|  |  |  |  |  |  |
| Community |  | About |  | Subscribe to udpates |  |
| Join the community | https://community.blockstack.org/ | Company | https://blockstack.org/about/ |  |  |
| Forum | https://github.com/blockstack | Careers | https://blockstack.org/careers/ |  |  |
| Slack | http://chat.blockstack.org/ | Public Offering | ??? | Blog | https://blockstack.org/blog |
| Meetup | https://www.meetup.com/topics/blockstack/ | Events | http://community.blockstack.org/events | Press | https://blockstack.org/press/ |
| Telegram | https://t.me/BlockstackChat | News | http://community.blockstack.org/news | Branding | https://branding.blockstack.design/ |
| Telegram (characters) | https://t.me/BlockstackChinese | Contact | http://community.blockstack.org/contact | Swag | https://blockstack.myshopify.com/ |
|  |  |  |  |  |  |
|  |  |  |  |  |  |
|  |  |  |  | https://twitter.com/blockstack | https://github.com/blockstack |

**Comment by moxiegirl** [comment]
@jeffdomke @aulneau @jasperjansz see prototype screen cap and link references table.

**Comment by jeffdomke** [comment]
`Technology` missing.

**Comment by aulneau** [comment]
Do you mean as the header or as an Item? I saw with Mary's edit, the technology and try blockstack pages weren't included, so I kept the previous title of the first column as `Blockstack` and put the tech and try pages under there.

**Comment by aulneau** [comment]
![Screen Shot 2019-05-21 at 8.58.46 AM.png](https://images.zenhubusercontent.com/5c0160f25cb43a45a18af171/41f054db-b1e4-4c9b-80dd-042444ace9ab)

**Comment by moxiegirl** [comment]
@aulneau @jeffdomke We discussed in the meeting that the header need not match the footer.  *Blockstack* as a heading is meaningless as a category the entire **_site_** is about Blockstack. That's why I used _**Technology**_ in the footer --- they are all aspects of our technology.
