### ISSUE TITLE
Add the ability to single source (currently updating the FAQs takes 2 team members)

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack.org#808]
The current blockstack.org backend is not pulling the FAQs in any automated fashion.  App.co uses a backend that pulls from the JSON file for the FAQ in real time. 

This is a static site and it is not doing that so each small change to the FAQs is not doing that. We need to look at automating either the build so that it rebuilds say nightly, or automated so that that build can launch after docs, or making the JSON pull in real time.

**Comment by aulneau** [comment]
cc @kantai 

We don't allow for this to happen because we always want to ensure that we are authorizing the update of the site each time. Aaron can speak more to it, however.

**Comment by kantai** [comment]
Yep, that's pretty much right, we want to make sure that any update to the site (blockstack.org) is authorized. We've explored alternatives in the past, but have never made a big push to prioritize simplifying our process while maintaining the necessary amounts of control. We can explore alternatives as well, but when it comes to infrastructure-related discussions, we should conduct those in a non-public forum, so I'm closing this issue.
