### ISSUE TITLE
New Opengraph images

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack.org#809]
With the new design we need updated open graph images.

It would be cool to have ones for the big pages: home, about, careers, technology, try-blockstack, but a sensible default would be fine too.

**Comment by jeffdomke** [comment]
Just checked this on staging: https://og.blockstack.sh/Blockstack.png?theme=dark&md=1&fontSize=150px

Is this the updated design? If so, please explore a few other options. And the icons/logos are out of date.

**Comment by aulneau** [comment]
> And the icons/logos are out of date.

I'm not sure what you mean, this is our most up to date logo

**Comment by jeffdomke** [comment]
home = "Decentralized computing network and app ecosystem" 

/technology/ = "Easily build blockchain apps that scale" 

/try-blockstack/ = "Apps that protect your digital rights" 

/about/ = "Leading the way to a blockchain computing era"

**Comment by jeffdomke** [comment]
Is it possible to 1) Update the typeface to IBM? And increase the margin, so the text isn't almost touching the edge of the blue box? 

![Screen Shot 2019-05-28 at 2.47.33 PM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/9a979001-4995-4df4-af48-bf0f8f11b970)

**Comment by jeffdomke** [comment]
Nice. Moving to done 👌
