### ISSUE TITLE
Found issues in blockstack.org new home page

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack.org#810]
## https://deploy-preview-804--blockstack.netlify.com/

* **Build Apps** > **Build apps**  consistency, sentence case in all other buttons 
* Blockchain computing platform and app ecosystem > Create ID is a 404
* Secure your identity and data with Blockstack ID > Learn more is a 404 
* Unclear antecedent here, I get it is marketing language but the which does make it clearer

> We provide an online identity with blockchain-based security and encryption — protecting your data from big internet companies.

We provide an online identity with blockchain-based security and encryption, which protects your data from big internet companies.

Switch the mdash:

> Everything you need, from auth to data storage, ready and in production. 100% Javascript — zero backend development.

Everything you need, from auth to data storage, ready and in production —  100% Javascript and zero backend development.

Numbers under 10 spell out like you did with zero elsewhere

> How this Maker quit his job and made his side projects profitable in 1 year

How this Maker quit his job and made his side projects profitable in one year

_Design Comments_

Having the **Learn more** here go to the same place as **Create ID** isn't a good thing.  We should consistently use one or the other --- otherwise we set users. *Learn More* should likely go to docs or some kind of written thing.

 We are doing something similar with **Build blockchain-powered apps in as little as an hour** -> **Learn More** 

## https://deploy-preview-804--blockstack.netlify.com/about/

404
![image](https://user-images.githubusercontent.com/1347209/57885338-930c9b00-77df-11e9-8fe7-ca9b37981bc8.png)

Twitter 403:

![image](https://user-images.githubusercontent.com/1347209/57885388-afa8d300-77df-11e9-8281-47eddc15af51.png)

## https://deploy-preview-804--blockstack.netlify.com/technology/

**Blockstack is better for app builder > Users > Learn more** is a 404

also:

![image](https://user-images.githubusercontent.com/1347209/57886036-2f836d00-77e1-11e9-875d-c090e31f478e.png)

**Comment by aulneau** [comment]
The 404s you mention don't seem to be an issue anymore.

Also moving forward @moxiegirl can you create individual tickets per issue? It's a bit hard as it is currently formatted to work on them.

**Comment by aulneau** [comment]
these should be resolved
