### ISSUE TITLE
Link styles don't match figma

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#815]
[![Screenshot_2019-05-17_15-41-05.png](https://mrkr.io/s/5cded6116f65e75a95969b1a/2)](https://mrkr.io/s/5cded6116f65e75a95969b1a/0)
---
### More Info

**Source URL**: [https://deploy-preview-804--blockstack.netlify.com/technology/](https://deploy-preview-804--blockstack.netlify.com/technology/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 73.0.3683.86</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>1504 x 1158</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by aulneau** [comment]
I have spoken with Jasper about this directly. He can chime in cc @jasperjansz
