### ISSUE TITLE
/technology/ - Main Tutorials CTA not functional

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#816]

**Comment by jeffdomke** [comment]
Shouldn't it go to Zero to Dapp? That is our main tutorial right?

**Comment by aulneau** [comment]
But we have a link to zero to dapp right above it?

**Comment by moxiegirl** [comment]
@aulneau is correct. I think in some cases we should send them direct to Zero-to-Dapp but not in all. The best "top of the tutorials" I think is https://docs.blockstack.org/browser/hello-blockstack.html
