### ISSUE TITLE
Photo is bad. Better one in figma. 

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#822]
[![Screenshot_2019-05-17_17-25-54.png](https://mrkr.io/s/5cdeeea1a97ee759faff582c/2)](https://mrkr.io/s/5cdeeea1a97ee759faff582c/0)
---
### More Info

**Source URL**: [https://deploy-preview-804--blockstack.netlify.com/](https://deploy-preview-804--blockstack.netlify.com/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 73.0.3683.86</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>1300 x 1050</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by aulneau** [comment]
@jeffdomke which photo?

**Comment by jeffdomke** [comment]
I assigned to Jasper he can figure it out

**Comment by jeffdomke** [comment]
Commented in Figma. Options, and a unified approach, would be helpful.
