### ISSUE TITLE
Top nav icons

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#826]

**Comment by markmhx** [comment]
Does this issue refer to the need to add icons here in the menu's sub-menus such as here?

<img width="688" alt="Screen Shot 2019-05-21 at 18 15 36" src="https://user-images.githubusercontent.com/28991/58112773-72d04800-7bf4-11e9-9ac0-37c78dffb874.png">

**Comment by jasperjansz** [comment]
@jeffdomke yes

**Comment by jeffdomke** [comment]
Don't see these on stage. I'm assuming the icons are done but not implemented? LMK i can reassign to @aulneau etc.

**Comment by jasperjansz** [comment]
Designed, not implemented
