### ISSUE TITLE
Suggestion: Start screen with TED image at far left

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#827]
[![Screenshot_2019-05-17_17-32-41.png](https://mrkr.io/s/5cdef039a97ee759faff5830/2)](https://mrkr.io/s/5cdef039a97ee759faff5830/0)
---
### More Info

**Source URL**: [https://deploy-preview-804--blockstack.netlify.com/about/](https://deploy-preview-804--blockstack.netlify.com/about/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 73.0.3683.86</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>1300 x 1050</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by aulneau** [comment]
To have it on the far left is not always ideal, as at certain screen sizes, a user would never be able to see the item.

**Comment by jeffdomke** [comment]
Cool, we can close, at certain screen sizes it feels very odd and like a glitch.
