### ISSUE TITLE
Bar prompting to token offering

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#829]

**Comment by jeffdomke** [comment]
What is the deal with the placeholder text? Is this hellobar?

**Comment by aulneau** [comment]
I asked a question re: statements and disclaimers. This is public, so I didn't want to put anything on there that wasn't checked first.

**Comment by jeffdomke** [comment]
The copy from figma isn't right. Suggest: "Learn about the upcoming Stacks token sale"

**Comment by jeffdomke** [comment]
Why did you use the other copy? Please give bar a few more vertical pixels. 

Should this persist when user scrolls up the page with the main nav?

**Comment by aulneau** [comment]
I used the copy that Freddie provided.

> Should this persist when user scrolls up the page with the main nav?

We spoke about this before and thought we decided that it should not. I can make it so if you would prefer that.

**Comment by jeffdomke** [comment]
No persist is fine. 

We should use my copy. Same message 1/2 the words.

**Comment by aulneau** [comment]
I think this is a good combo:

> Learn about the anticipated Stacks Token sale
