### ISSUE TITLE
Photo scaling animation

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#830]
Find the animation a bit much. Doubly so when the container rises + the photo zooms. Suggest sorting this out so only one or the other happens. Seems like we have examples where one or the other or both occurs.

**Comment by aulneau** [comment]
Can you be more specific with which animation on which page you are referencing?

**Comment by aulneau** [comment]
@jeffdomke see comment above

**Comment by jeffdomke** [comment]
![2019-05-20 15-39-49.2019-05-20 15_40_31.gif](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/19d80eaf-a3f8-46d1-b092-ce2f221e446c)

Look at that Justin dance!
