### ISSUE TITLE
Click blockstack logo doesn't return to homage

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#837]
**Issue Type (check one)**

- [ ] Bug Report
- [ ] Feature Idea
- [ ] Technical Discussion
- [ ] Question / Other

**Comment by jeffdomke** [comment]
Not working on stage?

**Comment by aulneau** [comment]
It does work, there is a delay currently because we are fetching some blog data and the API is very slow. I have to cache/write a small service to make it faster.

**Comment by aulneau** [comment]
because this ticket is simply about if the logo goes home or not, i am closing it. there is another ticket to speed up navigation to homepage
