### ISSUE TITLE
Rethink graphic for mobile or edit

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#840]
[![Screenshot_2019-05-18_20-01-49.png](https://mrkr.io/s/5ce064ad4f305b5a6560b679/2)](https://mrkr.io/s/5ce064ad4f305b5a6560b679/0)
---
### More Info

**Source URL**: [https://deploy-preview-804--blockstack.netlify.com/technology/](https://deploy-preview-804--blockstack.netlify.com/technology/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 74.0.3729.108</td></tr><tr><td><strong>Screen Size</strong></td><td>400 x 1014</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>2205 x 1221</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

**Comment by jeffdomke** [comment]
On prod still blurry, if this is a thing for Thomas please reassign.

**Comment by jasperjansz** [comment]
There is a specific mobile solution for this section: https://www.figma.com/file/LDiZPndnqfRjZnwTIMCzNMjr/Website?node-id=1546%3A1644

I am not seeing any blur. However, it would be a big improvement if we can move the section after the hero up on mobile:
![Screenshot 2019-07-19 at 15.22.16.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/8815afca-352c-42eb-ab58-0493f75afe14)

**Comment by jeffdomke** [comment]
Think this is still pretty unsuccessful. On mobile this graphic – black phone and the tiniest bit of code take up nearly the entire screen. And don't really say much. Think we should explore better solutions, ones that take up less space and communicate stronger.
