### ISSUE TITLE
Speed up navigation to homepage

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#843]
When I click the site menu's "Blockstack" logo to navigate home, it often takes several seconds with no loading indicator, suggesting that the link is completely broken. We should either speed up this behavior or add a loading indicator.

<img width="230" alt="Screen Shot 2019-05-21 at 18 11 05" src="https://user-images.githubusercontent.com/28991/58112440-d148f680-7bf3-11e9-8b44-c6556a29a4c9.png">

**Comment by aulneau** [comment]
fixed with https://github.com/blockstack/blockstack.org/pull/923/commits/916aed670b286fb34918894db65a2091903ff140

**Comment by jeffdomke** [comment]
On stage I'm not seeing any improvement?

**Comment by aulneau** [comment]
Check https://blockstack.org

**Comment by markmhx** [comment]
This transition is now stalling for me entirely in production:

<img width="1424" alt="Screen Shot 2019-06-04 at 14 06 40" src="https://user-images.githubusercontent.com/28991/58877798-fe0c0c00-86d1-11e9-8b37-6318871d3dda.png">

**Comment by aulneau** [comment]
@markmhx I am not able to recreate this. Will close this for now, but if it comes up again, please make a new issue. Thanks!

**Comment by markmhx** [comment]
This appears to be working for me now as well.
