### ISSUE TITLE
Add placeholder text for footer email input

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#845]
The "Stay up to date" input has no placeholder so I'm assuming I put my email address...but not really sure?

<img width="218" alt="Screen Shot 2019-05-21 at 18 14 03" src="https://user-images.githubusercontent.com/28991/58112684-487e8a80-7bf4-11e9-852a-19a817ed0b20.png">

**Comment by jeffdomke** [comment]
Dupe I believe.

**Comment by markmhx** [comment]
This appears resolved on staging in any case.
