### ISSUE TITLE
Add spacing between home sections

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#846]
These two sections look vertically very snuggly, especially compared to others on the page:

<img width="1235" alt="Screen Shot 2019-05-21 at 18 14 47" src="https://user-images.githubusercontent.com/28991/58112726-5c29f100-7bf4-11e9-90b9-bd80dd6c9978.png">

**Comment by aulneau** [comment]
This is technically one section, but it should get a bit more padding which I will add

**Comment by jeffdomke** [comment]
Looks the same as before?
