### ISSUE TITLE
Fix "Create ID" button

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#850]
This button currently doesn't do anything on the "Try Blockstack" page's hero:

<img width="613" alt="Screen Shot 2019-05-21 at 18 21 34" src="https://user-images.githubusercontent.com/28991/58113214-51bc2700-7bf5-11e9-982d-63e33ec489b0.png">

**Comment by jeffdomke** [comment]
Think this is also a dupe.

**Comment by markmhx** [comment]
This appears fixed on the latest staging in any case.
