### ISSUE TITLE
Improve App.co tagline on about pgae

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#852]
I'm pretty sure we don't want to say it's "real-time funding"? Or should we call this "App Mining" and link to the mining page on App.co?

<img width="501" alt="Screen Shot 2019-05-21 at 18 24 36" src="https://user-images.githubusercontent.com/28991/58113447-cd1dd880-7bf5-11e9-8ccd-a5e6f08ad2f7.png">

**Comment by aulneau** [comment]
This has been resolved
