### ISSUE TITLE
Add download icon to native browser options

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#853]
It seems we want these listings to be more directly actionable instead of leaving it up to the visitor to associate the buttons above for "Create ID" and "Sign In".

Can we link these to each OS's build? Or take the user to the install page?

<img width="621" alt="Screen Shot 2019-05-21 at 18 26 26" src="https://user-images.githubusercontent.com/28991/58113568-18d08200-7bf6-11e9-9b03-6728bd4b288d.png">

**Comment by jeffdomke** [comment]
@markmhx sorry not understanding what you mean?

**Comment by markmhx** [comment]
It appears this was partially resolved by https://github.com/blockstack/blockstack.org/issues/833, since when I initially created this issue, these listings weren't linked. Now they appear linked in staging.

If each of these browser options is intended to link to each OS build, then perhaps we don't need to add an additional CTA near them (e.g. "Download browser", which could take the user to https://blockstack.org/install).

However, given that these are descriptive and not imperative listings (e.g. "Browser Web" not "Download Browser Web"), it may not be the most intuitive that the user can click them to download.

I might suggest that we change the arrow icon beside the MacOS, Windows and Linux options with a download icon (e.g. https://fontawesome.com/icons/download?style=solid) since that would indicate the actionability better. The arrow icon could remain for Web since it does indicate decently that it'll open in a new tab when clicked.

**Comment by jeffdomke** [comment]
This makes sense now. I would suggest we make this change or something similar.
