### ISSUE TITLE
Link whitepapers

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack.org#854]
Currently they're un-actionable. Also maybe "View whitepaper" may be a more expressive CTA for each?

<img width="691" alt="Screen Shot 2019-05-21 at 18 28 36" src="https://user-images.githubusercontent.com/28991/58113632-49182080-7bf6-11e9-9a2f-69927343cc53.png">

**Comment by jeffdomke** [comment]
Should be covered by the stacks token page build but just in case.
