### ISSUE TITLE
H2 letter-spacing

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#855]
Here's what I've used in Figma:

# On H2's:
e.g.
![Screenshot 2019-05-23 at 14.41.06.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/695feb16-0b06-4d7d-a64a-99f9edec8212)
![Screenshot 2019-05-23 at 14.43.57.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/0202332d-5af5-4b9e-ac8f-54e3c5c680a2)

letter-spacing: -0.6px

Seems to work with the grid and look better when I change it in Chrome

**Comment by jeffdomke** [comment]
![Screen Shot 2019-05-23 at 5.34.44 PM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/17e2d214-270c-482f-9714-696ba16427e9)

Pretty sure this applies to all headers but the change is only visible in that one section.

**Comment by aulneau** [comment]
@jeffdomke  why are you having a question mark on it. I had originally made the kerning tighter so that the line breaks reflected figma. Jasper said to change it to something less dense than what I had, which will result in line breaks not matching up as they are in figma.

**Comment by jeffdomke** [comment]
Just went back and inspected everything. You are right. Closing.
