### ISSUE TITLE
Menu styling

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#857]
1. Right side misaligned with page:
![Screenshot 2019-05-23 at 14.51.48.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/8378ca49-a709-4851-b598-8a499a7c954b)

2. suggest using Caption (14px) for menu labels, it will look less cramped and be visually aligned with the footer. See screenshot (top = current implementation, middle and footer = design)

![Screenshot 2019-05-23 at 14.56.11.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/8c4d493d-9161-4ec9-8e3a-aa327c49dba5)

3. Then we can also decrease the height of the menu to 64px. It will look more subtle that way.

4. I think the Indigo logo on white looks better (my bad for making it black once...)

**Comment by jeffdomke** [comment]
I'm still seeing the misalignment mentioned on `1` on prod.

**Comment by jeffdomke** [comment]
Shouldn't this state not be possible? 

![Screen Shot 2019-06-05 at 5.19.08 PM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/14b44014-d2c4-4b94-9b89-6eddf8688be5)

**Comment by aulneau** [comment]
Whoops my mistake didn't realize that. The reason that is the case is because the buttons themselves take up the remaining space but are centered equally in the 6 sections. I can play around with how to make it aligned to the right.
