### ISSUE TITLE
Try blockstack / Blockstack ID visual

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#860]

**Comment by jasperjansz** [comment]
@aulneau I've tweaked this visual to match the style of the one we have on the homepage.

**Comment by jeffdomke** [comment]
Not sure what I'm checking here?

**Comment by aulneau** [comment]
the graphic was changed from

![image.png](https://images.zenhubusercontent.com/5c0160f25cb43a45a18af171/17693012-72f7-4d93-a26b-d1b771f54458)

to this

![image.png](https://images.zenhubusercontent.com/5c0160f25cb43a45a18af171/78d0a92a-c260-4aec-b67a-a7a0d530a606)
