### ISSUE TITLE
2 Menu improvements

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#866]
## Logo size

The menu label line-height is 20px. If we make the logo the same height they will be aligned and more proportional in size.

As you'll see they're currently misaligned:
![Screenshot 2019-05-24 at 11.40.11.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/b620fc15-60f7-4114-9617-b925e55015bf)

## Label letter-spacing
The letter-spacing of the menu labels is currently not the same as the letter-spacing we use elsewhere at 14px. See screenshot where you can see the difference between the menu labels and the footer + browser options.

**Comment by jeffdomke** [comment]
@jasperjansz please clear this
