### ISSUE TITLE
Try Blockstack mobile: app cards not visible

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#868]
![Screenshot 2019-05-24 at 14.36.17.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/cb7fe817-8b70-4fe3-a50c-9275f24e5e09)

Only see part of 2 cards when scrolling past it

**Comment by jeffdomke** [comment]
@jasperjansz please clear this
