### ISSUE TITLE
Mobile footer: too little spacing between bottom links

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#869]
These are hard to tap correctly because of how close together they are.![Screenshot 2019-05-24 at 14.37.28.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/87f86f64-c75a-42b5-b0cb-ade9d0175d2b)

Suggest implementing like the design, or increasing the margins between the rows.![Screenshot 2019-05-24 at 14.37.44.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/925b14c1-52d2-4465-80c0-16a62439d8ce)

**Comment by jeffdomke** [comment]
@jasperjansz please clear this
