### ISSUE TITLE
Try Blockstack mobile: align buttons and text in the CTA

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#873]
Looks strange to have the buttons centered and the text left-aligned. Suggest either aligning the buttons to the left or making them 100% width

![Screenshot 2019-05-24 at 14.45.37.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/b4f41a6d-c888-44c4-a42d-676a9fa7b457)

**Comment by jeffdomke** [comment]
@jasperjansz please clear this
