### ISSUE TITLE
About mobile: 3x margins

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#874]
1. Margin between title and text too small.

![Screenshot 2019-05-24 at 14.47.03.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/585328e0-ba77-40fc-8948-a8b53eba641d)

2. Margin between title and text too small.

![Screenshot 2019-05-24 at 14.47.20.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/6619693f-bf64-46ac-b6fd-72449c58ecc4)

3. Margins between cards too small
 
![Screenshot 2019-05-24 at 14.47.27.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/dccc6d27-7a46-42e3-ba3f-87ff5ffa13eb)

**Comment by jeffdomke** [comment]
@jasperjansz please clear this
