### ISSUE TITLE
Improve "share move connect data" graphic

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#878]
[![Screenshot_2019-05-24_15-19-55.png](https://mrkr.io/s/5ce80b9b6e004d65f2f65a40/2)](https://mrkr.io/s/5ce80b9b6e004d65f2f65a40/0)
---
### More Info

**Source URL**: [https://deploy-preview-804--blockstack.netlify.com/try-blockstack/](https://deploy-preview-804--blockstack.netlify.com/try-blockstack/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 74.0.3729.157</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>2315 x 1255</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by jeffdomke** [comment]
Shared more in depth feedback in figma

**Comment by jasperjansz** [comment]
duplicate issue, closing.
