### ISSUE TITLE
[Homepage] Video stills too dark, low resolution, and low saturation

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#879]

**Comment by jeffdomke** [comment]
Not sure what to test here

**Comment by jasperjansz** [comment]
@aulneau I have improved the video stills of the video section of the homepage: https://www.figma.com/file/LDiZPndnqfRjZnwTIMCzNMjr/Website?node-id=1393%3A12632

Currently, the stills of our video section have unnecessarily heavy overlays. I've also tweaked some to look better (e.g. more color and contrast on the Ari Paul one, remove white light on the hairs on the top of Muneeb's head).

You should be able to take the pictures right from Figma. There's only two that include an overlay (the two from Muneeb).

**Comment by jeffdomke** [comment]
I can't see any change here on stage?

**Comment by aulneau** [comment]
The images used are directly from figma, with no overlay. I'm not sure why
it would be different for you.

**Comment by jasperjansz** [comment]
Perhaps it's compression you're using?
