### ISSUE TITLE
Wasted space, outdated stories on homepage

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack.org#881]
There are a lot more recent stories published that are more relevant, also the space on the left is pretty large, easy to gloss over the link to 'View all news'. This seems like a good place to pull in the featured image of whatever top story we want. 

![image](https://user-images.githubusercontent.com/6131188/58344277-1a729380-7e0a-11e9-966d-b814a95bb641.png)

**Comment by cuevasm** [comment]
Combined with the section below going all the way to the left, it looks off balance.

**Comment by aulneau** [comment]
cc @jasperjansz

**Comment by jeffdomke** [comment]
I think this looks fine, but sure. @cuevasm try to split up each problem. Pretty sure the stale posts is just staging env. issue, but if I'm wrong please speak up @aulneau
