### ISSUE TITLE
Homepage videos - suggest modal

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack.org#882]
The videos port you out to YouTube where you may never come back from, I would suggest they play in a modal so people stay on the site.

**Comment by jeffdomke** [comment]
![Screen Shot 2019-06-05 at 5.17.13 PM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/6e40eea6-e746-4beb-a925-0bd4c0b4824b)

There are some screen sizes that result in the video close off screen. This example is from Chrome.

**Comment by jeffdomke** [comment]
Result = youtube play button?
Expected = autoplay upon clicking.

**Comment by aulneau** [comment]
@jeffdomke this now autoplays when open
