### ISSUE TITLE
Hyperlink underlines on /technology are up to high and being covered by words

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack.org#893]
![image](https://user-images.githubusercontent.com/6131188/58349123-4a746380-7e17-11e9-94f8-e963d3fa0fa9.png)

**Comment by aulneau** [comment]
@cuevasm I am not able to recreate this, is this still happening on blockstack.org?

**Comment by cuevasm** [comment]
Yes, Windows, latest version of Chrome (including incognito) 
![image](https://user-images.githubusercontent.com/6131188/59708267-41c64180-91b9-11e9-9013-ae8109c828d9.png)

Happens in Firefox too: 
![image](https://user-images.githubusercontent.com/6131188/59708325-63272d80-91b9-11e9-80f6-d8626da6d812.png)

and Brave:
![image](https://user-images.githubusercontent.com/6131188/59708380-84881980-91b9-11e9-973b-f3ffa49ccb70.png)
