### ISSUE TITLE
Alignment of this section on /technology is off

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack.org#895]
![image](https://user-images.githubusercontent.com/6131188/58349178-6d9f1300-7e17-11e9-8804-693108b3421e.png)

I would start the left column further in so there isn't so much empty space on the right and so the change from centered to left-aligned content isn't as harsh

**Comment by jeffdomke** [comment]
Looking at this you're on windows or something? Need env. data to really fix this @cuevasm

**Comment by cuevasm** [comment]
Windows, latest build of Chrome
![image](https://user-images.githubusercontent.com/6131188/58358717-ed87a600-7e34-11e9-81fb-fd40d25544d8.png)

(there are some nice bug reporting platforms that make point-click feedback easy and auto include system info in the ticket and integrate with github if you're ever interested.)

I already mentioned this, but I find it time-consuming and tedious to provide feedback this way vs. even just invision or redpen. Much respect to your process, I will work on your terms but I think we can simplify and you'd get a lot more feedback from the team (that would be less redundant and you could have conversations around copy right there on one thread vs. in multiple issues and so forth). My two cents, for next time, I know we're in a rush
