### ISSUE TITLE
/about page artifact and alignment

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack.org#899]
![image](https://user-images.githubusercontent.com/6131188/58349818-26198680-7e19-11e9-9c6b-3fa7cfc9cb1f.png)

**Comment by jeffdomke** [comment]
Thx @cuevasm can you please share your browser/platform?

**Comment by cuevasm** [comment]
Windows, Chrome

Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by aulneau** [comment]
The character is from a soft return added in figma and copied over. Thanks for catching it. I won't be aligning the logos as it's not super straightforward to so right now, but will come back to it.
