### ISSUE TITLE
Swap out video content

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#900]
Feature podcast with Ari Paul (BlockTower CIO) vs Naval Ravikant and Ryan talk (will need an image featuring Ari Paul — maybe pull one where he was speaking at one of our summits).

**Comment by cuevasm** [comment]
Looking for more if this one doesn't work: 
![maxresdefault (2)](https://user-images.githubusercontent.com/6131188/58351529-ddb09780-7e1d-11e9-8b32-e9ed12674981.jpg)

**Comment by shanvoight** [comment]
I just looked through the 25 or so we have of Ari from Berlin and the image above is one of the better shots. He either has his eyes closed or the image of him is blurry but focused on Nader. Here are a few more if you prefer one of these instead? 
![Ari Paul panel](https://user-images.githubusercontent.com/29715942/58352878-e6fc2d00-7e3a-11e9-81bc-516838a7d02b.jpg)
![Ari Paul and Nader](https://user-images.githubusercontent.com/29715942/58353293-1f503b00-7e3c-11e9-896c-7e8345d09c4c.jpg)
![Ari Paul and Nader2](https://user-images.githubusercontent.com/29715942/58353300-224b2b80-7e3c-11e9-8817-85efd42f8266.jpg)

**Comment by jeffdomke** [comment]
@cuevasm thank you. I think the image is fine. I was hoping you could help me find the media (podcast?) he is referencing? Assume it is posted online someplace?

**Comment by cuevasm** [comment]
Ah sure, sorry I just thought you need an image, here you go! https://stacks.co/podcast/episodes/2
