### ISSUE TITLE
Copy edit

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#901]
"We provide an online identity with blockchain-based security and encryption — protecting your data from big internet companies."

Change to: 

"We provide private data lockers and a universal login with blockchain-based security and encryption — protecting your data from big internet companies."

**Comment by jeffdomke** [comment]
Wrong copy is on staging.

**Comment by jeffdomke** [comment]
@aulneau sorry, see two tickets opened on this one for some reason, please use this copy.

**Comment by aulneau** [comment]
@jeffdomke for future reference please include the page that the copy edits are one, thank you!
