### ISSUE TITLE
[Technology] Implement Resources section

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#904]
We have an improved version of the Technology page that makes it easier for developers to find the resources/links, and gets rid of that one ugly section. Designs (mobile too) are in dev/website.

![Screenshot 2019-05-28 at 10.19.36.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/27d64373-e674-49b4-81df-a8bb4a58325d)

**Comment by jeffdomke** [comment]
Eng calls missing date/time. 

Section below `We abstract...` is missing.
