### ISSUE TITLE
On homepage, the page to view full May rankings goes to app.co/mining 

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/blockstack.org#912]
On homepage, the page to view full May rankings goes to app.co/mining. 

Should it go to the most recent app mining rankings? Or do we want to keep as is. 
<img width="1088" alt="Screen Shot 2019-05-28 at 3 04 40 PM" src="https://user-images.githubusercontent.com/30627583/58505046-086e5900-815a-11e9-994d-b0825cb6097c.png">

**Comment by jeffdomke** [comment]
This is needed https://github.com/blockstack/app.co/pull/503 @hstove

**Comment by hstove** [comment]
This route is now live - app.co/mining/latest
