### ISSUE TITLE
About page copy change

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#913]
![Screen Shot 2019-05-28 at 3.23.33 PM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/daf58f19-8693-4601-bf9a-d388d40ab8f0)

**Comment by aulneau** [comment]
@jeffdomke please include text in your issues in the future for any copy changes. Retyping is error prone and time consuming.

**Comment by jeffdomke** [comment]
It was Freddie 😜
