### ISSUE TITLE
Dev highlights on landing page

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#915]
Passing along feedback: The Democracy Earth Wired article doesn’t mention Blockstack. Use another developer to highlight?

**Comment by cuevasm** [comment]
Personally, don't see why that matters all that much, I think it's pretty obvious democracy earth is built with Blockstack. The point of these is to show what amazing things our devs are doing, whether we're explicitly mentioned in the linked piece is inconsequential to me. Ideal, but not necessary.

**Comment by cuevasm** [comment]
If I'm overruled here I can try to dig up something else, but I think this one of the stronger stories we have

**Comment by jeffdomke** [comment]
@cuevasm I agree with you. A decision might be easier if we have a next-best-option to evaluate. I can't remember if you pulled one before that meets this criteria?

**Comment by jeffdomke** [comment]
https://makermag.com/2019/04/15/privacy-data-ownership/

https://bitcoinmagazine.com/articles/bitcoin-startup-working-free-speech-alternatives-patreon/ – no mention of blockstack. 

Also Noteriot but similar to Graphite. Seems as thought we don't have good solution here. Iceboxing.
