### ISSUE TITLE
"Sign in" in nav bar seems confusing

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/blockstack.org#926]
**Is your feature request related to a problem? Please describe.**
Not a problem per se, more a suggestion. I find the "Sign in" link on the main menu confusing, it seems to suggest I'm going to "sign into blockstack.org". That's the expectation most consumers / visitors to the website will have IMO, since that's the common pattern / behavior for most other websites / services.

**Describe the solution you'd like**
Maybe remove the "Sign in" button from the menu, or change to wording to clarify that it's going to log users into the hosted Blockstack browser instance.

**Comment by jeffdomke** [comment]
We know from the last few rounds of research that novice users seek this CTA on the site, especially when they get confused on ID recovery or signup for a new app. We probably should do more research to confirm this works properly now and I assume this will happen when we work on browser onboarding again. Agree it doesn't make perfect sense in our model, but it still might be the right solution from a behavior standpoint.
