### ISSUE TITLE
Paper translations design – need a way to signify the same paper but in an alt-language

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#927]
[![Screenshot_2019-05-30_20-06-13.png](https://mrkr.io/s/5cf037b504708d1b50f4c409/2)](https://mrkr.io/s/5cf037b504708d1b50f4c409/0)
---
### More Info

**Source URL**: [https://deploy-preview-804--blockstack.netlify.com/papers/](https://deploy-preview-804--blockstack.netlify.com/papers/)

<table><tr><td><strong>Browser</strong></td><td>Chrome 74.0.3729.169</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.4</td></tr><tr><td><strong>Viewport Size</strong></td><td>2048 x 1300</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by jasperjansz** [comment]
Trying to work towards a long-term solution so we don't have to revisit this later. I read we'll have 4 translations soon, I assume for both the white paper and the token paper:


![Screenshot 2019-06-05 at 13.17.01.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/9a15af2a-e6c9-4458-b5fa-53668421cccd)



In the short term, that would mean the following when selecting Chinese:


![Screenshot 2019-06-05 at 13.24.33.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/ecb75a3e-b531-4a93-90ce-ac52cebb45d9)

**Comment by jeffdomke** [comment]
I'm not sure this solution is best, I don't know if we'll have parity across the different languages in terms of what papers are translated and what aren't. Can't remember specifics anymore but thought we purposely want to show english as the primary, and the sub-languages as alternates (one level down in visual hierarchy) but can't remember rational. Maybe @blocks8 has some thoughts here.

**Comment by muneeb-ali** [comment]
Initial translations are only for the whitepaper but entirely possible that the token-paper can also get translated.

**Comment by blocks8** [comment]
Yes: 
"we purposely want to show english as the primary, and the other languages as alternates (one level down in visual hierarchy)" --> We didn't want each translation to have it's own white card because it then looked like there were 4 different whitepapers. Instead, 1 whitepaper card + 3 translations of it, they should belong together like a set.
