### ISSUE TITLE
Footer: Design error/success states for the email capture

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#933]

**Comment by jasperjansz** [comment]
See Dev/Website. @aulneau I've added two shades of green to the system: Green/10 and Green/Text. The shades we had previously did not have enough contrast between them to meet WCAG standards. 

We should not develop our own error handling for this given the limited space, so I'm fine with keeping what we have now for that.

![Screenshot 2019-06-04 at 17.11.35.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/ce394ddb-7e3d-4651-89b4-38e90ae0307c)

**Comment by jeffdomke** [comment]
Very subtle thing but bugged me quite a bit. Feels smooth now. Nice work fellas.
