### ISSUE TITLE
[Technology] Improve type hierarchy of the resources section

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#935]

**Comment by jasperjansz** [comment]
Done (https://www.figma.com/file/LDiZPndnqfRjZnwTIMCzNMjr/Website?node-id=1393%3A14665), assigning @aulneau

**Comment by jeffdomke** [comment]
This ticket is super cryptic. Just need a little more context on "resources section" please.

**Comment by jasperjansz** [comment]
This is a small tweak on the Resources section of the Technology page. The feedback was that the text hierarchy was off. Specifically, that the column titles ('Build your app', and 'Learn about Blockstack') were hardly noticeable.

I've increased the visual weight of the column titles and decreased the visual weight of each item in the column. 

Current:
![Screenshot 2019-07-16 at 17.40.44.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/be4f9bf4-a4e7-40a8-a397-23266120ae8b)


Improvement:
![Screenshot 2019-07-16 at 17.41.07.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/8e0015c2-d76f-4b1c-8a24-2a4d9ea37b40)

**Comment by jeffdomke** [comment]
@jasperjansz and @aulneau please confer on this engineering call text. I'm fine with skipping but maybe there are some reasons to keep it around.
