### ISSUE TITLE
[Technology] Improve Smart Contracts graphic

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#937]

**Comment by jeffdomke** [comment]
@jasperjansz think Thomas needs some more detail on how this graphic should behave. I see the issue here with scale and cropping. Also the way the photo terminates on the right side is a bit strange looking.

**Comment by aulneau** [comment]
Yes, this doesn't work based off of all our other sections. There are no sections within the body of the pages that has a graphic that extends beyond the panes like it does in the design here. Additionally, the design doesn't show what it would look like outside of the width it's designed for. @jasperjansz would love some recommendations from ya

**Comment by jasperjansz** [comment]
I edited the graphic to not extend beyond the screen, and fit our standard 488px width: https://www.figma.com/file/LDiZPndnqfRjZnwTIMCzNMjr/Website?node-id=1393%3A14665

**Comment by jasperjansz** [comment]
@aulneau this is very low-res for me:

![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/a31a9bd5-f2c1-44f9-b786-52dcec3b2cdc)
