### ISSUE TITLE
[Technology] The copy of the two main CTA's is different

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#938]
In the hero our main CTA says "Tutorials", while at the bottom of the page it says "Zero-to-dapp tutorial"

![Screenshot 2019-06-03 at 09.57.11.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/d634a501-c5c2-4205-bb19-6a0361a7d24d)![Screenshot 2019-06-03 at 09.57.00.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/2c8636f3-21c5-4032-8311-53fb5e23ef1b)

**Comment by aulneau** [comment]
@jeffdomke this is assigned to you

**Comment by jeffdomke** [comment]
Please change both to `Tutorials`
