### ISSUE TITLE
[Try Blockstack] Alternative to app cards

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#940]
We want to communicate:
- We have lots of apps
- In a lot of different categories
- They protect your digital rights

Any animation should be independent of scroll.

**Comment by jasperjansz** [comment]
I think the best solution for now is to remove the scroll-based animation, and make them scroll slowly by default. Here's a good example: https://www.apple.com/apple-arcade/.

If you agree please assign to yourself @aulneau

**Comment by jeffdomke** [comment]
I agree on the scrolling. The larger issue of improving the cards stands. @jasperjansz can we have a separate effort to upgrade those cards?
