### ISSUE TITLE
[Try Blockstack] Improve "True data ownership" graphic

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#941]
1. Make sure the shapes are instantly recognisable with the blur
2. Make video

**Comment by jasperjansz** [comment]
Done. Blurred images are now more recognizable: https://www.figma.com/file/LDiZPndnqfRjZnwTIMCzNMjr/Website?node-id=1486%3A15141. Assigning @aulneau

**Comment by jeffdomke** [comment]
Left comments in figma. Still think we can do better with the photo panel.

**Comment by aulneau** [comment]
@jasperjansz I am waiting on you for changes to this as it seems to still be in progress.

**Comment by jeffdomke** [comment]
![Screen Shot 2019-08-13 at 3.39.39 PM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/83208f08-e106-418f-a152-04996b51c19d)

Think we should remove "Jonny..." 
Copy is gendered. 
And on my display I'm seeing a subtle color distinction between the video area and bg color.
