### ISSUE TITLE
[Try Blockstack] Improve "Share, move, and connect" graphic

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#942]

**Comment by jasperjansz** [comment]
Done: https://www.figma.com/file/LDiZPndnqfRjZnwTIMCzNMjr/Website?node-id=1486%3A15141. Assigning @aulneau

**Comment by jeffdomke** [comment]
Is this animated. You're suggesting we use the doughnut photo? I have always considered that placeholder. What is a better photo?

**Comment by aulneau** [comment]
@jasperjansz sounds like this is still in progress on your end based off of @jeffdomke's comments?

**Comment by jeffdomke** [comment]
Shared my thoughts chatting with @jasperjansz
