### ISSUE TITLE
[Homepage] Improve news section

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#948]

**Comment by jasperjansz** [comment]
This section is much improved by aligning it to the new grid. The title and content are more connected.

Old grid (currently live):

![Screenshot 2019-07-03 at 10.10.36.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/7e59664f-3755-442c-973e-c72acfc0d177)

New grid:

![Screenshot 2019-07-03 at 10.10.22.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/5d301a8a-46bd-4b1d-9481-d77b191f6bb1)

@aulneau Also please note that we should align the font-size of the news item's headline with the sections below and above (20 instead of 16)

**Comment by jeffdomke** [comment]
![Screen Shot 2019-08-13 at 5.36.43 PM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/4c4d29e2-53f4-405b-b0f9-e9740a560019)

Compared staging to figma – typography and spacing is all way off. 

Checked on mobile and see a few spacing problems. Maybe @jasperjansz wants to give some guidance. 

![IMG_0176.PNG](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/386c99f0-bcfa-4404-9281-9d7f5bc17ed1)

Also some small alignment issues: 

![Screen Shot 2019-08-13 at 5.33.17 PM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/42c523cb-3f36-4035-8c13-64f157c3aef5)

**Comment by jasperjansz** [comment]
Couple things here:

Padding-top & -bottom: it would look better with 128px instead of 64px (in general)

Font-size: if we use the same size as in the press section, the events section (20px), it would look more consistent. It now implies some hierarchy between the press section and this news section

Padding-top & -bottom of the rows: if you make it 24px it will look less cramped

Last child is missing a border-bottom

I'm not sure how to fix the misalignment between the author and the date, css looks alright to me. Maybe remove the dot and just place a comma if that solves it?

I have added to Figma (latest components) a mobile design of this section

**Comment by jeffdomke** [comment]
![Screen Shot 2019-08-20 at 10.47.04 AM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/437ebf59-72dd-4183-b9e8-1c61f834b321)
