### ISSUE TITLE
[About] Alternative to hero section

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#951]
1. shouldn't rely on scroll

**Comment by jasperjansz** [comment]
Assigning this to @aulneau. This is the drag component.

**Comment by jeffdomke** [comment]
Page title missing?

**Comment by jeffdomke** [comment]
![Screen Shot 2019-08-20 at 10.39.25 AM.png](https://images.zenhubusercontent.com/5c01542d2c4f4d3a813340fc/76338579-5597-40aa-9e9c-b639d7dbf793)

Please work a bit more on making sure this is responsive and always looks good.

**Comment by jasperjansz** [comment]
@aulneau You have double padding here, 96px top and bottom on the parent div too. That causes the excessive white space

**Comment by jasperjansz** [comment]
@aulneau can we have a poster for these videos? Reason is it's kind of strange when the images to the right of videos load faster than the video.


![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/fb47fb9b-037f-4ee4-b208-6affe1f5072b)
