### ISSUE TITLE
[Try Blockstack] Improve section below CTA

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#954]

**Comment by jasperjansz** [comment]
Done, see: https://www.figma.com/file/LDiZPndnqfRjZnwTIMCzNMjr/Website?node-id=1486%3A15141. Assigning @aulneau.

**Comment by jeffdomke** [comment]
More context please.

**Comment by jasperjansz** [comment]
@jeffdomke 
Some time ago we spoke about this section below the blue CTA on the Try Blockstack page. It looks cramped, the columns aren't aligned, and is generally difficult to read. 


See the how it is currently:

![Screenshot 2019-07-16 at 19.13.04.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/497d90b7-52e7-452a-828e-d4ce0bb214a4)

The improved section:

![Frame 7.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/786d3a08-bdd0-4b9d-825b-cacfbd270d54)

Center aligning the CTA like the hero section frames the page. Increased width and white space makes the section below look less cramped and easier to understand.

**Comment by jeffdomke** [comment]
Just checked this and typography and spacing are quite off. Please implement as it is in the design. @jasperjansz can provide more guidance.

**Comment by jeffdomke** [comment]
Button sizes are off. Text color in figma #637282 and in stage looks #000
