### ISSUE TITLE
[About] Improve Investors section

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#963]
Currently, the text alignment is weird and the logos don't match the grid. Please see Dev/Website for the improvements:

• Center aligned text
• A grid for the logos

Additionally, I've found svg's for Lux Capital and Huobi Capital.

![Screenshot 2019-06-07 at 11.01.31.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/13197286-02e6-4126-9d45-55aea9360333)

![Screenshot 2019-06-07 at 11.01.43.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/0fb54c54-261e-4218-919c-dba56fc58f46)

**Comment by jeffdomke** [comment]
Looks great. Well done.
