### ISSUE TITLE
Update Chinese Whitepaper on https://blockstack.org/papers/

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack.org#964]
[Blockstack_Whitepaper_204-CN-final-0607.pdf](https://github.com/blockstack/blockstack.org/files/3267103/Blockstack_Whitepaper_204-CN-final-0607.pdf)

**Comment by aulneau** [comment]
updated in https://github.com/blockstack/blockstack.org/pull/958/commits/632825cb98570fd4413c703b7b5092e3caefc644
