### ISSUE TITLE
[About] Investors, add 'and more' item

### ISSUE THREAD

**Issue by aulneau** [blockstack/blockstack.org#966]
We need a link to the angel.co/blockstack page that states 'And more'.

**Comment by aulneau** [comment]
![Screen Shot 2019-06-10 at 2 07 56 PM](https://user-images.githubusercontent.com/11803153/59219915-2d66c100-8b89-11e9-9a20-099eba63f457.png)


I added this, let me know if you want something different

**Comment by jasperjansz** [comment]
looks good to me @aulneau

**Comment by jeffdomke** [comment]
@jasperjansz if you review these please move to done.
