### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [blockstack/blockstack.org#968]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/blockstack/blockstack.org/blob/master/package.json#L79

See https://nodejs.org/api/fs.html

You might want to remove it using `yarn remove fs`.

**Comment by aulneau** [comment]
@DanielRuf Thanks for this! it will be fixed in the next release.
