### ISSUE TITLE
Update copy on /technology

### ISSUE THREAD

**Issue by cuevasm** [blockstack/blockstack.org#973]
![image](https://user-images.githubusercontent.com/6131188/60271895-ff32f200-98a7-11e9-8d02-32f3fe7c0533.png)

**Clarity: a predictable smart contract language**
Clarity is a decidable, interpreted smart contract language that optimizes for predictability and security. It empowers you to be certain of how your code behaves prior to pushing it into production, so you don’t have to worry about security issues, side effects, or unexpected fees.

Learn more - https://blog.blockstack.org/introducing-clarity-the-language-for-predictable-smart-contracts/

**Comment by jeffdomke** [comment]
Suggest: "Clarity Smart Contracts". None of the other panels have a subtitle like follow on label and you're burying the lead, the word people are hunting for is "smart contracts". And the suggested label is more parallel to above when we say "Stacks blockchain"

**Comment by cuevasm** [comment]
Fine, this is from Jason the Product Marketer and was deferring to him
