### ISSUE TITLE
Fix contact link in footer

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#975]
[![Screenshot_2019-07-08_19-50-29.png](https://mrkr.io/s/5d239e857003026246d32f47/2)](https://mrkr.io/s/5d239e857003026246d32f47/0)
---
### More Info

**Source URL**: [https://blockstack.org/#](https://blockstack.org/#)

<table><tr><td><strong>Browser</strong></td><td>Chrome 75.0.3770.100</td></tr><tr><td><strong>Screen Size</strong></td><td>2560 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 10.14.5</td></tr><tr><td><strong>Viewport Size</strong></td><td>2560 x 1417</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by aulneau** [comment]
Fixed and deployed
