### ISSUE TITLE
[Homepage] Replace 'Build apps' image

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#981]
![Build apps img.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/9f83c501-8d27-4dab-be10-9fe534e64e13)

**Comment by jeffdomke** [comment]
Staging does not match latest figma component.

**Comment by jeffdomke** [comment]
Same comment as before. Please talk to Jasper or share the resolution here.
