### ISSUE TITLE
Improve design/coms for more click through to zero-to-dapp

### ISSUE THREAD

**Issue by jeffdomke** [blockstack/blockstack.org#982]
Current conversion and bounce rates are poor

**Comment by moxiegirl** [comment]
Maybe we time this with the StackIt tutorial.  We will have two tracks.

**Comment by jasperjansz** [comment]
Ideas:

add 'Tutorials' explicitly to the menu under 'Technology'
add 'Tutorials' to the 'Resources' section on 'Technology'

The technology page is very information heavy and long. What if we embed the first step of a tutorial on the page, such as choose a tutorial to start. 

Redo the 'Build apps' section on the homepage to feature tutorials

**Comment by jeffdomke** [comment]
Ideas: 
- Reduce the number of links on the top section. 
- Add more CTAs across page. 
- Make the hero image have an on hover CTA
- Agree, we can preview the tutorial more/better. 

Todos: 
- Analyze the traffic more (see where our inbound is converting well). 
- Investigate tutorial onramps – maybe we can find some ideas out there.
