### ISSUE TITLE
[Homepage] Decrease white space in the hero

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/blockstack.org#991]
I see on some test recordings the white space is too excessive in relation to the screen, causing almost the entire hero to be white. One person also did not scroll beyond the hero, presumably because of this.

The margins I used in the design are 80px between the menu and the hero text and 80px between that section and the apps below.

Currently, in production, it's 120px and 128px, which is a little excessive.

**Comment by krtb** [comment]
Hi, can I take this issue?
